import type { LearningUnit } from "@/lib/types";

export const japaneseScriptsUnit: LearningUnit = {
  id: "jp-three-scripts",
  pathId: "japanese",
  title: "Three writing systems",
  titleJa: "3つの文字",
  subtitle: "Hiragana, katakana, and kanji (recognize before you memorize)",
  xpReward: 100,
  tutorial: {
    title: "Why Japanese has three scripts",
    titleJa: "なぜ文字が3種類？",
    bodyEn:
      "Modern Japanese mixes three systems: hiragana (native grammar and words), katakana (loanwords and emphasis), and kanji (meaning characters from Chinese). You do not need to write them yet. First, learn to tell them apart by look.",
    bodyJa:
      "現代日本語はひらがな（和語・文法）、カタカナ（外来語・強調）、漢字（意味を持つ字）を混ぜて使います。まだ書かなくてOK。まずは見た目で見分けます。",
    tips: [
      "Hiragana looks round and soft",
      "Katakana looks angular and sharp",
      "Kanji often looks denser / more complex",
    ],
  },
  exercises: [
    {
      id: "jp-sc-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which line is hiragana?",
      promptJa: "ひらがなはどれ？",
      choices: [
        { id: "a", label: "A) あいうえお" },
        { id: "b", label: "B) アイウエオ" },
        { id: "c", label: "C) 日本語" },
        { id: "d", label: "D) ABCDE" },
      ],
      correctChoiceId: "a",
      explanationEn: "あいうえお is hiragana. アイウエオ is katakana.",
      explanationJa: "あいうえおはひらがな。アイウエオはカタカナです。",
    },
    {
      id: "jp-sc-2",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which line is katakana?",
      promptJa: "カタカナはどれ？",
      choices: [
        { id: "a", label: "A) さしすせそ" },
        { id: "b", label: "B) カキクケコ" },
        { id: "c", label: "C) 山本" },
        { id: "d", label: "D) hello" },
      ],
      correctChoiceId: "b",
      explanationEn: "カキクケコ is katakana (angular).",
      explanationJa: "カキクケコはカタカナ（角ばった形）です。",
    },
    {
      id: "jp-sc-3",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which contains kanji?",
      promptJa: "漢字を含むのは？",
      choices: [
        { id: "a", label: "A) ねこ" },
        { id: "b", label: "B) ネコ" },
        { id: "c", label: "C) 人" },
        { id: "d", label: "D) neko" },
      ],
      correctChoiceId: "c",
      explanationEn: "人 is a kanji meaning person.",
      explanationJa: "人は「ひと」を表す漢字です。",
    },
    {
      id: "jp-sc-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Loanwords like 'coffee' are usually written in:",
      promptJa: "コーヒーのような外来語は主に何で書く？",
      choices: [
        { id: "a", label: "A) Katakana" },
        { id: "b", label: "B) Only English letters forever" },
        { id: "c", label: "C) Only kanji" },
        { id: "d", label: "D) Numbers" },
      ],
      correctChoiceId: "a",
      explanationEn: "Coffee is コーヒー in katakana.",
      explanationJa: "coffee はカタカナで コーヒー と書きます。",
    },
    {
      id: "jp-sc-5",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick the hiragana set (round script).",
      promptJa: "ひらがな（丸みのある字）を選ぶ。",
      choices: [
        { id: "a", label: "A) たちつてと" },
        { id: "b", label: "B) タチツテト" },
        { id: "c", label: "C) 東京" },
        { id: "d", label: "D) Tokyo" },
      ],
      correctChoiceId: "a",
      explanationEn: "たちつてと is hiragana.",
      explanationJa: "たちつてとはひらがなです。",
    },
  ],
};
