import type { LearningUnit } from "@/lib/types";

export const japaneseSoundsUnit: LearningUnit = {
  id: "jp-sounds",
  pathId: "japanese",
  title: "Japanese sounds",
  titleJa: "日本語の音",
  subtitle: "Vowels first, using romaji + audio (no kana yet)",
  xpReward: 90,
  tutorial: {
    title: "Five vowels",
    titleJa: "5つの母音",
    bodyEn:
      "Japanese has five pure vowels: a, i, u, e, o. They are short and clear (not English diphthongs). Master these sounds before you learn hiragana shapes. We use romaji here on purpose.",
    bodyJa:
      "日本語の母音は a i u e o の5つ。短くはっきり（英語のような二重母音にしない）。ひらがなの形の前に、まず音を体に入れます。ここではローマ字を使います。",
    tips: [
      "a like 'ah', i like 'ee', u like 'oo' (short)",
      "e like 'eh', o like 'oh' (short)",
      "Listen, then repeat",
    ],
  },
  exercises: [
    {
      id: "jp-s-1",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which vowel do you hear?",
      promptJa: "聞こえた母音は？",
      ttsText: "あ",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) a" },
        { id: "b", label: "B) i" },
        { id: "c", label: "C) u" },
        { id: "d", label: "D) e" },
      ],
      correctChoiceId: "a",
      explanationEn: "You heard a (あ).",
      explanationJa: "a（あ）の音です。",
    },
    {
      id: "jp-s-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which vowel?",
      promptJa: "聞こえた母音は？",
      ttsText: "い",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) o" },
        { id: "b", label: "B) i" },
        { id: "c", label: "C) a" },
        { id: "d", label: "D) u" },
      ],
      correctChoiceId: "b",
      explanationEn: "You heard i (い).",
      explanationJa: "i（い）の音です。",
    },
    {
      id: "jp-s-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak the five vowels in order: a i u e o.",
      promptJa: "母音を順に言ってみましょう：a i u e o。",
      ttsText: "あいうえお",
      ttsLang: "ja-JP",
      explanationEn: "This vowel set becomes the hiragana あ行 next.",
      explanationJa: "この母音が、次のひらがなあ行になります。",
    },
    {
      id: "jp-s-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Japanese 'u' should sound most like:",
      promptJa: "日本語の u に近い発音は？",
      choices: [
        { id: "a", label: "A) A short 'oo' (not English 'you')" },
        { id: "b", label: "B) English 'you' with a Y glide" },
        { id: "c", label: "C) English 'uh' in 'cup'" },
        { id: "d", label: "D) Silent every time" },
      ],
      correctChoiceId: "a",
      explanationEn: "Keep u pure and short; avoid a 'y' sound.",
      explanationJa: "u は短く純粋に。you のような y を入れない。",
    },
    {
      id: "jp-s-5",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which vowel?",
      promptJa: "聞こえた母音は？",
      ttsText: "お",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) e" },
        { id: "b", label: "B) a" },
        { id: "c", label: "C) o" },
        { id: "d", label: "D) i" },
      ],
      correctChoiceId: "c",
      explanationEn: "You heard o (お).",
      explanationJa: "o（お）の音です。",
    },
  ],
};
