import type { LearningUnit } from "@/lib/types";

export const japaneseBridgeUnit: LearningUnit = {
  id: "jp-before-hiragana",
  pathId: "japanese",
  title: "Ready for hiragana",
  titleJa: "ひらがな準備",
  subtitle: "Connect sounds to your first characters",
  xpReward: 90,
  tutorial: {
    title: "From sound to shape",
    titleJa: "音から形へ",
    bodyEn:
      "Each hiragana stands for one mora (a beat), usually a vowel or consonant+vowel. Example: a → あ, ka → か. Next lessons teach one line at a time. Stroke order tip: top to bottom, left to right.",
    bodyJa:
      "ひらがな1字はだいたい1拍（母音、または子音＋母音）。例：a→あ、ka→か。次から行ごとに学びます。書き順の目安は上から下、左から右。",
    tips: [
      "One character ≈ one beat",
      "Do not rush; 5 characters per line is enough",
      "Keep using audio every day",
    ],
  },
  exercises: [
    {
      id: "jp-b-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The hiragana for the vowel 'a' will be:",
      promptJa: "母音 a のひらがなは？",
      choices: [
        { id: "a", label: "A) あ" },
        { id: "b", label: "B) か" },
        { id: "c", label: "C) ア" },
        { id: "d", label: "D) 人" },
      ],
      correctChoiceId: "a",
      explanationEn: "あ is hiragana a. ア is katakana a.",
      explanationJa: "あがひらがなの a。アはカタカナです。",
    },
    {
      id: "jp-b-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen to 'ka'. You will soon write it as か.",
      promptJa: "ka の音を聞く。まもなく か と書きます。",
      ttsText: "か",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) ka" },
        { id: "b", label: "B) sa" },
        { id: "c", label: "C) ma" },
        { id: "d", label: "D) na" },
      ],
      correctChoiceId: "a",
      explanationEn: "That beat is ka.",
      explanationJa: "ka の音です。",
    },
    {
      id: "jp-b-3",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Best stroke-order habit:",
      promptJa: "書き順の良い習慣は？",
      choices: [
        { id: "a", label: "A) Top to bottom, left to right" },
        { id: "b", label: "B) Random scribbles" },
        { id: "c", label: "C) Bottom to top only" },
        { id: "d", label: "D) Skip writing forever" },
      ],
      correctChoiceId: "a",
      explanationEn: "Japanese characters generally go top→bottom and left→right.",
      explanationJa: "基本は上から下、左から右です。",
    },
    {
      id: "jp-b-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say a-i-u-e-o one more time. Next unit: write あいうえお.",
      promptJa: "もう一度 a i u e o。次で あいうえお を書きます。",
      ttsText: "あいうえお",
      ttsLang: "ja-JP",
      explanationEn: "You are ready for the hiragana あ-line.",
      explanationJa: "ひらがなあ行の準備OKです。",
    },
    {
      id: "jp-b-5",
      kind: "write-choice",
      skill: "write",
      prompt: "Preview: pick hiragana 'a'.",
      promptJa: "予習：ひらがなの a を選ぶ。",
      choices: [
        { id: "a", label: "い" },
        { id: "b", label: "う" },
        { id: "c", label: "あ" },
        { id: "d", label: "え" },
      ],
      correctChoiceId: "c",
      explanationEn: "あ is your first hiragana target.",
      explanationJa: "あが最初のひらがなターゲットです。",
    },
  ],
};
