import type { LearningUnit } from "@/lib/types";

/** First real alphabet lesson: teach あいうえお before any line quiz. */
export const japaneseBridgeUnit: LearningUnit = {
  id: "jp-before-hiragana",
  pathId: "japanese",
  title: "Learn あいうえお",
  titleJa: "あいうえおを覚える",
  subtitle: "Your first hiragana alphabet: study each letter, then a tiny check",
  xpReward: 110,
  tutorial: {
    title: "This is the alphabet lesson",
    titleJa: "ここがアルファベットの授業です",
    bodyEn:
      "Japanese does not use A B C. It uses hiragana letters. Your first five are あ い う え お (a i u e o). Next you will see each letter large, with romaji spelling and Listen audio. Only after that comes a short check. Learning comes before testing.",
    bodyJa:
      "日本語の基本は ABC ではなくひらがなです。最初の5字は あいうえお（a i u e o）。次の画面で1字ずつ大きく見せて、ローマ字と音声で教えます。そのあとに短い確認があります。テストの前に学習します。",
    tips: [
      "Tap Listen on every letter",
      "Say the romaji while looking at the kana",
      "Do not rush into the check until you know all five",
    ],
  },
  teach: [
    {
      glyph: "あ",
      reading: "a",
      tipEn: "Letter 1 of 5. あ = a. Open vowel, short and clear.",
      tipJa: "1文字目。あ＝a。口を開けて短く。",
      ttsText: "あ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "い",
      reading: "i",
      tipEn: "Letter 2 of 5. い = i. Like a short ee.",
      tipJa: "2文字目。い＝i。短く。",
      ttsText: "い",
      ttsLang: "ja-JP",
    },
    {
      glyph: "う",
      reading: "u",
      tipEn: "Letter 3 of 5. う = u. Round lips; not yoo.",
      tipJa: "3文字目。う＝u。唇を丸めて。",
      ttsText: "う",
      ttsLang: "ja-JP",
    },
    {
      glyph: "え",
      reading: "e",
      tipEn: "Letter 4 of 5. え = e. Like e in get.",
      tipJa: "4文字目。え＝e。",
      ttsText: "え",
      ttsLang: "ja-JP",
    },
    {
      glyph: "お",
      reading: "o",
      tipEn: "Letter 5 of 5. お = o. Pure o sound.",
      tipJa: "5文字目。お＝o。",
      ttsText: "お",
      ttsLang: "ja-JP",
    },
  ],
  exercises: [
    {
      id: "jp-b-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Check: which letter is a?",
      promptJa: "確認：a はどれ？",
      choices: [
        { id: "a", label: "あ" },
        { id: "b", label: "い" },
        { id: "c", label: "う" },
        { id: "d", label: "え" },
      ],
      correctChoiceId: "a",
      explanationEn: "あ = a. You just learned it.",
      explanationJa: "あ＝a。今覚えた字です。",
    },
    {
      id: "jp-b-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Check: listen, then pick the letter.",
      promptJa: "確認：聞いて文字を選ぶ。",
      ttsText: "い",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "う" },
        { id: "b", label: "あ" },
        { id: "c", label: "い" },
        { id: "d", label: "お" },
      ],
      correctChoiceId: "c",
      explanationEn: "That was い (i).",
      explanationJa: "い（i）でした。",
    },
    {
      id: "jp-b-3",
      kind: "write-choice",
      skill: "write",
      prompt: "Check: pick the letter for u.",
      promptJa: "確認：u の字は？",
      choices: [
        { id: "a", label: "え" },
        { id: "b", label: "う" },
        { id: "c", label: "お" },
        { id: "d", label: "あ" },
      ],
      correctChoiceId: "b",
      explanationEn: "う = u.",
      explanationJa: "う＝u。",
    },
    {
      id: "jp-b-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say the whole alphabet line: あいうえお.",
      promptJa: "あいうえお をまとめて言ってください。",
      ttsText: "あいうえお",
      ttsLang: "ja-JP",
      explanationEn: "That line is a-i-u-e-o. Next lessons teach the next rows the same way.",
      explanationJa: "あいうえお＝a i u e o。次の行も同じやり方で教えます。",
    },
    {
      id: "jp-b-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does Japanese use instead of A B C for basic sounds?",
      promptJa: "基本の音に使うのは？",
      choices: [
        { id: "a", label: "A) Only English letters" },
        { id: "b", label: "B) Hiragana (and later katakana)" },
        { id: "c", label: "C) Only numbers" },
        { id: "d", label: "D) Emoji" },
      ],
      correctChoiceId: "b",
      explanationEn: "Hiragana is the first alphabet you master. Katakana comes after.",
      explanationJa: "最初にひらがな、そのあとカタカナです。",
    },
  ],
};
