import type { LearningUnit } from "@/lib/types";

/** First real lesson: survival phrases with listen / speak / meaning drills. */
export const japaneseWelcomeUnit: LearningUnit = {
  id: "jp-welcome",
  pathId: "japanese",
  title: "First phrases",
  titleJa: "はじめてのフレーズ",
  subtitle: "Hello, thanks, yes, no. Speak before you read kana.",
  xpReward: 100,
  tutorial: {
    title: "Speak useful Japanese today",
    titleJa: "今日から使える日本語",
    bodyEn:
      "You will learn four high-frequency phrases with audio: konnichiwa (hello), arigatou (thanks), hai (yes), and iie (no). Romaji is only a bridge. Listen carefully, then say each phrase out loud. Next lessons teach the five vowels and how Japanese writing works.",
    bodyJa:
      "よく使う4フレーズを音声で学びます：こんにちは、ありがとう、はい、いいえ。ローマ字は補助です。よく聞いてから声に出してください。次のレッスンで母音と文字の仕組みに進みます。",
    tips: [
      "Listen twice before you answer",
      "Match the rhythm, not English stress",
      "Hai and iie are short and clear",
    ],
  },
  exercises: [
    {
      id: "jp-w-1",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which phrase did you hear?",
      promptJa: "聞こえたフレーズは？",
      ttsText: "こんにちは",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) konnichiwa (hello)" },
        { id: "b", label: "B) arigatou (thanks)" },
        { id: "c", label: "C) hai (yes)" },
        { id: "d", label: "D) iie (no)" },
      ],
      correctChoiceId: "a",
      explanationEn: "こんにちは / konnichiwa is the daytime hello.",
      explanationJa: "こんにちはは昼間のあいさつです。",
    },
    {
      id: "jp-w-2",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say konnichiwa after LUMI.",
      promptJa: "話す：こんにちは と言ってみましょう。",
      ttsText: "こんにちは",
      ttsLang: "ja-JP",
      explanationEn: "Keep vowels clear: ko-n-ni-chi-wa (about 5 beats).",
      explanationJa: "こ・ん・に・ち・は の拍を意識して。",
    },
    {
      id: "jp-w-3",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which phrase means thank you?",
      promptJa: "「ありがとう」はどれ？",
      ttsText: "ありがとう",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) konnichiwa" },
        { id: "b", label: "B) arigatou" },
        { id: "c", label: "C) iie" },
        { id: "d", label: "D) ohayou" },
      ],
      correctChoiceId: "b",
      explanationEn: "ありがとう / arigatou means thank you.",
      explanationJa: "ありがとうは感謝の言葉です。",
    },
    {
      id: "jp-w-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say arigatou after LUMI.",
      promptJa: "話す：ありがとう と言ってみましょう。",
      ttsText: "ありがとう",
      ttsLang: "ja-JP",
      explanationEn: "A more polite form later is arigatou gozaimasu.",
      explanationJa: "丁寧形は「ありがとうございます」です。",
    },
    {
      id: "jp-w-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Someone asks if you want tea. You want it. What do you say?",
      promptJa: "お茶を勧められて、欲しいときは？",
      choices: [
        { id: "a", label: "A) iie (no)" },
        { id: "b", label: "B) hai (yes)" },
        { id: "c", label: "C) sayounara (goodbye)" },
        { id: "d", label: "D) gomen (sorry only)" },
      ],
      correctChoiceId: "b",
      explanationEn: "はい / hai is yes. いいえ / iie is no.",
      explanationJa: "はい＝yes、いいえ＝no です。",
    },
    {
      id: "jp-w-6",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Is this yes or no?",
      promptJa: "聞こえたのは yes？ no？",
      ttsText: "いいえ",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) hai (yes)" },
        { id: "b", label: "B) iie (no)" },
        { id: "c", label: "C) arigatou" },
        { id: "d", label: "D) konnichiwa" },
      ],
      correctChoiceId: "b",
      explanationEn: "いいえ / iie is no. It is longer than hai.",
      explanationJa: "いいえは no。はいより長い音です。",
    },
    {
      id: "jp-w-7",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say hai, then iie.",
      promptJa: "話す：はい、つづけて いいえ。",
      ttsText: "はい。いいえ。",
      ttsLang: "ja-JP",
      explanationEn: "Contrast short hai with fuller iie.",
      explanationJa: "短い「はい」と、はっきりした「いいえ」を対比して。",
    },
    {
      id: "jp-w-8",
      kind: "write-choice",
      skill: "write",
      prompt: "Match meaning to phrase: thank you",
      promptJa: "意味合わせ：thank you",
      choices: [
        { id: "a", label: "A) konnichiwa" },
        { id: "b", label: "B) hai" },
        { id: "c", label: "C) arigatou" },
        { id: "d", label: "D) iie" },
      ],
      correctChoiceId: "c",
      explanationEn: "arigatou = thank you.",
      explanationJa: "arigatou＝ありがとう＝thank you。",
    },
  ],
};
