import type { LearningUnit } from "@/lib/types";

export const japaneseGreetingsUnit: LearningUnit = {
  id: "jp-greetings-basics",
  pathId: "japanese",
  title: "Greetings",
  titleJa: "あいさつ",
  subtitle: "Hello, thanks, goodbye, and polite basics",
  xpReward: 120,
  tutorial: {
    title: "Everyday greetings",
    titleJa: "毎日のあいさつ",
    bodyEn:
      "Start speaking Japanese with high-frequency greetings. Politeness matters: です／ます style is safe for strangers and classmates. Listen to the melody, then say it yourself.",
    bodyJa:
      "頻度の高いあいさつから話しましょう。初対面では丁寧体が安心です。リズムを聞いてから自分でも言ってみます。",
    tips: [
      "こんにちは is for daytime hello",
      "ありがとう vs ありがとうございます (more polite)",
      "さようなら is a fuller goodbye",
    ],
  },
  exercises: [
    {
      id: "jp-gr-1",
      kind: "listen-choice",
      prompt: "What did you hear?",
      promptJa: "聞こえたのは？",
      ttsText: "こんにちは",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) Good morning (ohayou)" },
        { id: "b", label: "B) Hello / Good afternoon" },
        { id: "c", label: "C) Good night" },
        { id: "d", label: "D) Excuse me" },
      ],
      correctChoiceId: "b",
      explanationEn: "こんにちは is the standard daytime hello.",
      explanationJa: "こんにちはは昼間のあいさつです。",
    },
    {
      id: "jp-gr-2",
      kind: "multiple-choice",
      prompt: "How do you say thank you politely?",
      promptJa: "丁寧な「ありがとう」は？",
      choices: [
        { id: "a", label: "A) おはよう" },
        { id: "b", label: "B) ありがとうございます" },
        { id: "c", label: "C) さようなら" },
        { id: "d", label: "D) いいえ" },
      ],
      correctChoiceId: "b",
      explanationEn: "ありがとうございます is the polite thank you.",
      explanationJa: "ありがとうございますが丁寧です。",
    },
    {
      id: "jp-gr-3",
      kind: "listen-choice",
      prompt: "Choose the meaning.",
      promptJa: "意味を選ぶ。",
      ttsText: "おはようございます",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "A) Good morning (polite)" },
        { id: "b", label: "B) Good evening" },
        { id: "c", label: "C) See you later" },
        { id: "d", label: "D) I'm sorry" },
      ],
      correctChoiceId: "a",
      explanationEn: "おはようございます is polite good morning.",
      explanationJa: "おはようございますは丁寧な朝のあいさつです。",
    },
    {
      id: "jp-gr-4",
      kind: "multiple-choice",
      prompt: "Which means goodbye?",
      promptJa: "「さようなら」の意味は？",
      choices: [
        { id: "a", label: "A) Please" },
        { id: "b", label: "B) Goodbye" },
        { id: "c", label: "C) Yes" },
        { id: "d", label: "D) Delicious" },
      ],
      correctChoiceId: "b",
      explanationEn: "さようなら means goodbye.",
      explanationJa: "さようならは別れのあいさつです。",
    },
    {
      id: "jp-gr-5",
      kind: "speak-prompt",
      prompt: "Say ありがとう after Lumi.",
      promptJa: "ありがとう と言ってみましょう。",
      ttsText: "ありがとう",
      ttsLang: "ja-JP",
      expectedSpeech: ["ありがとう", "arigatou", "arigato"],
      explanationEn: "ありがとう is a casual thank you among friends.",
      explanationJa: "ありがとうはカジュアルな感謝の言葉です。",
    },
  ],
};
