import type { LearningUnit } from "@/lib/types";

export const japaneseHiraganaAUnit: LearningUnit = {
  id: "jp-hiragana-a-line",
  pathId: "japanese",
  title: "Hiragana あ行",
  titleJa: "ひらがな あ行",
  subtitle: "Read, write, speak, listen: あいうえお",
  xpReward: 100,
  tutorial: {
    title: "Meet hiragana",
    titleJa: "ひらがな入門",
    bodyEn:
      "Hiragana is one of the Japanese phonetic scripts, alongside katakana and kanji. Every Lumi Japanese lesson follows the same order: read, then write, then speak, then listen. Today is the あ-line: a, i, u, e, o.",
    bodyJa:
      "ひらがなはカタカナ・漢字と並ぶ表音文字です。Lumiの日本語レッスンは毎回「読む→書く→話す→聞く」の順です。今日はあ行（あいうえお）です。",
    tips: [
      "Read the shape before you write it",
      "Trace stroke order: top to bottom, left to right",
      "Keep vowels short and pure",
    ],
  },
  exercises: [
    {
      id: "jp-a-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Read: which character is 'a'?",
      promptJa: "読む練習：「a」のひらがなはどれ？",
      choices: [
        { id: "a", label: "あ" },
        { id: "b", label: "い" },
        { id: "c", label: "う" },
        { id: "d", label: "え" },
      ],
      correctChoiceId: "a",
      explanationEn: "あ is read as 'a'.",
      explanationJa: "あ は a と読みます。",
    },
    {
      id: "jp-a-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: which kana do you write for 'i'?",
      promptJa: "書く練習：「i」を書くとどれ？",
      choices: [
        { id: "a", label: "う" },
        { id: "b", label: "い" },
        { id: "c", label: "お" },
        { id: "d", label: "あ" },
      ],
      correctChoiceId: "b",
      explanationEn: "You write い for 'i'.",
      explanationJa: "i は い と書きます。",
    },
    {
      id: "jp-a-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say う after Lumi, then continue.",
      promptJa: "話す練習：う を声に出して言ってください。",
      ttsText: "う",
      ttsLang: "ja-JP",
      explanationEn: "う is 'u'. Round your lips; avoid English 'yoo'.",
      explanationJa: "う は u。唇を丸めて短く。",
    },
    {
      id: "jp-a-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen: which character do you hear?",
      promptJa: "聞く練習：聞こえた文字は？",
      ttsText: "え",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "あ" },
        { id: "b", label: "お" },
        { id: "c", label: "え" },
        { id: "d", label: "い" },
      ],
      correctChoiceId: "c",
      explanationEn: "You heard え (e).",
      explanationJa: "聞こえたのは え（e）です。",
    },
    {
      id: "jp-a-5",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: choose the kana for 'o'.",
      promptJa: "書く練習：「o」はどれ？",
      choices: [
        { id: "a", label: "お" },
        { id: "b", label: "あ" },
        { id: "c", label: "う" },
        { id: "d", label: "い" },
      ],
      correctChoiceId: "a",
      explanationEn: "お is the written form for 'o'.",
      explanationJa: "o は お と書きます。",
    },
  ],
};
