import type { LearningUnit } from "@/lib/types";

export const japaneseHiraganaSaUnit: LearningUnit = {
  id: "jp-hiragana-sa-line",
  pathId: "japanese",
  title: "Hiragana さ行",
  titleJa: "ひらがな さ行",
  subtitle: "Read, write, speak, listen: さしすせそ",
  xpReward: 100,
  tutorial: {
    title: "The S-line",
    titleJa: "さ行",
    bodyEn:
      "The さ-line is sa, shi, su, se, so. Note that し is 'shi', not 'si'. Order: read, write, speak, listen.",
    bodyJa:
      "さ行は さ・し・す・せ・そ。し は shi と読みます。読む→書く→話す→聞くで練習します。",
    tips: ["Remember し = shi", "す is a soft 'su'", "Pair listening with speaking"],
  },
  exercises: [
    {
      id: "jp-sa-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Read: which is 'sa'?",
      promptJa: "読む：「sa」はどれ？",
      choices: [
        { id: "a", label: "さ" },
        { id: "b", label: "し" },
        { id: "c", label: "す" },
        { id: "d", label: "そ" },
      ],
      correctChoiceId: "a",
      explanationEn: "さ = sa.",
      explanationJa: "さ = sa です。",
    },
    {
      id: "jp-sa-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: which kana is 'shi'?",
      promptJa: "書く：「shi」はどれ？",
      choices: [
        { id: "a", label: "さ" },
        { id: "b", label: "し" },
        { id: "c", label: "せ" },
        { id: "d", label: "そ" },
      ],
      correctChoiceId: "b",
      explanationEn: "し = shi.",
      explanationJa: "し = shi です。",
    },
    {
      id: "jp-sa-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say す.",
      promptJa: "話す：す と言ってください。",
      ttsText: "す",
      ttsLang: "ja-JP",
      explanationEn: "す = su.",
      explanationJa: "す = su です。",
    },
    {
      id: "jp-sa-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen: which kana did you hear?",
      promptJa: "聞く：聞こえたかなは？",
      ttsText: "せ",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "そ" },
        { id: "b", label: "せ" },
        { id: "c", label: "さ" },
        { id: "d", label: "す" },
      ],
      correctChoiceId: "b",
      explanationEn: "せ = se.",
      explanationJa: "せ = se です。",
    },
    {
      id: "jp-sa-5",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: choose そ.",
      promptJa: "書く：そ を選ぶ。",
      choices: [
        { id: "a", label: "さ" },
        { id: "b", label: "し" },
        { id: "c", label: "す" },
        { id: "d", label: "そ" },
      ],
      correctChoiceId: "d",
      explanationEn: "そ = so.",
      explanationJa: "そ = so です。",
    },
  ],
};
