import type { LearningUnit } from "@/lib/types";

export const japaneseHiraganaYouonUnit: LearningUnit = {
  id: "jp-hiragana-youon",
  pathId: "japanese",
  title: "Hiragana youon",
  titleJa: "ひらがな 拗音",
  subtitle: "Read, write, speak, listen: きゃしゃちゃ and friends",
  xpReward: 120,
  tutorial: {
    title: "Small ゃ ゅ ょ",
    titleJa: "小さいゃゅょ",
    bodyEn:
      "Youon (拗音, youon) combine i-column kana with a small ゃ, ゅ, or ょ. Say them as one beat: きゃ is kya (not ki-ya). Today: きゃ, しゃ, ちゃ, にゃ, ひゃ, みゃ, りゃ, plus voiced ぎゃ, じゃ, びゃ.",
    bodyJa:
      "拗音（ようおん）はい段のかなに小さいゃ・ゅ・ょを付けます。1拍で：きゃは kya（ki-ya ではない）。今日は きゃ・しゃ・ちゃ・にゃ・ひゃ・みゃ・りゃ、濁音の ぎゃ・じゃ・びゃ です。",
    tips: [
      "The second kana is half-size: ゃ not や",
      "Keep one mora: kya, sha, cha",
      "じ + ゃ makes じゃ (ja)",
    ],
  },
  teach: [
    {
      glyph: "きゃ",
      reading: "kya",
      tipEn: "きゃ = kya. き + small ゃ as one beat.",
      tipJa: "きゃ＝kya。き＋小さいゃで1拍。",
      ttsText: "きゃ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "しゃ",
      reading: "sha",
      tipEn: "しゃ = sha.",
      tipJa: "しゃ＝sha。",
      ttsText: "しゃ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "ちゃ",
      reading: "cha",
      tipEn: "ちゃ = cha.",
      tipJa: "ちゃ＝cha。",
      ttsText: "ちゃ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "にゃ",
      reading: "nya",
      tipEn: "にゃ = nya.",
      tipJa: "にゃ＝nya。",
      ttsText: "にゃ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "じゃ",
      reading: "ja",
      tipEn: "じゃ = ja (じ + small ゃ).",
      tipJa: "じゃ＝ja。",
      ttsText: "じゃ",
      ttsLang: "ja-JP",
    },
  ],
  exercises: [
    {
      id: "jp-youon-read",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Read: which kana is 'kya'?",
      promptJa: "読む：「kya」はどれ？",
      choices: [
        { id: "a", label: "きゃ" },
        { id: "b", label: "きや" },
        { id: "c", label: "しゃ" },
        { id: "d", label: "にゃ" },
      ],
      correctChoiceId: "a",
      explanationEn: "きゃ is kya: き + small ゃ as one sound.",
      explanationJa: "きゃ は kya。き＋小さいゃで1音です。",
    },
    {
      id: "jp-youon-write",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: which is 'sha'?",
      promptJa: "書く：「sha」はどれ？",
      choices: [
        { id: "a", label: "ちゃ" },
        { id: "b", label: "しゃ" },
        { id: "c", label: "ひゃ" },
        { id: "d", label: "じゃ" },
      ],
      correctChoiceId: "b",
      explanationEn: "しゃ is sha (し + small ゃ).",
      explanationJa: "しゃ は sha（し＋小さいゃ）です。",
    },
    {
      id: "jp-youon-speak",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say ちゃ (cha). Tap Continue after you say it.",
      promptJa: "話す：ちゃ（cha）と言ってください。",
      ttsText: "ちゃ",
      ttsLang: "ja-JP",
      explanationEn: "ちゃ is cha. Soft 'ch', one short beat.",
      explanationJa: "ちゃ は cha。短い1拍で。",
    },
    {
      id: "jp-youon-listen",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen: which youon do you hear?",
      promptJa: "聞く：聞こえた拗音は？",
      ttsText: "にゃ",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "ひゃ" },
        { id: "b", label: "みゃ" },
        { id: "c", label: "にゃ" },
        { id: "d", label: "りゃ" },
      ],
      correctChoiceId: "c",
      explanationEn: "You heard にゃ (nya).",
      explanationJa: "にゃ（nya）が聞こえました。",
    },
    {
      id: "jp-youon-read2",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Read: which is 'ja' (voiced youon)?",
      promptJa: "読む：濁音の「ja」はどれ？",
      choices: [
        { id: "a", label: "しゃ" },
        { id: "b", label: "ちゃ" },
        { id: "c", label: "ぎゃ" },
        { id: "d", label: "じゃ" },
      ],
      correctChoiceId: "d",
      explanationEn: "じゃ is ja: じ + small ゃ (voiced).",
      explanationJa: "じゃ は ja（じ＋小さいゃの濁音）です。",
    },
    {
      id: "jp-youon-write2",
      kind: "write-choice",
      skill: "write",
      prompt: "Write: choose りゃ (rya).",
      promptJa: "書く：りゃ（rya）を選ぶ。",
      choices: [
        { id: "a", label: "みゃ" },
        { id: "b", label: "ひゃ" },
        { id: "c", label: "りゃ" },
        { id: "d", label: "びゃ" },
      ],
      correctChoiceId: "c",
      explanationEn: "りゃ is rya (り + small ゃ).",
      explanationJa: "りゃ は rya（り＋小さいゃ）です。",
    },
  ],
};
