import type { LearningUnit } from "@/lib/types";

export const japaneseKanjiNumbersTimeUnit: LearningUnit = {
  id: "jp-kanji-numbers-time",
  pathId: "japanese",
  title: "Kanji: numbers and time",
  titleJa: "漢字：数と時間",
  subtitle: "Read, write, speak, listen: 1 to 10, year, month, day",
  xpReward: 150,
  tutorial: {
    title: "Count and date",
    titleJa: "数える・日付",
    bodyEn:
      "Learn number kanji 一 to 十, then 年 (year), 月 (month), 日 (day). Romaji helpers: 一 ichi, 二 ni, 三 san, 四 yon/shi, 五 go, 六 roku, 七 nana/shichi, 八 hachi, 九 kyuu/ku, 十 juu, 年 nen/toshi, 月 gatsu/tsuki, 日 nichi/hi. Skill order: read, write, speak, listen.",
    bodyJa:
      "数字の漢字 一〜十 と、年・月・日 を学びます。ローマ字の目安：一 ichi、二 ni、三 san、四 yon/shi、五 go、六 roku、七 nana/shichi、八 hachi、九 kyuu/ku、十 juu、年 nen/toshi、月 gatsu/tsuki、日 nichi/hi。順番は読む→書く→話す→聞くです。",
    tips: [
      "四 is often yon in counting, shi in some compounds",
      "七 is often nana when counting aloud",
      "Dates use 月 and 日 after numbers",
    ],
  },
  exercises: [
    {
      id: "jp-knt-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 五 mean?",
      promptJa: "「五」の意味は？",
      choices: [
        { id: "a", label: "A) Four" },
        { id: "b", label: "B) Five" },
        { id: "c", label: "C) Six" },
        { id: "d", label: "D) Ten" },
      ],
      correctChoiceId: "b",
      explanationEn: "五 means five. Reading: ご (go).",
      explanationJa: "五は5。読みは ご（go）。",
    },
    {
      id: "jp-knt-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which character means 'eight'?",
      promptJa: "「八」を書くとどれ？",
      choices: [
        { id: "a", label: "六" },
        { id: "b", label: "七" },
        { id: "c", label: "九" },
        { id: "d", label: "八" },
      ],
      correctChoiceId: "d",
      explanationEn: "八 means eight. Reading: はち (hachi).",
      explanationJa: "八は8。読みは はち（hachi）。",
    },
    {
      id: "jp-knt-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say 十 as じゅう (juu). Tap Continue after you say it.",
      promptJa: "話す：「十」を じゅう（juu）と言ってください。",
      ttsText: "じゅう",
      ttsLang: "ja-JP",
      explanationEn: "十 means ten. Reading: じゅう (juu).",
      explanationJa: "十は10。読みは じゅう（juu）。",
    },
    {
      id: "jp-knt-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which kanji matches the number you hear?",
      promptJa: "聞いて、合う数字の漢字を選ぶ。",
      ttsText: "よん",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "三" },
        { id: "b", label: "四" },
        { id: "c", label: "七" },
        { id: "d", label: "九" },
      ],
      correctChoiceId: "b",
      explanationEn: "よん (yon) is a common reading of 四 (four). Also し (shi).",
      explanationJa: "「よん」（yon）は四のよく使う読み。し（shi）もあります。",
    },
    {
      id: "jp-knt-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 年 mean?",
      promptJa: "「年」の意味は？",
      choices: [
        { id: "a", label: "A) Month" },
        { id: "b", label: "B) Day" },
        { id: "c", label: "C) Year" },
        { id: "d", label: "D) Week" },
      ],
      correctChoiceId: "c",
      explanationEn: "年 means year. Readings: ねん (nen), とし (toshi).",
      explanationJa: "年は年。読みは ねん（nen）、とし（toshi）。",
    },
    {
      id: "jp-knt-6",
      kind: "write-choice",
      skill: "write",
      prompt: "In a date, which kanji marks the day of the month?",
      promptJa: "日付で「日」を書くとどれ？",
      choices: [
        { id: "a", label: "年" },
        { id: "b", label: "月" },
        { id: "c", label: "日" },
        { id: "d", label: "十" },
      ],
      correctChoiceId: "c",
      explanationEn: "日 marks the day (also sun). Readings: にち (nichi), ひ (hi).",
      explanationJa: "日は日（日付・太陽）。読みは にち（nichi）、ひ（hi）。",
    },
  ],
};
