import type { LearningUnit } from "@/lib/types";

export const japaneseKanjiPeopleUnit: LearningUnit = {
  id: "jp-kanji-people",
  pathId: "japanese",
  title: "Kanji: people",
  titleJa: "漢字：人",
  subtitle: "Read and say 人・女・男・子・学・先",
  xpReward: 140,
  tutorial: {
    title: "People kanji you will see on day one",
    titleJa: "初日に見る人の漢字",
    bodyEn:
      "These characters show up on station signs, school gates, and every self-intro. Learn the meaning, a main reading, then speak a word — not only the isolated kanji.",
    bodyJa:
      "駅・学校・自己紹介に出ます。意味と代表読みを覚え、単語で話します。",
    tips: [
      "人 is ひと alone and じん in 日本人",
      "先生 is せんせい — two kanji, one word",
      "子 often reads こ",
    ],
  },
  teach: [
    {
      glyph: "人",
      reading: "hito / jin",
      tipEn: "Person. Walking legs.",
      tipJa: "人。歩いている足。",
      ttsText: "ひと",
      ttsLang: "ja-JP",
      meaningEn: "person",
      meaningJa: "ひと",
    },
    {
      glyph: "女",
      reading: "onna / jo",
      tipEn: "Woman. Kneeling figure.",
      tipJa: "女。すわる人の形。",
      ttsText: "おんな",
      ttsLang: "ja-JP",
      meaningEn: "woman",
      meaningJa: "おんな",
    },
    {
      glyph: "男",
      reading: "otoko / dan",
      tipEn: "Man. Field + power.",
      tipJa: "男。田＋力。",
      ttsText: "おとこ",
      ttsLang: "ja-JP",
      meaningEn: "man",
      meaningJa: "おとこ",
    },
    {
      glyph: "子",
      reading: "ko / shi",
      tipEn: "Child.",
      tipJa: "子。こども。",
      ttsText: "こ",
      ttsLang: "ja-JP",
      meaningEn: "child",
      meaningJa: "こ",
    },
    {
      glyph: "学",
      reading: "gaku / mana(bu)",
      tipEn: "Study / learn. In 学生 and 学校.",
      tipJa: "学。学生・学校。",
      ttsText: "がく",
      ttsLang: "ja-JP",
      meaningEn: "study",
      meaningJa: "がく",
    },
    {
      glyph: "先",
      reading: "saki / sen",
      tipEn: "Ahead / previous. First kanji of 先生.",
      tipJa: "先。先生の最初。",
      ttsText: "せん",
      ttsLang: "ja-JP",
      meaningEn: "ahead / previous",
      meaningJa: "さき／せん",
    },
  ],
  exercises: [
    {
      id: "jp-kp-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 学生 mean?",
      promptJa: "「学生」の意味は？",
      choices: [
        { id: "a", label: "Teacher" },
        { id: "b", label: "Student" },
        { id: "c", label: "Child" },
        { id: "d", label: "School only" },
      ],
      correctChoiceId: "b",
      explanationEn: "学生 is がくせい, student.",
      explanationJa: "学生はがくせい。",
    },
    {
      id: "jp-kp-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which kanji is 'woman'?",
      promptJa: "「女」はどれ？",
      choices: [
        { id: "a", label: "男" },
        { id: "b", label: "子" },
        { id: "c", label: "女" },
        { id: "d", label: "先" },
      ],
      correctChoiceId: "c",
      strokeGlyph: "女",
      explanationEn: "女 is woman (おんな / ジョ).",
      explanationJa: "女はおんな。",
    },
    {
      id: "jp-kp-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say 先生 (せんせい).",
      promptJa: "先生と言ってください。",
      ttsText: "せんせい",
      ttsLang: "ja-JP",
      expectedSpeech: ["せんせい", "先生", "sensei"],
      explanationEn: "先生 is teacher. Two kanji, one word.",
      explanationJa: "先生はせんせい。",
    },
    {
      id: "jp-kp-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word did you hear?",
      promptJa: "聞こえた単語は？",
      ttsText: "こども",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "先生" },
        { id: "b", label: "子ども" },
        { id: "c", label: "男" },
        { id: "d", label: "人" },
      ],
      correctChoiceId: "b",
      explanationEn: "こども uses 子.",
      explanationJa: "こどもは子が入ります。",
    },
    {
      id: "jp-kp-5",
      kind: "match",
      skill: "read",
      prompt: "Match kanji words to English.",
      promptJa: "漢字語と英語を結ぶ。",
      pairs: [
        { id: "a", left: "人", right: "person" },
        { id: "b", left: "男", right: "man" },
        { id: "c", left: "学", right: "study" },
        { id: "d", left: "先", right: "ahead" },
      ],
      explanationEn: "Read the character, then the English meaning.",
      explanationJa: "漢字を見てから英語の意味へ。",
    },
  ],
};
