import { kanjiRecallExercises } from "@/content/japanese/kanji-factory";
import type { LearningUnit } from "@/lib/types";

export const japaneseKanjiPeopleUnit: LearningUnit = {
  id: "jp-kanji-people",
  pathId: "japanese",
  title: "Kanji: people",
  titleJa: "漢字：人",
  subtitle: "Read and say 人・女・男・子・学・先",
  xpReward: 140,
  tutorial: {
    title: "People kanji you will see on day one",
    titleJa: "初日に見る人の漢字",
    bodyEn:
      "These characters show up on station signs, school gates, and every self-intro. Learn the meaning, a main reading, then speak a word — not only the isolated kanji.",
    bodyJa:
      "駅・学校・自己紹介に出ます。意味と代表読みを覚え、単語で話します。",
    tips: [
      "人 is ひと alone and じん in 日本人",
      "先生 is せんせい — two kanji, one word",
      "子 often reads こ",
    ],
  },
  teach: [
    {
      glyph: "人",
      reading: "hito / jin",
      tipEn: "Person. Walking legs.",
      tipJa: "人。歩いている足。",
      ttsText: "ひと",
      ttsLang: "ja-JP",
      meaningEn: "person",
      meaningJa: "ひと",
    },
    {
      glyph: "女",
      reading: "onna / jo",
      tipEn: "Woman. Kneeling figure.",
      tipJa: "女。すわる人の形。",
      ttsText: "おんな",
      ttsLang: "ja-JP",
      meaningEn: "woman",
      meaningJa: "おんな",
    },
    {
      glyph: "男",
      reading: "otoko / dan",
      tipEn: "Man. Field + power.",
      tipJa: "男。田＋力。",
      ttsText: "おとこ",
      ttsLang: "ja-JP",
      meaningEn: "man",
      meaningJa: "おとこ",
    },
    {
      glyph: "子",
      reading: "ko / shi",
      tipEn: "Child.",
      tipJa: "子。こども。",
      ttsText: "こ",
      ttsLang: "ja-JP",
      meaningEn: "child",
      meaningJa: "こ",
    },
    {
      glyph: "学",
      reading: "gaku / mana(bu)",
      tipEn: "Study / learn. In 学生 and 学校.",
      tipJa: "学。学生・学校。",
      ttsText: "がく",
      ttsLang: "ja-JP",
      meaningEn: "study",
      meaningJa: "がく",
    },
    {
      glyph: "先",
      reading: "saki / sen",
      tipEn: "Ahead / previous. First kanji of 先生.",
      tipJa: "先。先生の最初。",
      ttsText: "せん",
      ttsLang: "ja-JP",
      meaningEn: "ahead / previous",
      meaningJa: "さき／せん",
    },
  ],
  exercises: kanjiRecallExercises("jp-kp", ["人", "女", "男", "子", "学", "先"]),
};
