import type { LearningUnit } from "@/lib/types";

export const japaneseKanjiBasicsUnit: LearningUnit = {
  id: "jp-kanji-basics",
  pathId: "japanese",
  title: "Kanji basics",
  titleJa: "漢字入門",
  subtitle: "Read, write, speak, and listen to first everyday kanji",
  xpReward: 140,
  tutorial: {
    title: "What is kanji?",
    titleJa: "漢字とは",
    bodyEn:
      "Kanji are characters that carry meaning. Japanese writing mixes hiragana, katakana, and kanji. We learn each new kanji in order: read it, write (choose) it, say it, then hear it. Start with high-frequency beginners: 一, 二, 三, 人, 日.",
    bodyJa:
      "漢字は意味を持つ文字です。日本語はひらがな・カタカナ・漢字を混ぜて書きます。新しい漢字は読む→書く→話す→聞くの順で学びます。まずは 一・二・三・人・日 から。",
    tips: [
      "One kanji can have more than one reading (on/kun)",
      "Count strokes when you study writing",
      "Learn words, not only isolated characters",
    ],
  },
  exercises: [
    {
      id: "jp-kj-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 人 mean?",
      promptJa: "「人」の意味は？",
      choices: [
        { id: "a", label: "A) Day / sun" },
        { id: "b", label: "B) Person" },
        { id: "c", label: "C) Water" },
        { id: "d", label: "D) Tree" },
      ],
      correctChoiceId: "b",
      explanationEn: "人 means person (readings include ひと and ジン/ニン).",
      explanationJa: "人は「ひと」や音読みのジン／ニンで、人を表します。",
    },
    {
      id: "jp-kj-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which character do you write for 'three'?",
      promptJa: "「三」を書くとどれ？",
      choices: [
        { id: "a", label: "二" },
        { id: "b", label: "一" },
        { id: "c", label: "三" },
        { id: "d", label: "十" },
      ],
      correctChoiceId: "c",
      explanationEn: "三 is three horizontal strokes for 'three'.",
      explanationJa: "三は横線3本で「さん／みっ」を表します。",
    },
    {
      id: "jp-kj-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say 日 (read as ひ or ニチ). Tap Continue after you say it.",
      promptJa: "「日」を声に出して言ってください。",
      ttsText: "ひ",
      ttsLang: "ja-JP",
      explanationEn: "日 can be ひ (day/sun) or ニチ/ジツ in compounds.",
      explanationJa: "日は訓読みで「ひ」、音読みでニチ／ジツなどがあります。",
    },
    {
      id: "jp-kj-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which kanji matches the word you hear?",
      promptJa: "聞いて、合う漢字を選ぶ。",
      ttsText: "ひと",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "日" },
        { id: "b", label: "人" },
        { id: "c", label: "一" },
        { id: "d", label: "二" },
      ],
      correctChoiceId: "b",
      explanationEn: "ひと is a common reading of 人.",
      explanationJa: "「ひと」は人の訓読みです。",
    },
    {
      id: "jp-kj-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which kanji means 'one'?",
      promptJa: "「一」の漢字はどれ？",
      choices: [
        { id: "a", label: "三" },
        { id: "b", label: "二" },
        { id: "c", label: "一" },
        { id: "d", label: "人" },
      ],
      correctChoiceId: "c",
      explanationEn: "一 is a single horizontal stroke meaning one.",
      explanationJa: "一は横線1本で「いち」を表します。",
    },
  ],
};
