import type { LearningUnit } from "@/lib/types";

export const japaneseKanjiNatureUnit: LearningUnit = {
  id: "jp-kanji-nature",
  pathId: "japanese",
  title: "Kanji: nature",
  titleJa: "漢字：自然",
  subtitle: "Read, write, speak, listen: mountain, river, tree, water, fire, sun, moon",
  xpReward: 140,
  tutorial: {
    title: "Nature kanji",
    titleJa: "自然の漢字",
    bodyEn:
      "These kanji name things you see outdoors. Learn meaning first, then a common reading with romaji: 山 yama (mountain), 川 kawa (river), 木 ki (tree), 水 mizu (water), 火 hi (fire), 日 hi / nichi (sun or day), 月 tsuki / getsu (moon or month). Order: read, write, speak, listen.",
    bodyJa:
      "外で見るものを表す漢字です。意味のあと、よく使う読みとローマ字：山 yama、川 kawa、木 ki、水 mizu、火 hi、日 hi / nichi、月 tsuki / getsu。順番は読む→書く→話す→聞くです。",
    tips: [
      "Picture the shape: 山 looks like peaks",
      "水 and 川 both relate to water",
      "日 and 月 appear in dates too",
    ],
  },
  exercises: [
    {
      id: "jp-kn-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 山 mean?",
      promptJa: "「山」の意味は？",
      choices: [
        { id: "a", label: "A) River" },
        { id: "b", label: "B) Mountain" },
        { id: "c", label: "C) Tree" },
        { id: "d", label: "D) Fire" },
      ],
      correctChoiceId: "b",
      explanationEn: "山 means mountain. Common reading: やま (yama); on-yomi サン (san).",
      explanationJa: "山は山。訓読み やま（yama）、音読み サン（san）。",
    },
    {
      id: "jp-kn-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which character means 'river'?",
      promptJa: "「川」を書くとどれ？",
      choices: [
        { id: "a", label: "水" },
        { id: "b", label: "木" },
        { id: "c", label: "川" },
        { id: "d", label: "火" },
      ],
      correctChoiceId: "c",
      explanationEn: "川 means river. Reading: かわ (kawa); on-yomi セン (sen).",
      explanationJa: "川は川。訓読み かわ（kawa）、音読み セン（sen）。",
    },
    {
      id: "jp-kn-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Speak: say 水 as みず (mizu). Tap Continue after you say it.",
      promptJa: "話す：「水」を みず（mizu）と言ってください。",
      ttsText: "みず",
      ttsLang: "ja-JP",
      explanationEn: "水 means water. Kun: みず (mizu); on: スイ (sui).",
      explanationJa: "水は水。訓読み みず（mizu）、音読み スイ（sui）。",
    },
    {
      id: "jp-kn-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which kanji matches the word you hear?",
      promptJa: "聞いて、合う漢字を選ぶ。",
      ttsText: "き",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "火" },
        { id: "b", label: "木" },
        { id: "c", label: "月" },
        { id: "d", label: "日" },
      ],
      correctChoiceId: "b",
      explanationEn: "き (ki) is a common reading of 木 (tree / wood). On-yomi: モク (moku).",
      explanationJa: "「き」（ki）は木の訓読み。音読みは モク（moku）。",
    },
    {
      id: "jp-kn-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which kanji means 'fire'?",
      promptJa: "「火」の漢字はどれ？",
      choices: [
        { id: "a", label: "水" },
        { id: "b", label: "日" },
        { id: "c", label: "火" },
        { id: "d", label: "月" },
      ],
      correctChoiceId: "c",
      explanationEn: "火 means fire. Reading: ひ (hi); on-yomi カ (ka).",
      explanationJa: "火は火。訓読み ひ（hi）、音読み カ（ka）。",
    },
    {
      id: "jp-kn-6",
      kind: "write-choice",
      skill: "write",
      prompt: "Which character is used for 'moon' (also 'month')?",
      promptJa: "「月」を書くとどれ？",
      choices: [
        { id: "a", label: "日" },
        { id: "b", label: "月" },
        { id: "c", label: "山" },
        { id: "d", label: "川" },
      ],
      correctChoiceId: "b",
      explanationEn: "月 means moon or month. Readings: つき (tsuki), ゲツ/ガツ (getsu/gatsu).",
      explanationJa: "月は月・月（カレンダー）。訓読み つき（tsuki）、音読み ゲツ／ガツ。",
    },
  ],
};
