import type { LearningUnit } from "@/lib/types";

/** Teach アイウエオ before katakana line quizzes. */
export const japaneseKatakanaBridgeUnit: LearningUnit = {
  id: "jp-before-katakana",
  pathId: "japanese",
  title: "Learn アイウエオ",
  titleJa: "アイウエオを覚える",
  subtitle: "Your first katakana alphabet: study each letter, then a tiny check",
  xpReward: 110,
  tutorial: {
    title: "Katakana is a second alphabet",
    titleJa: "カタカナはもう一つの五十音",
    bodyEn:
      "Same sounds as hiragana, different shapes. ア イ ウ エ オ = a i u e o. Learn each letter with Listen first, then a short check. Used a lot for loanwords like コーヒー.",
    bodyJa:
      "音はひらがなと同じで、形が違います。アイウエオ＝a i u e o。先に Listen で1字ずつ覚えてから短い確認へ。コーヒーなどの外来語によく使います。",
    tips: [
      "Compare each letter to the hiragana you already know",
      "Katakana looks more angular",
      "Listen before you quiz",
    ],
  },
  teach: [
    {
      glyph: "ア",
      reading: "a",
      tipEn: "ア = a. Angular version of あ.",
      tipJa: "ア＝a。あのカタカナ版。",
      ttsText: "ア",
      ttsLang: "ja-JP",
    },
    {
      glyph: "イ",
      reading: "i",
      tipEn: "イ = i.",
      tipJa: "イ＝i。",
      ttsText: "イ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "ウ",
      reading: "u",
      tipEn: "ウ = u.",
      tipJa: "ウ＝u。",
      ttsText: "ウ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "エ",
      reading: "e",
      tipEn: "エ = e.",
      tipJa: "エ＝e。",
      ttsText: "エ",
      ttsLang: "ja-JP",
    },
    {
      glyph: "オ",
      reading: "o",
      tipEn: "オ = o.",
      tipJa: "オ＝o。",
      ttsText: "オ",
      ttsLang: "ja-JP",
    },
  ],
  exercises: [
    {
      id: "jp-kb-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which katakana is a?",
      promptJa: "a のカタカナは？",
      choices: [
        { id: "a", label: "イ" },
        { id: "b", label: "ア" },
        { id: "c", label: "ウ" },
        { id: "d", label: "エ" },
      ],
      correctChoiceId: "b",
      explanationEn: "ア = a.",
      explanationJa: "ア＝a。",
    },
    {
      id: "jp-kb-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick katakana i.",
      promptJa: "i のカタカナを選ぶ。",
      choices: [
        { id: "a", label: "ウ" },
        { id: "b", label: "オ" },
        { id: "c", label: "イ" },
        { id: "d", label: "ア" },
      ],
      correctChoiceId: "c",
      explanationEn: "イ = i.",
      explanationJa: "イ＝i。",
    },
    {
      id: "jp-kb-3",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen and choose the letter.",
      promptJa: "聞いて文字を選ぶ。",
      ttsText: "エ",
      ttsLang: "ja-JP",
      choices: [
        { id: "a", label: "ア" },
        { id: "b", label: "オ" },
        { id: "c", label: "ウ" },
        { id: "d", label: "エ" },
      ],
      correctChoiceId: "d",
      explanationEn: "You heard エ (e).",
      explanationJa: "エ（e）でした。",
    },
    {
      id: "jp-kb-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say アイウエオ aloud.",
      promptJa: "アイウエオ を声に出して。",
      ttsText: "アイウエオ",
      ttsLang: "ja-JP",
      explanationEn: "Same vowels as hiragana, sharper shapes.",
      explanationJa: "ひらがなと同じ母音、角ばった形です。",
    },
    {
      id: "jp-kb-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Coffee is usually written with which script?",
      promptJa: "コーヒーは主にどの文字？",
      choices: [
        { id: "a", label: "A) Katakana" },
        { id: "b", label: "B) Only hiragana" },
        { id: "c", label: "C) Only kanji" },
        { id: "d", label: "D) Only A B C" },
      ],
      correctChoiceId: "a",
      explanationEn: "Loanwords like coffee use katakana: コーヒー.",
      explanationJa: "外来語はカタカナ（コーヒー）が多いです。",
    },
  ],
};
