import { createSentenceUnit } from "@/content/japanese/sentence-factory";

export const japaneseSentenceFirstUnit = createSentenceUnit({
  id: "jp-sentence-first",
  title: "Build first sentences",
  titleJa: "はじめての文づくり",
  subtitle: "Move hiragana tiles into SOV order: who → what → verb",
  tutorialTitle: "Japanese sentences are built, not guessed",
  tutorialTitleJa: "日本語の文は組み立てる",
  bodyEn:
    "English is SVO: I eat bread. Japanese is SOV: わたしは パンを たべます. You will tap colored tiles into the tray. Hiragana is the grammar glue. Read each tile, then place it. This is how real reading starts — seeing order, not picking A/B/C.",
  bodyJa:
    "英語はSVO、日本語はSOV：わたしは パンを たべます。色つきタイルをトレイへ。ひらがなは文法の接着剤。読んでから置く。読む力はここから。",
  tips: [
    "は marks the topic (said wa)",
    "を marks the object (said o)",
    "The verb almost always comes last",
  ],
  teach: [
    {
      glyph: "SOV",
      reading: "who → what → do",
      tipEn: "Topic は, object を, then the ます verb.",
      tipJa: "主題は、目的語を、それからます動詞。",
      ttsText: "わたしはみずをのみます",
      ttsLang: "ja-JP",
      meaningEn: "I drink water",
      meaningJa: "水を飲みます",
    },
  ],
  items: [
    {
      id: "sf-1",
      promptEn: "Build: I drink water.",
      promptJa: "「水を飲みます」を組み立てる。",
      ttsText: "わたしはみずをのみます",
      tiles: [
        { id: "watashi", label: "わたし", script: "hiragana", reading: "watashi" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "mizu", label: "みず", script: "hiragana", reading: "mizu" },
        { id: "o", label: "を", script: "particle", reading: "o" },
        { id: "nomu", label: "のみます", script: "hiragana", reading: "nomimasu" },
      ],
      extra: [{ id: "taberu", label: "たべます", script: "hiragana", reading: "tabemasu" }],
      order: ["watashi", "wa", "mizu", "o", "nomu"],
      explainEn: "わたしは みずを のみます. Verb last. を marks water.",
      explainJa: "わたしは みずを のみます。動詞は最後。",
    },
    {
      id: "sf-2",
      promptEn: "Build: I eat bread.",
      promptJa: "「パンを食べます」を組み立てる。",
      ttsText: "わたしはパンをたべます",
      tiles: [
        { id: "watashi", label: "わたし", script: "hiragana" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "pan", label: "パン", script: "katakana", reading: "pan" },
        { id: "o", label: "を", script: "particle", reading: "o" },
        { id: "taberu", label: "たべます", script: "hiragana" },
      ],
      extra: [{ id: "nomu", label: "のみます", script: "hiragana" }],
      order: ["watashi", "wa", "pan", "o", "taberu"],
      explainEn: "パン is katakana (loanword). Same SOV frame.",
      explainJa: "パンはカタカナ。型は同じSOV。",
    },
    {
      id: "sf-3",
      promptEn: "Build: Lumi goes to school.",
      promptJa: "「ルミは学校に行きます」を組み立てる。",
      ttsText: "ルミはがっこうにいきます",
      tiles: [
        { id: "lumi", label: "ルミ", script: "katakana", reading: "rumi" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "gakkou", label: "がっこう", script: "hiragana", reading: "gakkou" },
        { id: "ni", label: "に", script: "particle", reading: "ni" },
        { id: "iku", label: "いきます", script: "hiragana" },
      ],
      extra: [{ id: "o", label: "を", script: "particle", reading: "o" }],
      order: ["lumi", "wa", "gakkou", "ni", "iku"],
      explainEn: "に marks destination with いきます. Do not use を here.",
      explainJa: "行き先はに。をではない。",
    },
    {
      id: "sf-4",
      promptEn: "Build: This is coffee.",
      promptJa: "「これはコーヒーです」を組み立てる。",
      ttsText: "これはコーヒーです",
      tiles: [
        { id: "kore", label: "これ", script: "hiragana" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "coffee", label: "コーヒー", script: "katakana", reading: "koohii" },
        { id: "desu", label: "です", script: "hiragana" },
      ],
      extra: [{ id: "o", label: "を", script: "particle" }],
      order: ["kore", "wa", "coffee", "desu"],
      explainEn: "X は Y です is the core identity pattern.",
      explainJa: "XはYです が基本。",
    },
    {
      id: "sf-5",
      promptEn: "Build: The cat is here.",
      promptJa: "「ねこがいます」を組み立てる。",
      ttsText: "ねこがいます",
      tiles: [
        { id: "neko", label: "ねこ", script: "hiragana" },
        { id: "ga", label: "が", script: "particle", reading: "ga" },
        { id: "iru", label: "います", script: "hiragana" },
      ],
      extra: [
        { id: "aru", label: "あります", script: "hiragana" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
      ],
      order: ["neko", "ga", "iru"],
      explainEn: "います is for living things. が often marks the new subject.",
      explainJa: "いますは生き物。がは新しい主語。",
    },
  ],
});
