import { createSentenceUnit } from "@/content/japanese/sentence-factory";

export const japaneseProEmailUnit = createSentenceUnit({
  id: "jp-pro-email",
  title: "Read a work email",
  titleJa: "仕事のメールを読む",
  subtitle: "Build the lines of a polite office message",
  tutorialTitle: "Professional Japanese is polite SOV plus set phrases",
  tutorialTitleJa: "ビジネスは丁寧なSOV＋定型",
  bodyEn:
    "Office mail recycles frames: お世話になっております, 会議は3時です, 添付ファイルをご確認ください. You will assemble those frames from kanji tiles so you can read a real inbox, not a word list.",
  bodyJa:
    "社内メールは型の再利用。タイルで組み立てて、単語帳ではなく受信箱を読めるようにします。",
  tips: [
    "ご確認ください is a soft command",
    "にて is formal で",
    "Keep です／ます in first-job Japanese",
  ],
  teach: [
    {
      glyph: "ご確認ください",
      reading: "gokakunin kudasai",
      tipEn: "Please confirm / please check. Inbox Japanese.",
      tipJa: "確認してほしいときの定型。",
      ttsText: "ごかくにんください",
      ttsLang: "ja-JP",
    },
  ],
  items: [
    {
      id: "em-1",
      promptEn: "Build: Thank you for your continued support.",
      promptJa: "お世話になっております。",
      ttsText: "おせわになっております",
      tiles: [
        { id: "osewa", label: "お世話", script: "kanji", reading: "おせわ" },
        { id: "ni", label: "に", script: "particle" },
        { id: "natte", label: "なって", script: "hiragana" },
        { id: "orimasu", label: "おります", script: "hiragana" },
      ],
      extra: [{ id: "desu", label: "です", script: "hiragana" }],
      order: ["osewa", "ni", "natte", "orimasu"],
      explainEn: "Opening line of almost every business email.",
      explainJa: "ビジネスメールの書き出し。",
    },
    {
      id: "em-2",
      promptEn: "Build: The meeting is at 3 o'clock.",
      promptJa: "会議は3時です。",
      ttsText: "かいぎはさんじです",
      tiles: [
        { id: "kaigi", label: "会議", script: "kanji", reading: "かいぎ" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "sanji", label: "3時", script: "kanji", reading: "さんじ" },
        { id: "desu", label: "です", script: "hiragana" },
      ],
      extra: [{ id: "ni", label: "に", script: "particle" }],
      order: ["kaigi", "wa", "sanji", "desu"],
      explainEn: "X は time です. Clock times often skip に in this frame.",
      explainJa: "会議は3時です。",
    },
    {
      id: "em-3",
      promptEn: "Build: Please check the attached file.",
      promptJa: "添付ファイルをご確認ください。",
      ttsText: "てんぷファイルをごかくにんください",
      tiles: [
        { id: "tenpu", label: "添付", script: "kanji", reading: "てんぷ" },
        { id: "file", label: "ファイル", script: "katakana" },
        { id: "o", label: "を", script: "particle" },
        { id: "go", label: "ご", script: "hiragana" },
        { id: "kakunin", label: "確認", script: "kanji", reading: "かくにん" },
        { id: "kudasai", label: "ください", script: "hiragana" },
      ],
      extra: [{ id: "wa", label: "は", script: "particle" }],
      order: ["tenpu", "file", "o", "go", "kakunin", "kudasai"],
      explainEn: "ご + verbal noun + ください = polite request.",
      explainJa: "ご確認ください が丁寧な依頼。",
    },
    {
      id: "em-4",
      promptEn: "Build: I will send it later.",
      promptJa: "後で送ります。",
      ttsText: "あとでおくります",
      tiles: [
        { id: "ato", label: "後で", script: "kanji", reading: "あとで" },
        { id: "okuru", label: "送ります", script: "kanji", reading: "おくります" },
      ],
      extra: [{ id: "kimasu", label: "来ます", script: "kanji", reading: "きます" }],
      order: ["ato", "okuru"],
      explainEn: "Time + verb. 送ります is send.",
      explainJa: "後で送ります。",
    },
    {
      id: "em-5",
      promptEn: "Build: Best regards (closing).",
      promptJa: "よろしくお願いいたします。",
      ttsText: "よろしくおねがいいたします",
      tiles: [
        { id: "yoroshiku", label: "よろしく", script: "hiragana" },
        { id: "onegai", label: "お願い", script: "kanji", reading: "おねがい" },
        { id: "itashimasu", label: "いたします", script: "hiragana" },
      ],
      extra: [{ id: "shimasu", label: "します", script: "hiragana" }],
      order: ["yoroshiku", "onegai", "itashimasu"],
      explainEn: "いたします is humbler than します. Standard close.",
      explainJa: "いたしますのほうが謙譲。",
    },
  ],
});

export const japaneseProNewsUnit = createSentenceUnit({
  id: "jp-pro-news",
  title: "Read a news headline",
  titleJa: "ニュースの見出し",
  subtitle: "Headlines drop particles — you still rebuild the full sentence",
  tutorialTitle: "News Japanese is compressed",
  tutorialTitleJa: "ニュースは省略される",
  bodyEn:
    "A headline may say 円高、輸出に影響. Your job is to expand it into a readable sentence with particles and a verb. That is professional reading: recover the grammar the page hid.",
  bodyJa:
    "見出しは助詞を落とす。あなたは助詞と動詞を戻して読める文にする。それがプロの読解。",
  tips: [
    "Headlines often omit です／ます",
    "、 can replace は",
    "Rebuild the polite sentence first",
  ],
  teach: [
    {
      glyph: "影響",
      reading: "eikyou",
      tipEn: "Influence / impact. High-frequency news kanji.",
      tipJa: "ニュース頻出。",
      ttsText: "えいきょう",
      ttsLang: "ja-JP",
    },
  ],
  items: [
    {
      id: "nw-1",
      promptEn: "Expand the headline: Yen rise affects exports.",
      promptJa: "円高は輸出に影響します。",
      ttsText: "えんだかはゆしゅつにえいきょうします",
      tiles: [
        { id: "endaka", label: "円高", script: "kanji", reading: "えんだか" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "yushutsu", label: "輸出", script: "kanji", reading: "ゆしゅつ" },
        { id: "ni", label: "に", script: "particle" },
        { id: "eikyou", label: "影響", script: "kanji", reading: "えいきょう" },
        { id: "shimasu", label: "します", script: "hiragana" },
      ],
      extra: [{ id: "o", label: "を", script: "particle" }],
      order: ["endaka", "wa", "yushutsu", "ni", "eikyou", "shimasu"],
      explainEn: "X は Y に影響します = X affects Y.",
      explainJa: "XはYに影響します。",
    },
    {
      id: "nw-2",
      promptEn: "Build: The company announced a new product.",
      promptJa: "会社は新製品を発表しました。",
      ttsText: "かいしゃはしんせいひんをはっぴょうしました",
      tiles: [
        { id: "kaisha", label: "会社", script: "kanji", reading: "かいしゃ" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "shin", label: "新製品", script: "kanji", reading: "しんせいひん" },
        { id: "o", label: "を", script: "particle" },
        { id: "happyou", label: "発表しました", script: "kanji", reading: "はっぴょうしました" },
      ],
      extra: [{ id: "ni", label: "に", script: "particle" }],
      order: ["kaisha", "wa", "shin", "o", "happyou"],
      explainEn: "発表する takes を for the thing announced.",
      explainJa: "発表はを。",
    },
    {
      id: "nw-3",
      promptEn: "Build: Tomorrow's meeting was canceled.",
      promptJa: "明日の会議は中止になりました。",
      ttsText: "あしたのかいぎはちゅうしになりました",
      tiles: [
        { id: "ashita", label: "明日", script: "kanji", reading: "あした" },
        { id: "no", label: "の", script: "particle" },
        { id: "kaigi", label: "会議", script: "kanji", reading: "かいぎ" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "chushi", label: "中止", script: "kanji", reading: "ちゅうし" },
        { id: "ninatta", label: "になりました", script: "hiragana" },
      ],
      extra: [{ id: "desu", label: "です", script: "hiragana" }],
      order: ["ashita", "no", "kaigi", "wa", "chushi", "ninatta"],
      explainEn: "になりました reports a change of state.",
      explainJa: "になりましたは変化。",
    },
    {
      id: "nw-4",
      promptEn: "Build: Prices are rising.",
      promptJa: "物価が上がっています。",
      ttsText: "ぶっかがあがっています",
      tiles: [
        { id: "bukka", label: "物価", script: "kanji", reading: "ぶっか" },
        { id: "ga", label: "が", script: "particle" },
        { id: "agatte", label: "上がっています", script: "kanji", reading: "あがっています" },
      ],
      extra: [{ id: "wa", label: "は", script: "particle" }],
      order: ["bukka", "ga", "agatte"],
      explainEn: "〜ています = ongoing change.",
      explainJa: "上がっています＝進行。",
    },
  ],
});

export const japaneseProMeetingUnit = createSentenceUnit({
  id: "jp-pro-meeting",
  title: "Read a meeting line",
  titleJa: "会議の一言",
  subtitle: "Assemble the phrases you will see on slides and minutes",
  tutorialTitle: "Meetings run on a small set of readable frames",
  tutorialTitleJa: "会議は少ない型で回る",
  bodyEn:
    "If you can rebuild 資料をご覧ください, 質問はありますか, and 次の議題に移ります, you can follow a Japanese meeting. Tile order trains your eyes to land on ご覧, 議題, 資料 — the kanji that carry the room.",
  bodyJa:
    "資料をご覧ください、質問はありますか、次の議題に移ります。漢字に目を落とす訓練です。",
  tips: [
    "ご覧ください = please look",
    "議題 is agenda item",
    "移ります = we move on",
  ],
  teach: [
    {
      glyph: "議題",
      reading: "gidai",
      tipEn: "Agenda item. Scan for this on every slide.",
      tipJa: "スライドで探す語。",
      ttsText: "ぎだい",
      ttsLang: "ja-JP",
    },
  ],
  items: [
    {
      id: "mt-1",
      promptEn: "Build: Please look at the materials.",
      promptJa: "資料をご覧ください。",
      ttsText: "しりょうをごらんください",
      tiles: [
        { id: "shiryou", label: "資料", script: "kanji", reading: "しりょう" },
        { id: "o", label: "を", script: "particle" },
        { id: "goran", label: "ご覧", script: "kanji", reading: "ごらん" },
        { id: "kudasai", label: "ください", script: "hiragana" },
      ],
      extra: [{ id: "kakunin", label: "確認", script: "kanji" }],
      order: ["shiryou", "o", "goran", "kudasai"],
      explainEn: "ご覧ください is the meeting version of 'please look'.",
      explainJa: "ご覧ください＝見てください。",
    },
    {
      id: "mt-2",
      promptEn: "Build: Are there any questions?",
      promptJa: "質問はありますか。",
      ttsText: "しつもんはありますか",
      tiles: [
        { id: "shitsumon", label: "質問", script: "kanji", reading: "しつもん" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "arimasu", label: "あります", script: "hiragana" },
        { id: "ka", label: "か", script: "particle" },
      ],
      extra: [{ id: "imasu", label: "います", script: "hiragana" }],
      order: ["shitsumon", "wa", "arimasu", "ka"],
      explainEn: "ありますか for things that exist, including questions.",
      explainJa: "質問はありますか。",
    },
    {
      id: "mt-3",
      promptEn: "Build: We will move to the next agenda item.",
      promptJa: "次の議題に移ります。",
      ttsText: "つぎのぎだいにうつります",
      tiles: [
        { id: "tsugi", label: "次", script: "kanji", reading: "つぎ" },
        { id: "no", label: "の", script: "particle" },
        { id: "gidai", label: "議題", script: "kanji", reading: "ぎだい" },
        { id: "ni", label: "に", script: "particle" },
        { id: "utsuru", label: "移ります", script: "kanji", reading: "うつります" },
      ],
      extra: [{ id: "o", label: "を", script: "particle" }],
      order: ["tsugi", "no", "gidai", "ni", "utsuru"],
      explainEn: "に marks the destination of 移ります.",
      explainJa: "移る先はに。",
    },
    {
      id: "mt-4",
      promptEn: "Build: I agree with that opinion.",
      promptJa: "その意見に賛成です。",
      ttsText: "そのいけんにさんせいです",
      tiles: [
        { id: "sono", label: "その", script: "hiragana" },
        { id: "iken", label: "意見", script: "kanji", reading: "いけん" },
        { id: "ni", label: "に", script: "particle" },
        { id: "sansei", label: "賛成", script: "kanji", reading: "さんせい" },
        { id: "desu", label: "です", script: "hiragana" },
      ],
      extra: [{ id: "hantai", label: "反対", script: "kanji", reading: "はんたい" }],
      order: ["sono", "iken", "ni", "sansei", "desu"],
      explainEn: "賛成／反対 take に for the thing you agree with.",
      explainJa: "賛成はに。",
    },
  ],
});
