import { createSentenceUnit } from "@/content/japanese/sentence-factory";

export const japaneseSentenceMixUnit = createSentenceUnit({
  id: "jp-sentence-mix",
  title: "Mix the three scripts",
  titleJa: "3つの文字を混ぜる",
  subtitle: "Real Japanese mixes 漢字, ひらがな, and カタカナ in one line",
  tutorialTitle: "Professionals read mixed script without thinking",
  tutorialTitleJa: "混ざった文字を無意識に読む",
  bodyEn:
    "A workplace line looks like 私は東京でコーヒーを飲みます. Kanji carry meaning, hiragana carries grammar, katakana marks loans. Build each sentence by script color so your eyes learn the jobs of each writing system.",
  bodyJa:
    "職場の文は 私は東京でコーヒーを飲みます。漢字は意味、ひらがなは文法、カタカナは外来語。色で役割を目に覚えさせます。",
  tips: [
    "Kanji = meaning islands",
    "Hiragana = endings and particles",
    "Katakana = foreign / emphasized words",
  ],
  teach: [
    {
      glyph: "私／コーヒー／を",
      reading: "kanji + kata + hira",
      tipEn: "One sentence, three scripts. That is adult Japanese.",
      tipJa: "一文に三種類。それが本物。",
      ttsText: "わたしはコーヒーをのみます",
      ttsLang: "ja-JP",
    },
  ],
  items: [
    {
      id: "sm-1",
      promptEn: "Build: I drink coffee in Tokyo.",
      promptJa: "東京でコーヒーを飲む文。",
      ttsText: "わたしはとうきょうでコーヒーをのみます",
      tiles: [
        { id: "watashi", label: "私", script: "kanji", reading: "わたし" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "tokyo", label: "東京", script: "kanji", reading: "とうきょう" },
        { id: "de", label: "で", script: "particle", reading: "de" },
        { id: "coffee", label: "コーヒー", script: "katakana" },
        { id: "o", label: "を", script: "particle", reading: "o" },
        { id: "nomu", label: "飲みます", script: "kanji", reading: "のみます" },
      ],
      extra: [{ id: "ni", label: "に", script: "particle" }],
      order: ["watashi", "wa", "tokyo", "de", "coffee", "o", "nomu"],
      explainEn: "で marks the place of the action. に would be destination.",
      explainJa: "で は動作の場所。に は行き先。",
    },
    {
      id: "sm-2",
      promptEn: "Build: Tanaka-san is a student.",
      promptJa: "田中さんは学生です。",
      ttsText: "たなかさんはがくせいです",
      tiles: [
        { id: "tanaka", label: "田中", script: "kanji", reading: "たなか" },
        { id: "san", label: "さん", script: "hiragana" },
        { id: "wa", label: "は", script: "particle", reading: "wa" },
        { id: "gakusei", label: "学生", script: "kanji", reading: "がくせい" },
        { id: "desu", label: "です", script: "hiragana" },
      ],
      extra: [{ id: "sensei", label: "先生", script: "kanji", reading: "せんせい" }],
      order: ["tanaka", "san", "wa", "gakusei", "desu"],
      explainEn: "さん is hiragana after a kanji name. 学生 is a kanji word.",
      explainJa: "名前＋さん。学生は漢字語。",
    },
    {
      id: "sm-3",
      promptEn: "Build: I buy a ticket at the station.",
      promptJa: "駅で切符を買います。",
      ttsText: "えきできっぷをかいます",
      tiles: [
        { id: "eki", label: "駅", script: "kanji", reading: "えき" },
        { id: "de", label: "で", script: "particle" },
        { id: "kippu", label: "切符", script: "kanji", reading: "きっぷ" },
        { id: "o", label: "を", script: "particle" },
        { id: "kau", label: "買います", script: "kanji", reading: "かいます" },
      ],
      extra: [{ id: "ni", label: "に", script: "particle" }],
      order: ["eki", "de", "kippu", "o", "kau"],
      explainEn: "駅で = at the station. Action place uses で.",
      explainJa: "駅で＝駅という場所で。",
    },
    {
      id: "sm-4",
      promptEn: "Build: Please give me water.",
      promptJa: "水をください。",
      ttsText: "みずをください",
      tiles: [
        { id: "mizu", label: "水", script: "kanji", reading: "みず" },
        { id: "o", label: "を", script: "particle" },
        { id: "kudasai", label: "ください", script: "hiragana" },
      ],
      extra: [{ id: "dozo", label: "どうぞ", script: "hiragana" }],
      order: ["mizu", "o", "kudasai"],
      explainEn: "Item + を + ください. High-frequency survival line.",
      explainJa: "名詞＋を＋ください。",
    },
    {
      id: "sm-5",
      promptEn: "Build: I study Japanese every day.",
      promptJa: "毎日日本語を勉強します。",
      ttsText: "まいにちにほんごをべんきょうします",
      tiles: [
        { id: "mainichi", label: "毎日", script: "kanji", reading: "まいにち" },
        { id: "nihongo", label: "日本語", script: "kanji", reading: "にほんご" },
        { id: "o", label: "を", script: "particle" },
        { id: "benkyou", label: "勉強します", script: "kanji", reading: "べんきょうします" },
      ],
      extra: [{ id: "wa", label: "は", script: "particle" }],
      order: ["mainichi", "nihongo", "o", "benkyou"],
      explainEn: "Time words often come first. No に needed on 毎日.",
      explainJa: "毎日は先頭。に は不要。",
    },
  ],
});
