import { speechTargets } from "@/lib/japanese-normalize";
import type { SpeakDrill } from "@/lib/types";

export const speakLabDrills: SpeakDrill[] = [
  {
    id: "sp-1",
    ja: "こんにちは",
    reading: "こんにちは",
    en: "Hello (daytime)",
    pitch: "LHHH",
    expectedSpeech: speechTargets("こんにちは", "こんにちは", "konnichiwa", ["こんにちわ"]),
  },
  {
    id: "sp-2",
    ja: "おはようございます",
    reading: "おはようございます",
    en: "Good morning (polite)",
    pitch: "LHHHHHH",
    expectedSpeech: speechTargets("おはようございます", "おはようございます", "ohayou gozaimasu"),
  },
  {
    id: "sp-3",
    ja: "ありがとう",
    reading: "ありがとう",
    en: "Thanks",
    pitch: "LHHH",
    expectedSpeech: speechTargets("ありがとう", "ありがとう", "arigatou"),
  },
  {
    id: "sp-4",
    ja: "ありがとうございます",
    reading: "ありがとうございます",
    en: "Thank you (polite)",
    expectedSpeech: speechTargets("ありがとうございます", "ありがとうございます", "arigatou gozaimasu"),
  },
  {
    id: "sp-5",
    ja: "すみません",
    reading: "すみません",
    en: "Excuse me / sorry",
    expectedSpeech: speechTargets("すみません", "すみません", "sumimasen"),
  },
  {
    id: "sp-6",
    ja: "はい",
    reading: "はい",
    en: "Yes",
    pitch: "H",
    expectedSpeech: speechTargets("はい", "はい", "hai"),
  },
  {
    id: "sp-7",
    ja: "いいえ",
    reading: "いいえ",
    en: "No",
    expectedSpeech: speechTargets("いいえ", "いいえ", "iie"),
  },
  {
    id: "sp-8",
    ja: "はじめまして",
    reading: "はじめまして",
    en: "Nice to meet you",
    expectedSpeech: speechTargets("はじめまして", "はじめまして", "hajimemashite"),
  },
  {
    id: "sp-9",
    ja: "よろしくおねがいします",
    reading: "よろしくおねがいします",
    en: "Please treat me kindly",
    expectedSpeech: speechTargets("よろしくおねがいします", "よろしくおねがいします", "yoroshiku onegai shimasu"),
  },
  {
    id: "sp-10",
    ja: "みずをください",
    reading: "みずをください",
    en: "Water, please",
    expectedSpeech: speechTargets("みずをください", "みずをください", "mizu o kudasai"),
  },
  {
    id: "sp-11",
    ja: "いくらですか",
    reading: "いくらですか",
    en: "How much is it?",
    expectedSpeech: speechTargets("いくらですか", "いくらですか", "ikura desu ka"),
  },
  {
    id: "sp-12",
    ja: "これをください",
    reading: "これをください",
    en: "This one, please",
    expectedSpeech: speechTargets("これをください", "これをください", "kore o kudasai"),
  },
  {
    id: "sp-13",
    ja: "おいしいです",
    reading: "おいしいです",
    en: "It is delicious",
    expectedSpeech: speechTargets("おいしいです", "おいしいです", "oishii desu"),
  },
  {
    id: "sp-14",
    ja: "いまなんじですか",
    reading: "いまなんじですか",
    en: "What time is it?",
    expectedSpeech: speechTargets("いまなんじですか", "いまなんじですか", "ima nanji desu ka"),
  },
  {
    id: "sp-15",
    ja: "きょうはいいてんきですね",
    reading: "きょうはいいてんきですね",
    en: "Nice weather today, isn't it?",
    expectedSpeech: speechTargets("きょうはいいてんきですね", "きょうはいいてんきですね", "kyou wa ii tenki desu ne"),
  },
  {
    id: "sp-16",
    ja: "がくせいです",
    reading: "がくせいです",
    en: "I am a student",
    expectedSpeech: speechTargets("がくせいです", "がくせいです", "gakusei desu"),
  },
  {
    id: "sp-17",
    ja: "にほんごをべんきょうします",
    reading: "にほんごをべんきょうします",
    en: "I study Japanese",
    expectedSpeech: speechTargets("にほんごをべんきょうします", "にほんごをべんきょうします", "nihongo o benkyou shimasu"),
  },
  {
    id: "sp-18",
    ja: "だいじょうぶです",
    reading: "だいじょうぶです",
    en: "It's okay / I'm fine",
    expectedSpeech: speechTargets("だいじょうぶです", "だいじょうぶです", "daijoubu desu"),
  },
];
