import type { GradedStory } from "@/lib/types";

export const japaneseStories: GradedStory[] = [
  {
    id: "ohayou",
    title: "Good morning, Lumi",
    titleJa: "おはよう、ルミ",
    level: "Start",
    minutes: 3,
    synopsisEn: "Lumi wakes up, greets you, and drinks water. Tiny hiragana story.",
    synopsisJa: "ルミが起きて、あいさつして、水を飲みます。",
    lines: [
      [
        { surface: "あさ", reading: "asa", meaning: "morning", tts: "あさ" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "。", tts: "あさです" },
      ],
      [
        { surface: "ルミ", reading: "rumi", meaning: "Lumi", tts: "ルミ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "おきます", reading: "okimasu", meaning: "gets up", tts: "おきます" },
        { surface: "。", tts: "ルミはおきます" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "おはよう", reading: "ohayou", meaning: "good morning", tts: "おはよう" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "おはようといいます" },
      ],
      [
        { surface: "みず", reading: "mizu", meaning: "water", tts: "みず" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "のみます", reading: "nomimasu", meaning: "drinks", tts: "のみます" },
        { surface: "。", tts: "みずをのみます" },
      ],
      [
        { surface: "きょう", reading: "kyou", meaning: "today", tts: "きょう" },
        { surface: "も", reading: "mo", meaning: "also", tts: "も" },
        { surface: "げんき", reading: "genki", meaning: "well / energetic", tts: "げんき" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "。", tts: "きょうもげんきです" },
      ],
    ],
    questions: [
      {
        id: "st-oh-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What does Lumi say?",
        promptJa: "ルミは何と言いますか。",
        choices: [
          { id: "a", label: "こんにちは" },
          { id: "b", label: "おはよう" },
          { id: "c", label: "さようなら" },
          { id: "d", label: "ありがとう" },
        ],
        correctChoiceId: "b",
        explanationEn: "Lumi says おはよう in the morning.",
        explanationJa: "朝なので おはよう です。",
      },
      {
        id: "st-oh-2",
        kind: "listen-choice",
        skill: "listen",
        prompt: "Listen. What does Lumi drink?",
        promptJa: "ルミは何を飲みますか。",
        ttsText: "みずをのみます",
        ttsLang: "ja-JP",
        choices: [
          { id: "a", label: "コーヒー" },
          { id: "b", label: "パン" },
          { id: "c", label: "みず" },
          { id: "d", label: "おちゃ" },
        ],
        correctChoiceId: "c",
        explanationEn: "みずをのみます — she drinks water.",
        explanationJa: "みずをのみます。",
      },
    ],
  },
  {
    id: "neko-to-inu",
    title: "The cat and the dog",
    titleJa: "ねこといぬ",
    level: "N5-start",
    minutes: 4,
    synopsisEn: "A cat and a dog meet in a park and become friends.",
    synopsisJa: "公園でねこといぬが出会います。",
    lines: [
      [
        { surface: "こうえん", reading: "kouen", meaning: "park", tts: "こうえん" },
        { surface: "に", reading: "ni", meaning: "at / to", tts: "に" },
        { surface: "ねこ", reading: "neko", meaning: "cat", tts: "ねこ" },
        { surface: "が", reading: "ga", meaning: "subject", tts: "が" },
        { surface: "います", reading: "imasu", meaning: "is (animate)", tts: "います" },
        { surface: "。", tts: "こうえんにねこがいます" },
      ],
      [
        { surface: "いぬ", reading: "inu", meaning: "dog", tts: "いぬ" },
        { surface: "も", reading: "mo", meaning: "also", tts: "も" },
        { surface: "います", reading: "imasu", meaning: "is", tts: "います" },
        { surface: "。", tts: "いぬもいます" },
      ],
      [
        { surface: "ねこ", reading: "neko", meaning: "cat", tts: "ねこ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "こんにちは", reading: "konnichiwa", meaning: "hello", tts: "こんにちは" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "ねこはこんにちはといいます" },
      ],
      [
        { surface: "いぬ", reading: "inu", meaning: "dog", tts: "いぬ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "はじめまして", reading: "hajimemashite", meaning: "nice to meet you", tts: "はじめまして" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "いぬははじめましてといいます" },
      ],
      [
        { surface: "ふたり", reading: "futari", meaning: "two people / two of them", tts: "ふたり" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "ともだち", reading: "tomodachi", meaning: "friends", tts: "ともだち" },
        { surface: "です", reading: "desu", meaning: "are", tts: "です" },
        { surface: "。", tts: "ふたりはともだちです" },
      ],
    ],
    questions: [
      {
        id: "st-ni-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "Where are the cat and dog?",
        promptJa: "ねこといぬはどこにいますか。",
        choices: [
          { id: "a", label: "がっこう" },
          { id: "b", label: "こうえん" },
          { id: "c", label: "うち" },
          { id: "d", label: "みせ" },
        ],
        correctChoiceId: "b",
        explanationEn: "こうえんにねこがいます — they are in the park.",
        explanationJa: "こうえんにいます。",
      },
      {
        id: "st-ni-2",
        kind: "speak-prompt",
        skill: "speak",
        prompt: "Say the cat's greeting: こんにちは.",
        promptJa: "ねこのあいさつ「こんにちは」を言う。",
        ttsText: "こんにちは",
        ttsLang: "ja-JP",
        expectedSpeech: ["こんにちは", "こんにちわ", "konnichiwa"],
        explanationEn: "こんにちは is the daytime hello.",
        explanationJa: "こんにちはは昼間のあいさつ。",
      },
    ],
  },
  {
    id: "konbini",
    title: "At the convenience store",
    titleJa: "コンビニ",
    level: "N5",
    minutes: 5,
    synopsisEn: "You buy water and a rice ball. The clerk asks about a bag.",
    synopsisJa: "水とおにぎりを買います。袋を聞かれます。",
    lines: [
      [
        { surface: "コンビニ", reading: "konbini", meaning: "convenience store", tts: "コンビニ" },
        { surface: "に", reading: "ni", meaning: "to", tts: "に" },
        { surface: "いきます", reading: "ikimasu", meaning: "go", tts: "いきます" },
        { surface: "。", tts: "コンビニにいきます" },
      ],
      [
        { surface: "みず", reading: "mizu", meaning: "water", tts: "みず" },
        { surface: "と", reading: "to", meaning: "and", tts: "と" },
        { surface: "おにぎり", reading: "onigiri", meaning: "rice ball", tts: "おにぎり" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "かいます", reading: "kaimasu", meaning: "buy", tts: "かいます" },
        { surface: "。", tts: "みずとおにぎりをかいます" },
      ],
      [
        { surface: "てんいん", reading: "ten'in", meaning: "clerk", tts: "てんいん" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "ふくろ", reading: "fukuro", meaning: "bag", tts: "ふくろ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "いりますか", reading: "irimasu ka", meaning: "do you need?", tts: "いりますか" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "ききます", reading: "kikimasu", meaning: "asks", tts: "ききます" },
        { surface: "。", tts: "ふくろはいりますか" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "いいえ", reading: "iie", meaning: "no", tts: "いいえ" },
        { surface: "、", tts: "" },
        { surface: "だいじょうぶ", reading: "daijoubu", meaning: "it's fine", tts: "だいじょうぶ" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "」", tts: "" },
        { surface: "。", tts: "いいえだいじょうぶです" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "ありがとうございます", reading: "arigatou gozaimasu", meaning: "thank you", tts: "ありがとうございます" },
        { surface: "」", tts: "" },
        { surface: "。", tts: "ありがとうございます" },
      ],
    ],
    questions: [
      {
        id: "st-kb-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What two things does the shopper buy?",
        promptJa: "何を買いますか。",
        choices: [
          { id: "a", label: "コーヒーとパン" },
          { id: "b", label: "みずとおにぎり" },
          { id: "c", label: "おちゃとケーキ" },
          { id: "d", label: "ミルクとたまご" },
        ],
        correctChoiceId: "b",
        explanationEn: "みずとおにぎりをかいます.",
        explanationJa: "水とおにぎりです。",
      },
      {
        id: "st-kb-2",
        kind: "multiple-choice",
        skill: "read",
        prompt: "Does the shopper want a bag?",
        promptJa: "袋は要りますか。",
        choices: [
          { id: "a", label: "Yes" },
          { id: "b", label: "No — だいじょうぶです" },
          { id: "c", label: "They did not answer" },
          { id: "d", label: "They asked for two bags" },
        ],
        correctChoiceId: "b",
        explanationEn: "いいえ、だいじょうぶです means no bag needed.",
        explanationJa: "いいえ、だいじょうぶです。",
      },
    ],
  },
];

export function getStory(id: string): GradedStory | undefined {
  return japaneseStories.find((story) => story.id === id);
}
