import type { GradedStory } from "@/lib/types";

export const japaneseStories: GradedStory[] = [
  {
    id: "ohayou",
    title: "Good morning, Lumi",
    titleJa: "おはよう、ルミ",
    level: "Start",
    minutes: 3,
    synopsisEn: "Lumi wakes up, greets you, and drinks water. Tiny hiragana story.",
    synopsisJa: "ルミが起きて、あいさつして、水を飲みます。",
    lines: [
      [
        { surface: "あさ", reading: "asa", meaning: "morning", tts: "あさ" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "。", tts: "あさです" },
      ],
      [
        { surface: "ルミ", reading: "rumi", meaning: "Lumi", tts: "ルミ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "おきます", reading: "okimasu", meaning: "gets up", tts: "おきます" },
        { surface: "。", tts: "ルミはおきます" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "おはよう", reading: "ohayou", meaning: "good morning", tts: "おはよう" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "おはようといいます" },
      ],
      [
        { surface: "みず", reading: "mizu", meaning: "water", tts: "みず" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "のみます", reading: "nomimasu", meaning: "drinks", tts: "のみます" },
        { surface: "。", tts: "みずをのみます" },
      ],
      [
        { surface: "きょう", reading: "kyou", meaning: "today", tts: "きょう" },
        { surface: "も", reading: "mo", meaning: "also", tts: "も" },
        { surface: "げんき", reading: "genki", meaning: "well / energetic", tts: "げんき" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "。", tts: "きょうもげんきです" },
      ],
    ],
    questions: [
      {
        id: "st-oh-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What does Lumi say?",
        promptJa: "ルミは何と言いますか。",
        choices: [
          { id: "a", label: "こんにちは" },
          { id: "b", label: "おはよう" },
          { id: "c", label: "さようなら" },
          { id: "d", label: "ありがとう" },
        ],
        correctChoiceId: "b",
        explanationEn: "Lumi says おはよう in the morning.",
        explanationJa: "朝なので おはよう です。",
      },
      {
        id: "st-oh-2",
        kind: "listen-choice",
        skill: "listen",
        prompt: "Listen. What does Lumi drink?",
        promptJa: "ルミは何を飲みますか。",
        ttsText: "みずをのみます",
        ttsLang: "ja-JP",
        choices: [
          { id: "a", label: "コーヒー" },
          { id: "b", label: "パン" },
          { id: "c", label: "みず" },
          { id: "d", label: "おちゃ" },
        ],
        correctChoiceId: "c",
        explanationEn: "みずをのみます — she drinks water.",
        explanationJa: "みずをのみます。",
      },
    ],
  },
  {
    id: "neko-to-inu",
    title: "The cat and the dog",
    titleJa: "ねこといぬ",
    level: "N5-start",
    minutes: 4,
    synopsisEn: "A cat and a dog meet in a park and become friends.",
    synopsisJa: "公園でねこといぬが出会います。",
    lines: [
      [
        { surface: "こうえん", reading: "kouen", meaning: "park", tts: "こうえん" },
        { surface: "に", reading: "ni", meaning: "at / to", tts: "に" },
        { surface: "ねこ", reading: "neko", meaning: "cat", tts: "ねこ" },
        { surface: "が", reading: "ga", meaning: "subject", tts: "が" },
        { surface: "います", reading: "imasu", meaning: "is (animate)", tts: "います" },
        { surface: "。", tts: "こうえんにねこがいます" },
      ],
      [
        { surface: "いぬ", reading: "inu", meaning: "dog", tts: "いぬ" },
        { surface: "も", reading: "mo", meaning: "also", tts: "も" },
        { surface: "います", reading: "imasu", meaning: "is", tts: "います" },
        { surface: "。", tts: "いぬもいます" },
      ],
      [
        { surface: "ねこ", reading: "neko", meaning: "cat", tts: "ねこ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "こんにちは", reading: "konnichiwa", meaning: "hello", tts: "こんにちは" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "ねこはこんにちはといいます" },
      ],
      [
        { surface: "いぬ", reading: "inu", meaning: "dog", tts: "いぬ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "はじめまして", reading: "hajimemashite", meaning: "nice to meet you", tts: "はじめまして" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "いぬははじめましてといいます" },
      ],
      [
        { surface: "ふたり", reading: "futari", meaning: "two people / two of them", tts: "ふたり" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "ともだち", reading: "tomodachi", meaning: "friends", tts: "ともだち" },
        { surface: "です", reading: "desu", meaning: "are", tts: "です" },
        { surface: "。", tts: "ふたりはともだちです" },
      ],
    ],
    questions: [
      {
        id: "st-ni-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "Where are the cat and dog?",
        promptJa: "ねこといぬはどこにいますか。",
        choices: [
          { id: "a", label: "がっこう" },
          { id: "b", label: "こうえん" },
          { id: "c", label: "うち" },
          { id: "d", label: "みせ" },
        ],
        correctChoiceId: "b",
        explanationEn: "こうえんにねこがいます — they are in the park.",
        explanationJa: "こうえんにいます。",
      },
      {
        id: "st-ni-2",
        kind: "speak-prompt",
        skill: "speak",
        prompt: "Say the cat's greeting: こんにちは.",
        promptJa: "ねこのあいさつ「こんにちは」を言う。",
        ttsText: "こんにちは",
        ttsLang: "ja-JP",
        expectedSpeech: ["こんにちは", "こんにちわ", "konnichiwa"],
        explanationEn: "こんにちは is the daytime hello.",
        explanationJa: "こんにちはは昼間のあいさつ。",
      },
    ],
  },
  {
    id: "konbini",
    title: "At the convenience store",
    titleJa: "コンビニ",
    level: "N5",
    minutes: 5,
    synopsisEn: "You buy water and a rice ball. The clerk asks about a bag.",
    synopsisJa: "水とおにぎりを買います。袋を聞かれます。",
    lines: [
      [
        { surface: "コンビニ", reading: "konbini", meaning: "convenience store", tts: "コンビニ" },
        { surface: "に", reading: "ni", meaning: "to", tts: "に" },
        { surface: "いきます", reading: "ikimasu", meaning: "go", tts: "いきます" },
        { surface: "。", tts: "コンビニにいきます" },
      ],
      [
        { surface: "みず", reading: "mizu", meaning: "water", tts: "みず" },
        { surface: "と", reading: "to", meaning: "and", tts: "と" },
        { surface: "おにぎり", reading: "onigiri", meaning: "rice ball", tts: "おにぎり" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "かいます", reading: "kaimasu", meaning: "buy", tts: "かいます" },
        { surface: "。", tts: "みずとおにぎりをかいます" },
      ],
      [
        { surface: "てんいん", reading: "ten'in", meaning: "clerk", tts: "てんいん" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "ふくろ", reading: "fukuro", meaning: "bag", tts: "ふくろ" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "いりますか", reading: "irimasu ka", meaning: "do you need?", tts: "いりますか" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "ききます", reading: "kikimasu", meaning: "asks", tts: "ききます" },
        { surface: "。", tts: "ふくろはいりますか" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "いいえ", reading: "iie", meaning: "no", tts: "いいえ" },
        { surface: "、", tts: "" },
        { surface: "だいじょうぶ", reading: "daijoubu", meaning: "it's fine", tts: "だいじょうぶ" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "」", tts: "" },
        { surface: "。", tts: "いいえだいじょうぶです" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "ありがとうございます", reading: "arigatou gozaimasu", meaning: "thank you", tts: "ありがとうございます" },
        { surface: "」", tts: "" },
        { surface: "。", tts: "ありがとうございます" },
      ],
    ],
    questions: [
      {
        id: "st-kb-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What two things does the shopper buy?",
        promptJa: "何を買いますか。",
        choices: [
          { id: "a", label: "コーヒーとパン" },
          { id: "b", label: "みずとおにぎり" },
          { id: "c", label: "おちゃとケーキ" },
          { id: "d", label: "ミルクとたまご" },
        ],
        correctChoiceId: "b",
        explanationEn: "みずとおにぎりをかいます.",
        explanationJa: "水とおにぎりです。",
      },
      {
        id: "st-kb-2",
        kind: "multiple-choice",
        skill: "read",
        prompt: "Does the shopper want a bag?",
        promptJa: "袋は要りますか。",
        choices: [
          { id: "a", label: "Yes" },
          { id: "b", label: "No — だいじょうぶです" },
          { id: "c", label: "They did not answer" },
          { id: "d", label: "They asked for two bags" },
        ],
        correctChoiceId: "b",
        explanationEn: "いいえ、だいじょうぶです means no bag needed.",
        explanationJa: "いいえ、だいじょうぶです。",
      },
    ],
  },
  {
    id: "gakkou",
    title: "A morning at school",
    titleJa: "がっこうのあさ",
    level: "N5-start",
    minutes: 4,
    furiganaDefault: "on",
    synopsisEn: "Lumi goes to school, greets the teacher, and studies Japanese.",
    synopsisJa: "ルミが学校に行き、先生にあいさつして、日本語を勉強します。",
    lines: [
      [
        { surface: "あさ", reading: "asa", meaning: "morning", tts: "あさ" },
        { surface: "、", tts: "" },
        { surface: "がっこう", reading: "gakkou", meaning: "school", tts: "がっこう" },
        { surface: "に", reading: "ni", meaning: "to", tts: "に" },
        { surface: "いきます", reading: "ikimasu", meaning: "go", tts: "いきます" },
        { surface: "。", tts: "あさがっこうにいきます" },
      ],
      [
        { surface: "せんせい", reading: "sensei", meaning: "teacher", tts: "せんせい" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "「", tts: "" },
        { surface: "おはよう", reading: "ohayou", meaning: "good morning", tts: "おはよう" },
        { surface: "」", tts: "" },
        { surface: "と", reading: "to", meaning: "quote", tts: "と" },
        { surface: "いいます", reading: "iimasu", meaning: "says", tts: "いいます" },
        { surface: "。", tts: "せんせいはおはようといいます" },
      ],
      [
        { surface: "わたし", reading: "watashi", meaning: "I", tts: "わたし" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "にほんご", reading: "nihongo", meaning: "Japanese", tts: "にほんご" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "べんきょうします", reading: "benkyou shimasu", meaning: "study", tts: "べんきょうします" },
        { surface: "。", tts: "わたしはにほんごをべんきょうします" },
      ],
      [
        { surface: "ともだち", reading: "tomodachi", meaning: "friend", tts: "ともだち" },
        { surface: "と", reading: "to", meaning: "with", tts: "と" },
        { surface: "パン", reading: "pan", meaning: "bread", tts: "パン" },
        { surface: "を", reading: "o", meaning: "object", tts: "を" },
        { surface: "たべます", reading: "tabemasu", meaning: "eat", tts: "たべます" },
        { surface: "。", tts: "ともだちとパンをたべます" },
      ],
      [
        { surface: "きょう", reading: "kyou", meaning: "today", tts: "きょう" },
        { surface: "は", reading: "wa", meaning: "topic", tts: "は" },
        { surface: "たのしい", reading: "tanoshii", meaning: "fun", tts: "たのしい" },
        { surface: "です", reading: "desu", meaning: "is", tts: "です" },
        { surface: "。", tts: "きょうはたのしいです" },
      ],
    ],
    questions: [
      {
        id: "st-gk-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What does the student study?",
        promptJa: "何を勉強しますか。",
        choices: [
          { id: "a", label: "えいご" },
          { id: "b", label: "にほんご" },
          { id: "c", label: "すうがく" },
          { id: "d", label: "おんがく" },
        ],
        correctChoiceId: "b",
        explanationEn: "わたしはにほんごをべんきょうします.",
        explanationJa: "日本語を勉強します。",
      },
      {
        id: "st-gk-2",
        kind: "sentence-build",
        skill: "read",
        prompt: "Build: I study Japanese.",
        promptJa: "「日本語を勉強します」を組み立てる。",
        ttsText: "わたしはにほんごをべんきょうします",
        ttsLang: "ja-JP",
        tiles: [
          { id: "watashi", label: "わたし", script: "hiragana" },
          { id: "wa", label: "は", script: "particle", reading: "wa" },
          { id: "nihongo", label: "にほんご", script: "hiragana" },
          { id: "o", label: "を", script: "particle", reading: "o" },
          { id: "benkyou", label: "べんきょうします", script: "hiragana" },
        ],
        correctOrder: ["watashi", "wa", "nihongo", "o", "benkyou"],
        explanationEn: "Topic は, object を, verb last.",
        explanationJa: "は・を・動詞の順。",
      },
    ],
  },
  {
    id: "eki",
    title: "At the station",
    titleJa: "駅で",
    level: "N5",
    minutes: 5,
    furiganaDefault: "on",
    synopsisEn: "Buy a ticket, board the train, and hear the Tokyo stop.",
    synopsisJa: "切符を買い、電車に乗り、東京のアナウンスを聞きます。",
    lines: [
      [
        { surface: "駅", reading: "えき", meaning: "station", tts: "えき" },
        { surface: "に", reading: "に", meaning: "to", tts: "に" },
        { surface: "行きます", reading: "いきます", meaning: "go", tts: "いきます" },
        { surface: "。", tts: "えきにいきます" },
      ],
      [
        { surface: "切符", reading: "きっぷ", meaning: "ticket", tts: "きっぷ" },
        { surface: "を", reading: "を", meaning: "object", tts: "を" },
        { surface: "買います", reading: "かいます", meaning: "buy", tts: "かいます" },
        { surface: "。", tts: "きっぷをかいます" },
      ],
      [
        { surface: "電車", reading: "でんしゃ", meaning: "train", tts: "でんしゃ" },
        { surface: "が", reading: "が", meaning: "subject", tts: "が" },
        { surface: "来ます", reading: "きます", meaning: "comes", tts: "きます" },
        { surface: "。", tts: "でんしゃがきます" },
      ],
      [
        { surface: "東京", reading: "とうきょう", meaning: "Tokyo", tts: "とうきょう" },
        { surface: "に", reading: "に", meaning: "to", tts: "に" },
        { surface: "行きます", reading: "いきます", meaning: "go", tts: "いきます" },
        { surface: "。", tts: "とうきょうにいきます" },
      ],
      [
        { surface: "「", tts: "" },
        { surface: "次", reading: "つぎ", meaning: "next", tts: "つぎ" },
        { surface: "は", reading: "わ", meaning: "topic", tts: "は" },
        { surface: "東京", reading: "とうきょう", meaning: "Tokyo", tts: "とうきょう" },
        { surface: "です", reading: "です", meaning: "is", tts: "です" },
        { surface: "」", tts: "" },
        { surface: "。", tts: "つぎはとうきょうです" },
      ],
    ],
    questions: [
      {
        id: "st-ek-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What does the rider buy?",
        promptJa: "何を買いますか。",
        choices: [
          { id: "a", label: "コーヒー" },
          { id: "b", label: "切符" },
          { id: "c", label: "新聞" },
          { id: "d", label: "水" },
        ],
        correctChoiceId: "b",
        explanationEn: "切符を買います — they buy a ticket.",
        explanationJa: "切符を買います。",
      },
      {
        id: "st-ek-2",
        kind: "multiple-choice",
        skill: "read",
        prompt: "What is the next stop?",
        promptJa: "次はどこですか。",
        choices: [
          { id: "a", label: "大阪" },
          { id: "b", label: "京都" },
          { id: "c", label: "東京" },
          { id: "d", label: "横浜" },
        ],
        correctChoiceId: "c",
        explanationEn: "次は東京です.",
        explanationJa: "次は東京です。",
      },
    ],
  },
  {
    id: "office-mail",
    title: "A short work email",
    titleJa: "短い仕事のメール",
    level: "Workplace",
    minutes: 6,
    furiganaDefault: "off",
    synopsisEn:
      "Tanaka opens politely, sets a 3 o'clock meeting, and asks you to check the file. Practice with furigana off.",
    synopsisJa:
      "田中が丁寧に書き出し、会議は3時、ファイルの確認を依頼します。ふりがななしで練習。",
    lines: [
      [
        { surface: "田中", reading: "たなか", meaning: "Tanaka", tts: "たなか" },
        { surface: "です", reading: "です", meaning: "is / I am", tts: "です" },
        { surface: "。", tts: "たなかです" },
      ],
      [
        { surface: "お世話", reading: "おせわ", meaning: "care / support", tts: "おせわ" },
        { surface: "に", reading: "に", meaning: "particle", tts: "に" },
        { surface: "なって", reading: "なって", meaning: "become (te)", tts: "なって" },
        { surface: "おります", reading: "おります", meaning: "humble am", tts: "おります" },
        { surface: "。", tts: "おせわになっております" },
      ],
      [
        { surface: "会議", reading: "かいぎ", meaning: "meeting", tts: "かいぎ" },
        { surface: "は", reading: "わ", meaning: "topic", tts: "は" },
        { surface: "3時", reading: "さんじ", meaning: "3 o'clock", tts: "さんじ" },
        { surface: "です", reading: "です", meaning: "is", tts: "です" },
        { surface: "。", tts: "かいぎはさんじです" },
      ],
      [
        { surface: "添付", reading: "てんぷ", meaning: "attached", tts: "てんぷ" },
        { surface: "ファイル", reading: "ファイル", meaning: "file", tts: "ファイル" },
        { surface: "を", reading: "を", meaning: "object", tts: "を" },
        { surface: "ご確認", reading: "ごかくにん", meaning: "confirmation (honorific)", tts: "ごかくにん" },
        { surface: "ください", reading: "ください", meaning: "please", tts: "ください" },
        { surface: "。", tts: "てんぷファイルをごかくにんください" },
      ],
      [
        { surface: "よろしく", reading: "よろしく", meaning: "kindly", tts: "よろしく" },
        { surface: "お願い", reading: "おねがい", meaning: "request", tts: "おねがい" },
        { surface: "いたします", reading: "いたします", meaning: "humble do", tts: "いたします" },
        { surface: "。", tts: "よろしくおねがいいたします" },
      ],
    ],
    questions: [
      {
        id: "st-om-1",
        kind: "multiple-choice",
        skill: "read",
        prompt: "When is the meeting?",
        promptJa: "会議は何時ですか。",
        choices: [
          { id: "a", label: "2時" },
          { id: "b", label: "3時" },
          { id: "c", label: "4時" },
          { id: "d", label: "明日" },
        ],
        correctChoiceId: "b",
        explanationEn: "会議は3時です.",
        explanationJa: "会議は3時です。",
      },
      {
        id: "st-om-2",
        kind: "sentence-build",
        skill: "read",
        prompt: "Build: Please check the attached file.",
        promptJa: "添付ファイルをご確認ください。",
        ttsText: "てんぷファイルをごかくにんください",
        ttsLang: "ja-JP",
        tiles: [
          { id: "tenpu", label: "添付", script: "kanji", reading: "てんぷ" },
          { id: "file", label: "ファイル", script: "katakana" },
          { id: "o", label: "を", script: "particle" },
          { id: "go", label: "ご", script: "hiragana" },
          { id: "kakunin", label: "確認", script: "kanji", reading: "かくにん" },
          { id: "kudasai", label: "ください", script: "hiragana" },
          { id: "wa", label: "は", script: "particle" },
        ],
        correctOrder: ["tenpu", "file", "o", "go", "kakunin", "kudasai"],
        hideReadings: true,
        explanationEn: "ご + 確認 + ください is the polite inbox request.",
        explanationJa: "ご確認ください が丁寧な依頼。",
      },
    ],
  },
];

export function getStory(id: string): GradedStory | undefined {
  return japaneseStories.find((story) => story.id === id);
}
