import { isLatinRomaji, looksLikeFillerMeaning } from "./kana-romaji.mjs";
import { MORE_HIRAGANA } from "./more-vocab.mjs";

/**
 * Real beginner/intermediate words written in hiragana.
 * Format: [word, romaji, english, short explanation]
 */
const CURATED = [
  ["みず", "mizu", "water", "Everyday drink or liquid."],
  ["ねこ", "neko", "cat", "Common animal word."],
  ["いぬ", "inu", "dog", "Common animal word."],
  ["やま", "yama", "mountain", "Nature word."],
  ["かわ", "kawa", "river", "Nature word."],
  ["はな", "hana", "flower", "Flower (or nose by context)."],
  ["あめ", "ame", "rain", "Weather word."],
  ["つき", "tsuki", "moon", "Night sky word."],
  ["あさ", "asa", "morning", "Time of day."],
  ["よる", "yoru", "night", "Time of day."],
  ["ともだち", "tomodachi", "friend", "Social word."],
  ["がっこう", "gakkou", "school", "Place word. Small っ = pause."],
  ["せんせい", "sensei", "teacher", "Polite title."],
  ["たべる", "taberu", "to eat", "Basic verb."],
  ["のむ", "nomu", "to drink", "Basic verb."],
  ["いく", "iku", "to go", "Motion verb."],
  ["くる", "kuru", "to come", "Motion verb."],
  ["おおきい", "ookii", "big", "Size adjective."],
  ["ちいさい", "chiisai", "small", "Size adjective."],
  ["あたらしい", "atarashii", "new", "For things."],
  ["ふるい", "furui", "old", "For things (not people)."],
  ["たかい", "takai", "expensive / tall", "Price or height."],
  ["やすい", "yasui", "cheap", "Low price."],
  ["おいしい", "oishii", "delicious", "Food praise."],
  ["おもしろい", "omoshiroi", "interesting / funny", "Fun or interesting."],
  ["むずかしい", "muzukashii", "difficult", "Hard task."],
  ["やさしい", "yasashii", "kind / easy", "Kind person or easy task."],
  ["はやい", "hayai", "fast / early", "Speed or time."],
  ["おそい", "osoi", "slow / late", "Opposite of hayai."],
  ["あつい", "atsui", "hot", "Weather or objects."],
  ["さむい", "samui", "cold (weather)", "Cold air."],
  ["つめたい", "tsumetai", "cold (to touch)", "Cold drinks or surfaces."],
  ["いそがしい", "isogashii", "busy", "Busy schedule."],
  ["げんき", "genki", "healthy / energetic", "How are you? 元気."],
  ["しずか", "shizuka", "quiet", "Quiet place."],
  ["にぎやか", "nigiyaka", "lively", "Busy lively place."],
  ["きれい", "kirei", "pretty / clean", "Beauty or cleanliness."],
  ["すき", "suki", "like", "Preference."],
  ["きらい", "kirai", "dislike", "Opposite of suki."],
  ["ほしい", "hoshii", "want (a thing)", "Desire for an object."],
  ["わかる", "wakaru", "to understand", "I get it."],
  ["みる", "miru", "to see / watch", "Look or watch."],
  ["きく", "kiku", "to hear / ask", "Listen or ask."],
  ["はなす", "hanasu", "to speak", "Talk with someone."],
  ["よむ", "yomu", "to read", "Read text."],
  ["かく", "kaku", "to write", "Write characters or notes."],
  ["かう", "kau", "to buy", "Shopping verb."],
  ["まつ", "matsu", "to wait", "Wait for someone."],
  ["あるく", "aruku", "to walk", "Go on foot."],
  ["はしる", "hashiru", "to run", "Run."],
  ["およぐ", "oyogu", "to swim", "Swim."],
  ["ねる", "neru", "to sleep", "Go to bed / sleep."],
  ["おきる", "okiru", "to wake up", "Get up."],
  ["はたらく", "hataraku", "to work", "Do a job."],
  ["やすむ", "yasumu", "to rest", "Take a break."],
  ["べんきょう", "benkyou", "study", "Study (noun/verb stem)."],
  ["しごと", "shigoto", "work / job", "Job or task."],
  ["かぞく", "kazoku", "family", "Family members."],
  ["こども", "kodomo", "child", "Child / kids."],
  ["おとな", "otona", "adult", "Grown-up."],
  ["ひと", "hito", "person", "A person / people."],
  ["なまえ", "namae", "name", "Someone's name."],
  ["くに", "kuni", "country", "Nation or homeland."],
  ["まち", "machi", "town", "Town or city area."],
  ["いえ", "ie", "house / home", "Home building."],
  ["うち", "uchi", "home / inside", "My place / home."],
  ["へや", "heya", "room", "A room."],
  ["まど", "mado", "window", "Window."],
  ["つくえ", "tsukue", "desk", "Study desk."],
  ["いす", "isu", "chair", "Seat."],
  ["ほん", "hon", "book", "Book."],
  ["ざっし", "zasshi", "magazine", "Magazine."],
  ["しんぶん", "shinbun", "newspaper", "Newspaper."],
  ["じしょ", "jisho", "dictionary", "Dictionary."],
  ["てがみ", "tegami", "letter", "Written letter."],
  ["でんわ", "denwa", "telephone", "Phone call / phone."],
  ["じかん", "jikan", "time", "Time or hour span."],
  ["きょう", "kyou", "today", "This day."],
  ["あした", "ashita", "tomorrow", "Next day."],
  ["きのう", "kinou", "yesterday", "Previous day."],
  ["いま", "ima", "now", "Right now."],
  ["まえ", "mae", "before / front", "Time or position."],
  ["あと", "ato", "after / later", "Afterwards."],
  ["みぎ", "migi", "right", "Right side."],
  ["ひだり", "hidari", "left", "Left side."],
  ["うえ", "ue", "up / above", "On top."],
  ["した", "shita", "down / below", "Under."],
  ["なか", "naka", "inside / middle", "In the middle."],
  ["そと", "soto", "outside", "Outdoors."],
  ["ちかく", "chikaku", "near", "Nearby."],
  ["とおい", "tooi", "far", "Far away."],
  ["となり", "tonari", "next to", "Neighboring."],
  ["ここ", "koko", "here", "This place."],
  ["そこ", "soko", "there", "Near the listener."],
  ["あそこ", "asoko", "over there", "Farther place."],
  ["どこ", "doko", "where", "Question word."],
  ["これ", "kore", "this (thing)", "Near the speaker."],
  ["それ", "sore", "that (thing)", "Near the listener."],
  ["あれ", "are", "that over there", "Far from both."],
  ["どれ", "dore", "which", "Which one?"],
  ["だれ", "dare", "who", "Who?"],
  ["なに", "nani", "what", "What?"],
  ["いつ", "itsu", "when", "When?"],
  ["いくら", "ikura", "how much", "Price question."],
  ["おはよう", "ohayou", "good morning", "Casual morning hello."],
  ["こんにちは", "konnichiwa", "hello", "Daytime greeting."],
  ["こんばんは", "konbanwa", "good evening", "Evening greeting."],
  ["さようなら", "sayounara", "goodbye", "Fuller goodbye."],
  ["ありがとう", "arigatou", "thank you", "Thanks."],
  ["すみません", "sumimasen", "excuse me / sorry", "Polite attention or apology."],
  ["ごめんなさい", "gomennasai", "I'm sorry", "Apology."],
  ["はい", "hai", "yes", "Affirmative."],
  ["いいえ", "iie", "no", "Negative."],
  ["いただきます", "itadakimasu", "thanks for the meal (before)", "Said before eating."],
  ["ごちそうさま", "gochisousama", "thanks for the meal (after)", "Said after eating."],
  ["いってきます", "ittekimasu", "I'm heading out", "Leaving home."],
  ["いってらっしゃい", "itterasshai", "see you later", "Said to someone leaving."],
  ["ただいま", "tadaima", "I'm home", "Returning home."],
  ["おかえり", "okaeri", "welcome back", "Greeting someone home."],
  ["おやすみ", "oyasumi", "good night", "Before sleep."],
  ["はじめまして", "hajimemashite", "nice to meet you", "First meeting."],
  ["よろしく", "yoroshiku", "please treat me well", "After introductions."],
  ["りんご", "ringo", "apple", "Fruit."],
  ["みかん", "mikan", "mandarin orange", "Fruit."],
  ["いちご", "ichigo", "strawberry", "Fruit."],
  ["すいか", "suika", "watermelon", "Fruit."],
  ["ごはん", "gohan", "rice / meal", "Cooked rice or a meal."],
  ["にく", "niku", "meat", "Meat."],
  ["さかな", "sakana", "fish", "Fish as food or animal."],
  ["やさい", "yasai", "vegetable", "Vegetables."],
  ["くだもの", "kudamono", "fruit", "Fruit (general)."],
  ["たまご", "tamago", "egg", "Egg."],
  ["ぎゅうにゅう", "gyuunyuu", "milk", "Cow's milk."],
  ["おちゃ", "ocha", "tea", "Often green tea."],
  ["うみ", "umi", "sea", "Ocean / sea."],
  ["そら", "sora", "sky", "Sky."],
  ["くも", "kumo", "cloud", "Cloud (also spider with other kanji)."],
  ["かぜ", "kaze", "wind", "Wind (or a cold)."],
  ["ゆき", "yuki", "snow", "Snow."],
  ["てんき", "tenki", "weather", "Weather."],
  ["はれ", "hare", "clear weather", "Sunny."],
  ["くもり", "kumori", "cloudy", "Cloudy weather."],
  ["でんしゃ", "densha", "train", "Electric train."],
  ["くるま", "kuruma", "car", "Car."],
  ["じてんしゃ", "jitensha", "bicycle", "Bike."],
  ["ひこうき", "hikouki", "airplane", "Plane."],
  ["ふね", "fune", "ship / boat", "Boat."],
  ["えき", "eki", "station", "Train station."],
  ["くうこう", "kuukou", "airport", "Airport."],
  ["びょういん", "byouin", "hospital", "Hospital."],
  ["ぎんこう", "ginkou", "bank", "Bank."],
  ["ゆうびんきょく", "yuubinkyoku", "post office", "Post office."],
  ["としょかん", "toshokan", "library", "Library."],
  ["こうえん", "kouen", "park", "Park."],
  ["みせ", "mise", "shop", "Store."],
  ["かいしゃ", "kaisha", "company", "Workplace company."],
  ["だいがく", "daigaku", "university", "College."],
  ["きょうしつ", "kyoushitsu", "classroom", "Classroom."],
  ["しけん", "shiken", "exam", "Test."],
  ["しゅくだい", "shukudai", "homework", "Homework."],
  ["やすみ", "yasumi", "day off / rest", "Holiday or break."],
  ["たんじょうび", "tanjoubi", "birthday", "Birthday."],
  ["りょこう", "ryokou", "trip", "Travel."],
  ["おかね", "okane", "money", "Money."],
  ["きっぷ", "kippu", "ticket", "Ticket."],
  ["かさ", "kasa", "umbrella", "Umbrella."],
  ["くつ", "kutsu", "shoes", "Shoes."],
  ["ふく", "fuku", "clothes", "Clothing."],
  ["かばん", "kaban", "bag", "Bag."],
  ["めがね", "megane", "glasses", "Eyeglasses."],
  ["とけい", "tokei", "clock / watch", "Timepiece."],
  ["かぎ", "kagi", "key", "Key."],
  ["でんき", "denki", "electricity / light", "Power or electric light."],
  ["おんがく", "ongaku", "music", "Music."],
  ["えいが", "eiga", "movie", "Film."],
  ["しゃしん", "shashin", "photo", "Photograph."],
  ["しゅみ", "shumi", "hobby", "Hobby."],
  ["あそぶ", "asobu", "to play", "Play / hang out."],
  ["つかれる", "tsukareru", "to get tired", "Become tired."],
  ["ねむい", "nemui", "sleepy", "Want to sleep."],
  ["あたま", "atama", "head", "Head."],
  ["かお", "kao", "face", "Face."],
  ["め", "me", "eye", "Eye."],
  ["みみ", "mimi", "ear", "Ear."],
  ["くち", "kuchi", "mouth", "Mouth."],
  ["て", "te", "hand", "Hand."],
  ["あし", "ashi", "foot / leg", "Foot or leg."],
  ["きもち", "kimochi", "feeling", "Feeling / mood."],
  ["しんぱい", "shinpai", "worry", "Worry."],
  ["あんしん", "anshin", "relief", "Peace of mind."],
  ["だいじょうぶ", "daijoubu", "okay / fine", "It's all right."],
  ["もちろん", "mochiron", "of course", "Certainly."],
  ["たぶん", "tabun", "probably", "Maybe / probably."],
  ["すぐ", "sugu", "soon / right away", "Immediately."],
  ["ゆっくり", "yukkuri", "slowly", "Take it slow."],
  ["いっしょ", "issho", "together", "Together."],
  ["ひとり", "hitori", "one person / alone", "Alone or one person."],
  ["ふたり", "futari", "two people", "Two persons."],
  ["みんな", "minna", "everyone", "All people."],
  ["いつも", "itsumo", "always", "Every time."],
  ["ときどき", "tokidoki", "sometimes", "Now and then."],
  ["ちょっと", "chotto", "a little", "A bit."],
  ["たくさん", "takusan", "a lot", "Many / much."],
  ["すこし", "sukoshi", "a little (amount)", "Small amount."],
  ["もう", "mou", "already / more", "Already or again."],
  ["まだ", "mada", "still / not yet", "Still or not yet."],
  ["また", "mata", "again", "Again."],
  ["ことば", "kotoba", "word / language", "Word or speech."],
  ["いみ", "imi", "meaning", "Meaning."],
  ["れんしゅう", "renshuu", "practice", "Practice."],
  ["げつようび", "getsuyoubi", "Monday", "Monday."],
  ["かようび", "kayoubi", "Tuesday", "Tuesday."],
  ["すいようび", "suiyoubi", "Wednesday", "Wednesday."],
  ["もくようび", "mokuyoubi", "Thursday", "Thursday."],
  ["きんようび", "kinyoubi", "Friday", "Friday."],
  ["どようび", "doyoubi", "Saturday", "Saturday."],
  ["にちようび", "nichiyoubi", "Sunday", "Sunday."],
  ["しゅうまつ", "shuumatsu", "weekend", "Weekend."],
  ["はる", "haru", "spring", "Season."],
  ["なつ", "natsu", "summer", "Season."],
  ["あき", "aki", "autumn", "Season."],
  ["ふゆ", "fuyu", "winter", "Season."],
  ["あお", "ao", "blue", "Color."],
  ["あか", "aka", "red", "Color."],
  ["しろ", "shiro", "white", "Color."],
  ["くろ", "kuro", "black", "Color."],
  ["きいろ", "kiiro", "yellow", "Color."],
  ["みどり", "midori", "green", "Color."],
  ["ちゃいろ", "chairo", "brown", "Color."],
  ["むらさき", "murasaki", "purple", "Color."],
  ["オレンジいろ", "orenjiiro", "orange (color)", "Color word using loan + iro."],
  ["きょねん", "kyonen", "last year", "Previous year."],
  ["ことし", "kotoshi", "this year", "Current year."],
  ["らいねん", "rainen", "next year", "Coming year."],
  ["せんしゅう", "senshuu", "last week", "Previous week."],
  ["こんしゅう", "konshuu", "this week", "Current week."],
  ["らいしゅう", "raishuu", "next week", "Coming week."],
  ["せんげつ", "sengetsu", "last month", "Previous month."],
  ["こんげつ", "kongetsu", "this month", "Current month."],
  ["らいげつ", "raigetsu", "next month", "Coming month."],
  ["まいあさ", "maiasa", "every morning", "Daily morning habit."],
  ["まいばん", "maiban", "every evening", "Daily evening habit."],
  ["まいにち", "mainichi", "every day", "Daily."],
  ["おととい", "ototoi", "day before yesterday", "Two days ago."],
  ["あさって", "asatte", "day after tomorrow", "Two days ahead."],
  ["にほんご", "nihongo", "Japanese (language)", "The Japanese language."],
  ["えいご", "eigo", "English (language)", "The English language."],
  ["すうじ", "suuji", "number / numeral", "Digits."],
  ["もじ", "moji", "character / letter", "Writing character."],
  ["かんじ", "kanji", "kanji", "Chinese characters used in Japanese."],
  ["ひらがな", "hiragana", "hiragana", "Rounded Japanese syllabary."],
  ["あさごはん", "asagohan", "breakfast", "Morning meal."],
  ["ひるごはん", "hirugohan", "lunch", "Midday meal."],
  ["ばんごはん", "bangohan", "dinner", "Evening meal."],
  ["おやつ", "oyatsu", "snack", "Between-meal snack."],
  ["みそしる", "misoshiru", "miso soup", "Classic Japanese soup."],
  ["すし", "sushi", "sushi", "Vinegared rice dish."],
  ["うどん", "udon", "udon", "Thick wheat noodles."],
  ["そば", "soba", "soba / nearby", "Buckwheat noodles, or 'near'."],
  ["やきにく", "yakiniku", "grilled meat", "Korean-style BBQ in Japan."],
  ["てんぷら", "tenpura", "tempura", "Battered fried food."],
  ["じゃがいも", "jagaimo", "potato", "Potato."],
  ["にんじん", "ninjin", "carrot", "Carrot."],
  ["たまねぎ", "tamanegi", "onion", "Onion."],
  ["きゅうり", "kyuuri", "cucumber", "Cucumber."],
  ["ぶたにく", "butaniku", "pork", "Pork."],
  ["ぎゅうにく", "gyuuniku", "beef", "Beef."],
  ["とりにく", "toriniku", "chicken (meat)", "Chicken meat."],
  ["しお", "shio", "salt", "Salt."],
  ["さとう", "satou", "sugar", "Sugar."],
  ["しょうゆ", "shouyu", "soy sauce", "Soy sauce."],
  ["みずうみ", "mizuumi", "lake", "Lake."],
  ["もり", "mori", "forest", "Forest."],
  ["はたけ", "hatake", "field", "Farm field."],
  ["にわ", "niwa", "garden", "Garden / yard."],
  ["はなび", "hanabi", "fireworks", "Fireworks."],
  ["こおり", "koori", "ice", "Ice."],
  ["うわぎ", "uwagi", "jacket / outerwear", "Outer clothing."],
  ["ぼうし", "boushi", "hat", "Hat / cap."],
  ["てぶくろ", "tebukuro", "gloves", "Gloves."],
  ["くつした", "kutsushita", "socks", "Socks."],
  ["くすり", "kusuri", "medicine", "Medicine."],
  ["ねつ", "netsu", "fever / heat", "Body fever."],
  ["せき", "seki", "cough", "Cough."],
  ["いたみ", "itami", "pain", "Pain / ache."],
  ["けが", "kega", "injury", "Injury."],
  ["うんどう", "undou", "exercise", "Physical exercise."],
  ["さんぽ", "sanpo", "walk / stroll", "A stroll."],
  ["りょうり", "ryouri", "cooking / cuisine", "Cooking."],
  ["せんたく", "sentaku", "laundry / choice", "Washing clothes (or choice)."],
  ["そうじ", "souji", "cleaning", "House cleaning."],
  ["かいもの", "kaimono", "shopping", "Shopping."],
  ["りょうしん", "ryoushin", "parents", "Mother and father."],
  ["そふ", "sofu", "grandfather", "Grandfather."],
  ["そぼ", "sobo", "grandmother", "Grandmother."],
  ["まご", "mago", "grandchild", "Grandchild."],
  ["ゆうじん", "yuujin", "friend (formal)", "More formal than tomodachi."],
  ["いしゃ", "isha", "doctor", "Medical doctor."],
  ["かんごし", "kangoshi", "nurse", "Nurse."],
  ["けいさつ", "keisatsu", "police", "Police."],
  ["よやく", "yoyaku", "reservation", "Booking / reservation."],
  ["りょうきん", "ryoukin", "fee / charge", "Price charged."],
  ["わりびき", "waribiki", "discount", "Discount."],
  ["むりょう", "muryou", "free (no cost)", "No charge."],
  ["あんない", "annai", "guidance / information", "Directions or guide."],
  ["せつめい", "setsumei", "explanation", "Explanation."],
  ["しょうかい", "shoukai", "introduction", "Introducing someone."],
  ["けいかく", "keikaku", "plan", "A plan."],
  ["よてい", "yotei", "schedule / plan", "What you plan to do."],
  ["ほうこく", "houkoku", "report", "A report."],
  ["れんらく", "renraku", "contact", "Getting in touch."],
  ["かいぎ", "kaigi", "meeting", "Business meeting."],
  ["せいこう", "seikou", "success", "Success."],
  ["しっぱい", "shippai", "failure", "Failure."],
  ["けいけん", "keiken", "experience", "Experience."],
  ["もくひょう", "mokuhyou", "goal", "Target / goal."],
  ["どりょく", "doryoku", "effort", "Hard work / effort."],
  ["ちゅうい", "chuui", "attention / caution", "Be careful."],
  ["あんぜん", "anzen", "safety", "Safe / safety."],
  ["きけん", "kiken", "danger", "Danger."],
  ["しゃかい", "shakai", "society", "Society."],
  ["ぶんか", "bunka", "culture", "Culture."],
  ["れきし", "rekishi", "history", "History."],
  ["しぜん", "shizen", "nature", "Nature."],
  ["かんきょう", "kankyou", "environment", "Environment."],
  ["じしん", "jishin", "earthquake / confidence", "Context decides."],
  ["たいふう", "taifuu", "typhoon", "Typhoon."],
  ["じこ", "jiko", "accident", "Accident."],
  ["しんごう", "shingou", "traffic light", "Signal / light."],
  ["しゅっぱつ", "shuppatsu", "departure", "Leaving / departure."],
  ["とうちゃく", "touchaku", "arrival", "Arrival."],
  ["のりかえ", "norikae", "transfer (transit)", "Change trains."],
  ["おくれ", "okure", "delay", "Being late / delay."],
  ["しゅくはく", "shukuhaku", "lodging", "Staying overnight."],
  ["みやげ", "miyage", "souvenir", "Gift from a trip."],
  ["かんこう", "kankou", "sightseeing", "Tourism."],
  ["おてら", "otera", "temple", "Buddhist temple."],
  ["じんじゃ", "jinja", "shrine", "Shinto shrine."],
  ["おまつり", "omatsuri", "festival", "Festival."],
  ["けっこん", "kekkon", "marriage", "Marriage."],
  ["そつぎょう", "sotsugyou", "graduation", "Graduation."],
  ["めんせつ", "mensetsu", "interview", "Job interview."],
  ["きゅうりょう", "kyuuryou", "salary", "Pay."],
  ["ぜいきん", "zeikin", "tax", "Tax."],
  ["ほけん", "hoken", "insurance", "Insurance."],
  ["ちょきん", "chokin", "savings", "Saved money."],
  ["げんきん", "genkin", "cash", "Cash money."],
  ["うりあげ", "uriage", "sales / revenue", "Store sales."],
  ["ししゅつ", "shishutsu", "expense", "Spending."],
  ["しゅうにゅう", "shuunyuu", "income", "Income."],
  ["じむしょ", "jimusho", "office", "Office room."],
  ["うけつけ", "uketsuke", "reception desk", "Front desk."],
  ["じんじ", "jinji", "human resources", "HR."],
  ["えいぎょう", "eigyou", "sales (department)", "Sales work."],
  ["ひょうか", "hyouka", "evaluation", "Assessment."],
  ["いけん", "iken", "opinion", "Opinion."],
  ["さんせい", "sansei", "agreement", "I agree."],
  ["はんたい", "hantai", "opposition", "I disagree / against."],
  ["けんこう", "kenkou", "health", "Health."],
  ["えいよう", "eiyou", "nutrition", "Nutrition."],
  ["べんとう", "bentou", "boxed lunch", "Bento box."],
  ["おせんべい", "osenbei", "rice cracker", "Japanese cracker."],
  ["もち", "mochi", "rice cake", "Mochi."],
  ["だんご", "dango", "dumpling skewer", "Sweet dumplings."],
  ["しょうせつ", "shousetsu", "novel", "Novel."],
  ["ものがたり", "monogatari", "story", "Story / tale."],
  ["ニュース", "nyuusu", "news", "Often written in katakana; hiragana form rare."],
  ["でんわばんごう", "denwabangou", "phone number", "Telephone number."],
  ["じゅうしょ", "juusho", "address", "Home address."],
  ["ゆうびんばんごう", "yuubinbangou", "postal code", "Zip code."],
  ["こくせき", "kokuseki", "nationality", "Nationality."],
  ["りゅうがく", "ryuugaku", "study abroad", "Studying overseas."],
  ["しんさつ", "shinsatsu", "medical exam", "Doctor visit."],
  ["たいおん", "taion", "body temperature", "Temperature."],
  ["たいじゅう", "taijuu", "body weight", "Weight."],
  ["しんちょう", "shinchou", "height", "How tall someone is."],
  ["てあらい", "tearai", "hand washing / restroom", "Washing hands."],
  ["うんてん", "unten", "driving", "Driving a vehicle."],
  ["みちあんない", "michiannai", "directions", "Showing the way."],
  ["ちず", "chizu", "map", "Map."],
  ["きょり", "kyori", "distance", "Distance."],
  ["へんきん", "henkin", "refund", "Money returned."],
  ["りょうしゅうしょ", "ryoushuusho", "receipt", "Proof of payment."],
  ["ねびき", "nebiki", "price cut", "Discounting the price."],
  ["ざんぎょう", "zangyou", "overtime", "Working late."],
  ["しゅっちょう", "shucchou", "business trip", "Work travel."],
  ["のみかい", "nomikai", "drinks gathering", "After-work drinks."],
  ["おいわい", "oiwai", "celebration", "Celebrating something."],
  ["おれい", "orei", "thanks gift", "Token of gratitude."],
  ["がんばって", "ganbatte", "do your best", "Encouragement."],
  ["おだいじに", "odaijini", "take care (when ill)", "Said to a sick person."],
  ["またね", "matane", "see you", "Casual goodbye."],
  ["おひさしぶり", "ohisashiburi", "long time no see", "After a long gap."],
  ["かしこまりました", "kashikomarimashita", "certainly (polite)", "Staff reply: understood."],
  ["しょうちしました", "shouchishimashita", "understood (polite)", "I understand."],
  ["たすけて", "tasukete", "help me", "Call for help."],
  ["どういたしまして", "douitashimashite", "you're welcome", "Reply to thanks."],
  ["きにしないで", "kinishinaide", "don't worry about it", "It's fine."],
  ["おうえん", "ouen", "support / cheering", "Cheering someone on."],
  ["ひとつ", "hitotsu", "one (thing)", "Counter for things."],
  ["ふたつ", "futatsu", "two (things)", "Two items."],
  ["みっつ", "mittsu", "three (things)", "Three items."],
  ["よっつ", "yottsu", "four (things)", "Four items."],
  ["いつつ", "itsutsu", "five (things)", "Five items."],
  ["むっつ", "muttsu", "six (things)", "Six items."],
  ["ななつ", "nanatsu", "seven (things)", "Seven items."],
  ["やっつ", "yattsu", "eight (things)", "Eight items."],
  ["ここのつ", "kokonotsu", "nine (things)", "Nine items."],
  ["とお", "too", "ten (things)", "Ten items."],
  ["いち", "ichi", "one", "Number one."],
  ["に", "ni", "two", "Number two (also particle ni)."],
  ["さん", "san", "three", "Number three."],
  ["よん", "yon", "four", "Number four (common reading)."],
  ["ご", "go", "five", "Number five."],
  ["ろく", "roku", "six", "Number six."],
  ["なな", "nana", "seven", "Number seven."],
  ["はち", "hachi", "eight", "Number eight."],
  ["きゅう", "kyuu", "nine", "Number nine."],
  ["じゅう", "juu", "ten", "Number ten."],
  ["ひゃく", "hyaku", "hundred", "100."],
  ["せん", "sen", "thousand", "1000."],
  ["まん", "man", "ten thousand", "10,000."],
  ["えん", "en", "yen", "Japanese currency."],
  ["はん", "han", "half", "Half past / half."],
  ["じ", "ji", "o'clock", "Hour marker."],
  ["ふん", "fun", "minute", "Minute (also pun)."],
  ["びょう", "byou", "second", "Second of time."],
  ["おはようごぜいます", "ohayougozaimasu", "good morning (polite)", "Polite morning hello."],
  ["ありがとうございます", "arigatougozaimasu", "thank you (polite)", "Polite thanks."],
  ["いってらっしゃいませ", "itterasshaimase", "see you (shop)", "Staff send-off."],
  ["いらっしゃいませ", "irasshaimase", "welcome (to a shop)", "Shop greeting."],
  ["おねがいします", "onegaishimasu", "please", "Polite request."],
  ["しつれいします", "shitsureishimasu", "excuse me (entering)", "Polite interruption."],
  ["ごめんください", "gomenkudasai", "hello? (at door)", "Calling at someone's door."],
  ["おじゃまします", "ojamashimasu", "excuse the intrusion", "Entering someone's home."],
  ["いただきます前", "itadakimasumae", "before eating ritual", "Skip invalid."],
];

// Extra real vocab batches (romaji must be Latin)
const EXTRA = [
  ["あかちゃん", "akachan", "baby", "Infant."],
  ["おきゃくさん", "okyakusan", "customer / guest", "Customer."],
  ["てんいん", "ten'in", "store clerk", "Shop staff."],
  ["うんてんしゅ", "untenshu", "driver", "Vehicle driver."],
  ["エンジニア", "enjinia", "engineer", "Skip: katakana."],
  ["かいがい", "kaigai", "overseas", "Abroad."],
  ["こくない", "kokunai", "domestic", "Inside the country."],
  ["やくそく", "yakusoku", "promise", "Promise / appointment."],
  ["じゆう", "jiyuu", "freedom", "Freedom."],
  ["へいわ", "heiwa", "peace", "Peace."],
  ["あい", "ai", "love", "Love."],
  ["ゆめ", "yume", "dream", "Dream."],
  ["きぼう", "kibou", "hope", "Hope."],
  ["しあわせ", "shiawase", "happiness", "Happy state."],
  ["かなしい", "kanashii", "sad", "Sad feeling."],
  ["うれしい", "ureshii", "glad / happy", "Happy about something."],
  ["おもしろがる", "omoshirogaru", "to find amusing", "Find something funny."],
  ["たのしい", "tanoshii", "fun", "Enjoyable."],
  ["つまらない", "tsumaranai", "boring", "Not interesting."],
  ["すばらしい", "subarashii", "wonderful", "Amazing."],
  ["たいせつ", "taisetsu", "important", "Important / precious."],
  ["ひつよう", "hitsuyou", "necessary", "Needed."],
  ["べんり", "benri", "convenient", "Handy."],
  ["ふべん", "fuben", "inconvenient", "Not handy."],
  ["ゆうめい", "yuumei", "famous", "Well-known."],
  ["じょうず", "jouzu", "skilled", "Good at."],
  ["へた", "heta", "unskilled", "Bad at."],
  ["おなじ", "onaji", "same", "Same."],
  ["ちがう", "chigau", "different / wrong", "Not the same."],
  ["はじめ", "hajime", "beginning", "Start."],
  ["おわり", "owari", "end", "Finish."],
  ["さいしょ", "saisho", "first", "The first."],
  ["さいご", "saigo", "last", "The last."],
  ["つぎ", "tsugi", "next", "Next."],
  ["まえの", "maeno", "previous", "The one before."],
  ["りゆう", "riyuu", "reason", "Reason why."],
  ["もんだい", "mondai", "problem / question", "Issue or quiz item."],
  ["こたえ", "kotae", "answer", "Answer."],
  ["しつもん", "shitsumon", "question", "A question."],
  ["れい", "rei", "example", "Example."],
  ["ぶんぽう", "bunpou", "grammar", "Grammar."],
  ["はつおん", "hatsuon", "pronunciation", "How it sounds."],
  ["しゅうかん", "shuukan", "habit / week", "Habit or a week."],
  ["きせつ", "kisetsu", "season", "Season of the year."],
  ["きおん", "kion", "air temperature", "How warm/cold it is."],
  ["しつど", "shitsudo", "humidity", "Humidity."],
  ["かさなる", "kasanaru", "to overlap", "Stack / overlap."],
  ["ひらく", "hiraku", "to open", "Open something."],
  ["しめる", "shimeru", "to close", "Close something."],
  ["つける", "tsukeru", "to turn on / attach", "Switch on or attach."],
  ["けす", "kesu", "to turn off / erase", "Switch off or erase."],
  ["あける", "akeru", "to open", "Open a door/window."],
  ["おす", "osu", "to push", "Push."],
  ["ひく", "hiku", "to pull / play (instrument)", "Pull or play piano."],
  ["のる", "noru", "to ride / board", "Get on a vehicle."],
  ["おりる", "oriru", "to get off / go down", "Exit a vehicle."],
  ["はいる", "hairu", "to enter", "Go in."],
  ["でる", "deru", "to leave / exit", "Go out."],
  ["つく", "tsuku", "to arrive", "Arrive."],
  ["とまる", "tomaru", "to stop / stay overnight", "Stop or lodge."],
  ["とめる", "tomeru", "to stop (something)", "Make something stop."],
  ["かかる", "kakaru", "to take (time/money)", "It takes…"],
  ["ある", "aru", "to exist (things)", "There is (inanimate)."],
  ["いる", "iru", "to exist (people/animals)", "There is (animate)."],
  ["する", "suru", "to do", "Do."],
  ["なる", "naru", "to become", "Become."],
  ["できる", "dekiru", "can do / be made", "Ability or completion."],
  ["あげる", "ageru", "to give (upward)", "Give to someone."],
  ["もらう", "morau", "to receive", "Receive."],
  ["くれる", "kureru", "to give (to me)", "Someone gives to me."],
  ["かす", "kasu", "to lend", "Lend."],
  ["かりる", "kariru", "to borrow", "Borrow."],
  ["かえす", "kaesu", "to return (something)", "Give back."],
  ["おくる", "okuru", "to send / see off", "Send or escort."],
  ["とどく", "todoku", "to be delivered", "Arrive (package)."],
  ["とどける", "todokeru", "to deliver", "Deliver."],
  ["あう", "au", "to meet", "Meet someone."],
  ["よぶ", "yobu", "to call", "Call / invite."],
  ["しめる2", "shimeru2", "dup", "skip"],
];

function toEntry([word, reading, meaningEn, explanationEn], prefix, i) {
  if (!/^[\u3040-\u309Fー]+$/.test(word)) return null;
  if (!isLatinRomaji(reading)) return null;
  if (looksLikeFillerMeaning(meaningEn)) return null;
  if (/skip|dup/i.test(meaningEn) || /skip/i.test(explanationEn)) return null;
  return {
    id: `${prefix}-${i}`,
    word,
    reading: reading.toLowerCase(),
    meaningEn,
    explanationEn,
    ttsText: word,
    ttsLang: "ja-JP",
  };
}

export function buildHiragana(need) {
  const raw = [...CURATED, ...EXTRA, ...MORE_HIRAGANA];
  const out = [];
  const seen = new Set();
  for (let i = 0; i < raw.length; i += 1) {
    const entry = toEntry(raw[i], "h", i);
    if (!entry) continue;
    if (seen.has(entry.word)) continue;
    seen.add(entry.word);
    out.push(entry);
    if (out.length >= need) break;
  }
  if (out.length < 100) {
    throw new Error(`Hiragana real vocab too small: ${out.length}`);
  }
  return out;
}
