import { isLatinRomaji, looksLikeFillerMeaning } from "./kana-romaji.mjs";
import { MORE_KANJI } from "./more-vocab.mjs";

/** Real kanji words: [word, romaji, english, explanation] */
const CURATED = [
  ["山", "yama", "mountain", "Nature kanji."],
  ["川", "kawa", "river", "River."],
  ["日", "hi / nichi", "sun / day", "Sun or day."],
  ["月", "tsuki / getsu", "moon / month", "Moon or month."],
  ["人", "hito / jin", "person", "Person."],
  ["水", "mizu", "water", "Water."],
  ["火", "hi", "fire", "Fire."],
  ["木", "ki", "tree", "Tree."],
  ["金", "kane / kin", "gold / money", "Gold or money."],
  ["土", "tsuchi", "earth / soil", "Soil."],
  ["大", "oo / dai", "big", "Big."],
  ["小", "chii / shou", "small", "Small."],
  ["上", "ue", "up / above", "Above."],
  ["下", "shita", "down / below", "Below."],
  ["中", "naka", "middle / inside", "Inside."],
  ["一", "ichi", "one", "Number 1."],
  ["二", "ni", "two", "Number 2."],
  ["三", "san", "three", "Number 3."],
  ["四", "yon / shi", "four", "Number 4."],
  ["五", "go", "five", "Number 5."],
  ["六", "roku", "six", "Number 6."],
  ["七", "nana / shichi", "seven", "Number 7."],
  ["八", "hachi", "eight", "Number 8."],
  ["九", "kyuu / ku", "nine", "Number 9."],
  ["十", "juu", "ten", "Number 10."],
  ["百", "hyaku", "hundred", "100."],
  ["千", "sen", "thousand", "1000."],
  ["万", "man", "ten thousand", "10,000."],
  ["円", "en", "yen", "Japanese currency."],
  ["日本", "nihon", "Japan", "Japan."],
  ["学校", "gakkou", "school", "School."],
  ["学生", "gakusei", "student", "Student."],
  ["先生", "sensei", "teacher", "Teacher."],
  ["大学", "daigaku", "university", "University."],
  ["高校", "koukou", "high school", "High school."],
  ["今日", "kyou", "today", "Today."],
  ["明日", "ashita", "tomorrow", "Tomorrow."],
  ["昨日", "kinou", "yesterday", "Yesterday."],
  ["毎日", "mainichi", "every day", "Daily."],
  ["毎週", "maishuu", "every week", "Every week."],
  ["毎月", "maitsuki", "every month", "Every month."],
  ["毎年", "maitoshi", "every year", "Every year."],
  ["時間", "jikan", "time", "Time."],
  ["今", "ima", "now", "Now."],
  ["年", "toshi / nen", "year", "Year."],
  ["午前", "gozen", "a.m.", "Morning hours."],
  ["午後", "gogo", "p.m.", "Afternoon hours."],
  ["天気", "tenki", "weather", "Weather."],
  ["雨", "ame", "rain", "Rain."],
  ["雪", "yuki", "snow", "Snow."],
  ["風", "kaze", "wind", "Wind."],
  ["空", "sora", "sky", "Sky."],
  ["車", "kuruma", "car", "Car."],
  ["電車", "densha", "train", "Train."],
  ["駅", "eki", "station", "Station."],
  ["空港", "kuukou", "airport", "Airport."],
  ["飛行機", "hikouki", "airplane", "Plane."],
  ["自転車", "jitensha", "bicycle", "Bike."],
  ["自動車", "jidousha", "automobile", "Automobile."],
  ["道", "michi", "road / way", "Road."],
  ["右", "migi", "right", "Right."],
  ["左", "hidari", "left", "Left."],
  ["東", "higashi", "east", "East."],
  ["西", "nishi", "west", "West."],
  ["南", "minami", "south", "South."],
  ["北", "kita", "north", "North."],
  ["口", "kuchi", "mouth / opening", "Mouth or exit."],
  ["目", "me", "eye", "Eye."],
  ["耳", "mimi", "ear", "Ear."],
  ["手", "te", "hand", "Hand."],
  ["足", "ashi", "foot / leg", "Foot."],
  ["力", "chikara", "power / strength", "Strength."],
  ["男", "otoko", "man", "Man."],
  ["女", "onna", "woman", "Woman."],
  ["子", "ko", "child", "Child."],
  ["父", "chichi", "father", "Father (humble)."],
  ["母", "haha", "mother", "Mother (humble)."],
  ["友", "tomo", "friend", "Friend stem."],
  ["名前", "namae", "name", "Name."],
  ["何", "nani / nan", "what", "What."],
  ["行く", "iku", "to go", "Go."],
  ["来る", "kuru", "to come", "Come."],
  ["見る", "miru", "to see", "See."],
  ["聞く", "kiku", "to hear / ask", "Hear."],
  ["言う", "iu", "to say", "Say."],
  ["話す", "hanasu", "to speak", "Talk."],
  ["読む", "yomu", "to read", "Read."],
  ["書く", "kaku", "to write", "Write."],
  ["食べる", "taberu", "to eat", "Eat."],
  ["飲む", "nomu", "to drink", "Drink."],
  ["買う", "kau", "to buy", "Buy."],
  ["売る", "uru", "to sell", "Sell."],
  ["立つ", "tatsu", "to stand", "Stand."],
  ["休む", "yasumu", "to rest", "Rest."],
  ["入る", "hairu", "to enter", "Enter."],
  ["出る", "deru", "to exit", "Leave."],
  ["開ける", "akeru", "to open", "Open."],
  ["閉める", "shimeru", "to close", "Close."],
  ["新しい", "atarashii", "new", "New."],
  ["古い", "furui", "old", "Old."],
  ["高い", "takai", "high / expensive", "High or pricey."],
  ["安い", "yasui", "cheap", "Cheap."],
  ["長い", "nagai", "long", "Long."],
  ["短い", "mijikai", "short", "Short."],
  ["多い", "ooi", "many", "Many."],
  ["少ない", "sukunai", "few", "Few."],
  ["好き", "suki", "like", "Like."],
  ["近い", "chikai", "near", "Near."],
  ["遠い", "tooi", "far", "Far."],
  ["強い", "tsuyoi", "strong", "Strong."],
  ["弱い", "yowai", "weak", "Weak."],
  ["明るい", "akarui", "bright", "Bright."],
  ["暗い", "kurai", "dark", "Dark."],
  ["白い", "shiroi", "white", "White."],
  ["黒い", "kuroi", "black", "Black."],
  ["赤い", "akai", "red", "Red."],
  ["青い", "aoi", "blue", "Blue."],
  ["花", "hana", "flower", "Flower."],
  ["森", "mori", "forest", "Forest."],
  ["林", "hayashi", "woods", "Woods."],
  ["田", "ta", "rice field", "Rice field."],
  ["石", "ishi", "stone", "Stone."],
  ["町", "machi", "town", "Town."],
  ["村", "mura", "village", "Village."],
  ["市", "shi", "city", "City."],
  ["国", "kuni", "country", "Country."],
  ["語", "go", "language", "Language suffix."],
  ["英語", "eigo", "English", "English language."],
  ["日本語", "nihongo", "Japanese", "Japanese language."],
  ["中国", "chuugoku", "China", "China."],
  ["韓国", "kankoku", "Korea", "Korea."],
  ["会社", "kaisha", "company", "Company."],
  ["仕事", "shigoto", "work / job", "Job."],
  ["電話", "denwa", "telephone", "Phone."],
  ["電気", "denki", "electricity", "Electricity."],
  ["病気", "byouki", "illness", "Sick."],
  ["病院", "byouin", "hospital", "Hospital."],
  ["薬", "kusuri", "medicine", "Medicine."],
  ["体", "karada", "body", "Body."],
  ["心", "kokoro", "heart / mind", "Mind."],
  ["元気", "genki", "healthy / energetic", "Well."],
  ["安心", "anshin", "relief", "Relief."],
  ["心配", "shinpai", "worry", "Worry."],
  ["質問", "shitsumon", "question", "Question."],
  ["問題", "mondai", "problem", "Problem."],
  ["答え", "kotae", "answer", "Answer."],
  ["試験", "shiken", "exam", "Exam."],
  ["宿題", "shukudai", "homework", "Homework."],
  ["勉強", "benkyou", "study", "Study."],
  ["教室", "kyoushitsu", "classroom", "Classroom."],
  ["図書館", "toshokan", "library", "Library."],
  ["銀行", "ginkou", "bank", "Bank."],
  ["郵便局", "yuubinkyoku", "post office", "Post office."],
  ["公園", "kouen", "park", "Park."],
  ["映画", "eiga", "movie", "Movie."],
  ["音楽", "ongaku", "music", "Music."],
  ["写真", "shashin", "photograph", "Photo."],
  ["旅行", "ryokou", "trip", "Travel."],
  ["家族", "kazoku", "family", "Family."],
  ["兄弟", "kyoudai", "siblings", "Brothers/sisters."],
  ["自分", "jibun", "oneself", "Self."],
  ["世界", "sekai", "world", "World."],
  ["社会", "shakai", "society", "Society."],
  ["文化", "bunka", "culture", "Culture."],
  ["歴史", "rekishi", "history", "History."],
  ["科学", "kagaku", "science", "Science."],
  ["技術", "gijutsu", "technology", "Technology."],
  ["経済", "keizai", "economy", "Economy."],
  ["政治", "seiji", "politics", "Politics."],
  ["法律", "houritsu", "law", "Law."],
  ["安全", "anzen", "safety", "Safety."],
  ["危険", "kiken", "danger", "Danger."],
  ["必要", "hitsuyou", "necessary", "Needed."],
  ["便利", "benri", "convenient", "Handy."],
  ["有名", "yuumei", "famous", "Famous."],
  ["大切", "taisetsu", "important", "Important."],
  ["上手", "jouzu", "skilled", "Good at."],
  ["下手", "heta", "unskilled", "Bad at."],
  ["同じ", "onaji", "same", "Same."],
  ["違う", "chigau", "different", "Different."],
  ["初め", "hajime", "beginning", "Start."],
  ["終わり", "owari", "end", "End."],
  ["最初", "saisho", "first", "First."],
  ["最後", "saigo", "last", "Last."],
  ["次回", "jikai", "next time", "Next time."],
  ["前回", "zenkai", "last time", "Previous time."],
  ["以上", "ijou", "or more / that's all", "Above that amount."],
  ["以下", "ika", "or less", "Below that amount."],
  ["以外", "igai", "except", "Except."],
  ["以内", "inai", "within", "Within."],
  ["東京", "toukyou", "Tokyo", "Capital city."],
  ["大阪", "oosaka", "Osaka", "Major city."],
  ["京都", "kyouto", "Kyoto", "Historic city."],
  ["北海道", "hokkaidou", "Hokkaido", "Northern island."],
  ["九州", "kyuushuu", "Kyushu", "Southern island."],
  ["外国", "gaikoku", "foreign country", "Overseas country."],
  ["外国人", "gaikokujin", "foreigner", "Foreign person."],
  ["日本人", "nihonjin", "Japanese person", "Japanese national."],
  ["大人", "otona", "adult", "Adult."],
  ["子供", "kodomo", "child", "Child."],
  ["女性", "josei", "woman", "Woman (formal)."],
  ["男性", "dansei", "man", "Man (formal)."],
  ["先生方", "senseigata", "teachers (honorific)", "Plural respectful."],
  ["会社員", "kaishain", "company employee", "Office worker."],
  ["店員", "ten'in", "store clerk", "Shop staff."],
  ["医者", "isha", "doctor", "Doctor."],
  ["看護師", "kangoshi", "nurse", "Nurse."],
  ["警察", "keisatsu", "police", "Police."],
  ["電車賃", "denshachin", "train fare", "Train ticket cost."],
  ["切符", "kippu", "ticket", "Ticket."],
  ["入口", "iriguchi", "entrance", "Entrance."],
  ["出口", "deguchi", "exit", "Exit."],
  ["地図", "chizu", "map", "Map."],
  ["住所", "juusho", "address", "Address."],
  ["電話番号", "denwa bangou", "phone number", "Phone number."],
  ["誕生日", "tanjoubi", "birthday", "Birthday."],
  ["予約", "yoyaku", "reservation", "Reservation."],
  ["料金", "ryoukin", "fee", "Charge / fee."],
  ["割引", "waribiki", "discount", "Discount."],
  ["無料", "muryou", "free of charge", "No cost."],
  ["有料", "yuuryou", "paid / for a fee", "Costs money."],
  ["説明", "setsumei", "explanation", "Explanation."],
  ["案内", "annai", "guidance", "Guide / information."],
  ["紹介", "shoukai", "introduction", "Introduction."],
  ["計画", "keikaku", "plan", "Plan."],
  ["予定", "yotei", "schedule", "Schedule."],
  ["報告", "houkoku", "report", "Report."],
  ["連絡", "renraku", "contact", "Contact."],
  ["会議", "kaigi", "meeting", "Meeting."],
  ["成功", "seikou", "success", "Success."],
  ["失敗", "shippai", "failure", "Failure."],
  ["経験", "keiken", "experience", "Experience."],
  ["目標", "mokuhyou", "goal", "Goal."],
  ["努力", "doryoku", "effort", "Effort."],
  ["注意", "chuui", "caution", "Be careful."],
  ["自然", "shizen", "nature", "Nature."],
  ["環境", "kankyou", "environment", "Environment."],
  ["地震", "jishin", "earthquake", "Earthquake."],
  ["台風", "taifuu", "typhoon", "Typhoon."],
  ["事故", "jiko", "accident", "Accident."],
  ["信号", "shingou", "traffic light", "Signal."],
  ["出発", "shuppatsu", "departure", "Departure."],
  ["到着", "touchaku", "arrival", "Arrival."],
  ["乗換", "norikae", "transfer", "Train transfer."],
  ["遅延", "chien", "delay", "Delay."],
  ["宿泊", "shukuhaku", "lodging", "Overnight stay."],
  ["土産", "miyage", "souvenir", "Souvenir."],
  ["観光", "kankou", "sightseeing", "Sightseeing."],
  ["寺", "tera", "temple", "Temple."],
  ["神社", "jinja", "shrine", "Shrine."],
  ["祭", "matsuri", "festival", "Festival."],
  ["結婚", "kekkon", "marriage", "Marriage."],
  ["卒業", "sotsugyou", "graduation", "Graduation."],
  ["面接", "mensetsu", "interview", "Interview."],
  ["給料", "kyuuryou", "salary", "Salary."],
  ["税金", "zeikin", "tax", "Tax."],
  ["保険", "hoken", "insurance", "Insurance."],
  ["貯金", "chokin", "savings", "Savings."],
  ["現金", "genkin", "cash", "Cash."],
  ["売上", "uriage", "sales", "Sales revenue."],
  ["支出", "shishutsu", "expense", "Expense."],
  ["収入", "shuunyuu", "income", "Income."],
  ["事務所", "jimusho", "office", "Office."],
  ["受付", "uketsuke", "reception", "Front desk."],
  ["人事", "jinji", "HR", "Human resources."],
  ["営業", "eigyou", "sales (business)", "Sales department."],
  ["評価", "hyouka", "evaluation", "Evaluation."],
  ["意見", "iken", "opinion", "Opinion."],
  ["賛成", "sansei", "agreement", "Agree."],
  ["反対", "hantai", "opposition", "Disagree."],
  ["健康", "kenkou", "health", "Health."],
  ["栄養", "eiyou", "nutrition", "Nutrition."],
  ["弁当", "bentou", "boxed lunch", "Bento."],
  ["小説", "shousetsu", "novel", "Novel."],
  ["物語", "monogatari", "story", "Story."],
  ["留学", "ryuugaku", "study abroad", "Study abroad."],
  ["国籍", "kokuseki", "nationality", "Nationality."],
  ["郵便番号", "yuubin bangou", "postal code", "Zip code."],
  ["体温", "taion", "body temperature", "Temperature."],
  ["体重", "taijuu", "body weight", "Weight."],
  ["身長", "shinchou", "height", "Height."],
  ["運転", "unten", "driving", "Driving."],
  ["距離", "kyori", "distance", "Distance."],
  ["返金", "henkin", "refund", "Refund."],
  ["領収書", "ryoushuusho", "receipt", "Receipt."],
  ["残業", "zangyou", "overtime", "Overtime."],
  ["出張", "shucchou", "business trip", "Business trip."],
  ["祝", "iwai", "celebration", "Celebration stem."],
  ["礼", "rei", "thanks / bow", "Courtesy."],
  ["春", "haru", "spring", "Spring."],
  ["夏", "natsu", "summer", "Summer."],
  ["秋", "aki", "autumn", "Autumn."],
  ["冬", "fuyu", "winter", "Winter."],
  ["朝", "asa", "morning", "Morning."],
  ["昼", "hiru", "noon / daytime", "Daytime."],
  ["夜", "yoru", "night", "Night."],
  ["晩", "ban", "evening", "Evening."],
  ["週", "shuu", "week", "Week."],
  ["曜", "you", "day of week", "Weekday stem."],
  ["月曜日", "getsuyoubi", "Monday", "Monday."],
  ["火曜日", "kayoubi", "Tuesday", "Tuesday."],
  ["水曜日", "suiyoubi", "Wednesday", "Wednesday."],
  ["木曜日", "mokuyoubi", "Thursday", "Thursday."],
  ["金曜日", "kinyoubi", "Friday", "Friday."],
  ["土曜日", "doyoubi", "Saturday", "Saturday."],
  ["日曜日", "nichiyoubi", "Sunday", "Sunday."],
  ["週末", "shuumatsu", "weekend", "Weekend."],
  ["色", "iro", "color", "Color."],
  ["青", "ao", "blue", "Blue."],
  ["赤", "aka", "red", "Red."],
  ["白", "shiro", "white", "White."],
  ["黒", "kuro", "black", "Black."],
  ["黄色", "kiiro", "yellow", "Yellow."],
  ["緑", "midori", "green", "Green."],
  ["家", "ie / uchi", "house / home", "Home."],
  ["部屋", "heya", "room", "Room."],
  ["窓", "mado", "window", "Window."],
  ["机", "tsukue", "desk", "Desk."],
  ["椅子", "isu", "chair", "Chair."],
  ["本", "hon", "book", "Book."],
  ["新聞", "shinbun", "newspaper", "Newspaper."],
  ["辞書", "jisho", "dictionary", "Dictionary."],
  ["手紙", "tegami", "letter", "Letter."],
  ["財布", "saifu", "wallet", "Wallet."],
  ["傘", "kasa", "umbrella", "Umbrella."],
  ["靴", "kutsu", "shoes", "Shoes."],
  ["服", "fuku", "clothes", "Clothes."],
  ["鞄", "kaban", "bag", "Bag."],
  ["眼鏡", "megane", "glasses", "Glasses."],
  ["時計", "tokei", "clock / watch", "Clock."],
  ["鍵", "kagi", "key", "Key."],
  ["海", "umi", "sea", "Sea."],
  ["魚", "sakana", "fish", "Fish."],
  ["肉", "niku", "meat", "Meat."],
  ["野菜", "yasai", "vegetable", "Vegetable."],
  ["果物", "kudamono", "fruit", "Fruit."],
  ["卵", "tamago", "egg", "Egg."],
  ["牛乳", "gyuunyuu", "milk", "Milk."],
  ["茶", "cha", "tea", "Tea."],
  ["飯", "meshi / han", "rice / meal", "Meal stem."],
  ["朝食", "choushoku", "breakfast", "Breakfast."],
  ["昼食", "chuushoku", "lunch", "Lunch."],
  ["夕食", "yuushoku", "dinner", "Dinner."],
  ["料理", "ryouri", "cooking", "Cooking."],
  ["洗濯", "sentaku", "laundry", "Laundry."],
  ["掃除", "souji", "cleaning", "Cleaning."],
  ["買い物", "kaimono", "shopping", "Shopping."],
  ["両親", "ryoushin", "parents", "Parents."],
  ["祖父", "sofu", "grandfather", "Grandfather."],
  ["祖母", "sobo", "grandmother", "Grandmother."],
  ["友達", "tomodachi", "friend", "Friend."],
  ["約束", "yakusoku", "promise", "Promise."],
  ["自由", "jiyuu", "freedom", "Freedom."],
  ["平和", "heiwa", "peace", "Peace."],
  ["愛", "ai", "love", "Love."],
  ["夢", "yume", "dream", "Dream."],
  ["希望", "kibou", "hope", "Hope."],
  ["幸せ", "shiawase", "happiness", "Happiness."],
  ["楽しい", "tanoshii", "fun", "Fun."],
  ["嬉しい", "ureshii", "glad", "Glad."],
  ["悲しい", "kanashii", "sad", "Sad."],
  ["面白い", "omoshiroi", "interesting", "Interesting."],
  ["難しい", "muzukashii", "difficult", "Difficult."],
  ["易しい", "yasashii", "easy", "Easy (reading)."],
  ["早い", "hayai", "early / fast", "Early or fast."],
  ["遅い", "osoi", "late / slow", "Late or slow."],
  ["暑い", "atsui", "hot (weather)", "Hot weather."],
  ["寒い", "samui", "cold (weather)", "Cold weather."],
];

function toEntry([word, reading, meaningEn, explanationEn], i) {
  if (!/[\u4e00-\u9faf]/.test(word)) return null;
  const normalized = reading
    .toLowerCase()
    .replace(/・/g, " / ")
    .replace(/\s+/g, " ")
    .trim();
  if (!isLatinRomaji(normalized.replace(/\//g, ""))) return null;
  if (looksLikeFillerMeaning(meaningEn)) return null;
  if (/skip|dup/i.test(meaningEn + explanationEn)) return null;
  return {
    id: `c-${i}`,
    word,
    reading: normalized,
    meaningEn,
    explanationEn,
    ttsText: word,
    ttsLang: "ja-JP",
  };
}

export function buildKanji(need) {
  const raw = [...CURATED, ...MORE_KANJI];
  const out = [];
  const seen = new Set();
  for (let i = 0; i < raw.length; i += 1) {
    const entry = toEntry(raw[i], i);
    if (!entry) continue;
    if (seen.has(entry.word)) continue;
    seen.add(entry.word);
    out.push(entry);
    if (out.length >= need) break;
  }
  if (out.length < 100) {
    throw new Error(`Kanji real vocab too small: ${out.length}`);
  }
  return out;
}
