import { isLatinRomaji, looksLikeFillerMeaning } from "./kana-romaji.mjs";
import { MORE_KATAKANA } from "./more-vocab.mjs";

/** Real katakana loanwords / modern vocab: [word, romaji, english, explanation] */
const CURATED = [
  ["コーヒー", "koohii", "coffee", "Drink loanword. ー lengthens the vowel."],
  ["パン", "pan", "bread", "From Portuguese; everyday food."],
  ["タクシー", "takushii", "taxi", "Transport loanword."],
  ["バス", "basu", "bus", "Short travel word."],
  ["ホテル", "hoteru", "hotel", "Lodging loanword."],
  ["カメラ", "kamera", "camera", "Device loanword."],
  ["テレビ", "terebi", "television / TV", "Shortened TV word."],
  ["スマホ", "sumaho", "smartphone", "Casual short form of スマートフォン."],
  ["メニュー", "menyuu", "menu", "Restaurant list."],
  ["アイス", "aisu", "ice cream / ice", "Often means ice cream."],
  ["ジュース", "juusu", "juice", "Drink loanword."],
  ["サラダ", "sarada", "salad", "Food loanword."],
  ["トイレ", "toire", "restroom", "Essential travel word."],
  ["エレベーター", "erebeetaa", "elevator", "Building loanword."],
  ["インターネット", "intaanetto", "internet", "Tech loanword."],
  ["ノート", "nooto", "notebook", "Usually a paper notebook in Japanese."],
  ["ペン", "pen", "pen", "Stationery."],
  ["ドア", "doa", "door", "Western-style door."],
  ["アパート", "apaato", "apartment", "Housing loanword."],
  ["チーズ", "chiizu", "cheese", "Food loanword."],
  ["レストラン", "resutoran", "restaurant", "Dining place."],
  ["スーパー", "suupaa", "supermarket", "Grocery store."],
  ["コンビニ", "konbini", "convenience store", "Short for convenience store."],
  ["パソコン", "pasokon", "PC / computer", "Personal computer."],
  ["アプリ", "apuri", "app", "Smartphone application."],
  ["メール", "meeru", "email", "Electronic mail."],
  ["ボタン", "botan", "button", "Button."],
  ["サイズ", "saizu", "size", "Clothing or object size."],
  ["サービス", "saabisu", "service", "Customer service."],
  ["セール", "seeru", "sale", "Discount sale."],
  ["チケット", "chiketto", "ticket", "Event or travel ticket."],
  ["パスポート", "pasupooto", "passport", "Travel ID."],
  ["ビザ", "biza", "visa", "Entry permission."],
  ["チェックイン", "chekkuin", "check-in", "Hotel or airport check-in."],
  ["チェックアウト", "chekkuauto", "check-out", "Leaving a hotel."],
  ["キャンセル", "kyanseru", "cancellation", "Cancel a booking."],
  ["クレジットカード", "kurejitto kaado", "credit card", "Payment card."],
  ["レシート", "reshiito", "receipt", "Payment receipt."],
  ["バッグ", "baggu", "bag", "Bag."],
  ["シャツ", "shatsu", "shirt", "Shirt."],
  ["スカート", "sukaato", "skirt", "Skirt."],
  ["パンツ", "pantsu", "pants / underwear", "Context decides."],
  ["スニーカー", "suniikaa", "sneakers", "Sport shoes."],
  ["ジャケット", "jaketto", "jacket", "Jacket."],
  ["コート", "kooto", "coat", "Coat."],
  ["マフラー", "mafuraa", "scarf", "Winter scarf."],
  ["ネクタイ", "nekutai", "necktie", "Tie."],
  ["スーツ", "suutsu", "suit", "Business suit."],
  ["ワンピース", "wanpiisu", "dress", "One-piece dress."],
  ["サンダル", "sandaru", "sandals", "Open shoes."],
  ["ブーツ", "buutsu", "boots", "Boots."],
  ["キャップ", "kyappu", "cap", "Cap hat."],
  ["ヘルメット", "herumetto", "helmet", "Safety helmet."],
  ["スポーツ", "supootsu", "sports", "Sports."],
  ["サッカー", "sakkaa", "soccer", "Football (soccer)."],
  ["テニス", "tenisu", "tennis", "Tennis."],
  ["バスケ", "basuke", "basketball", "Short for basketball."],
  ["ゴルフ", "gorufu", "golf", "Golf."],
  ["スキー", "sukii", "ski / skiing", "Skiing."],
  ["スノーボード", "sunooboodo", "snowboard", "Snowboarding."],
  ["マラソン", "marason", "marathon", "Long race."],
  ["ジム", "jimu", "gym", "Fitness gym."],
  ["ヨガ", "yoga", "yoga", "Yoga."],
  ["トレーニング", "toreeningu", "training", "Workout / training."],
  ["ダイエット", "daietto", "diet", "Dieting."],
  ["カロリー", "karorii", "calorie", "Calories."],
  ["ビタミン", "bitamin", "vitamin", "Vitamin."],
  ["エネルギー", "enerugii", "energy", "Energy."],
  ["ストレス", "sutoresu", "stress", "Stress."],
  ["リラックス", "rirakkusu", "relax", "Relax."],
  ["マッサージ", "massaaji", "massage", "Massage."],
  ["シャワー", "shawaa", "shower", "Shower."],
  ["シャンプー", "shanpuu", "shampoo", "Shampoo."],
  ["タオル", "taoru", "towel", "Towel."],
  ["ソープ", "soopu", "soap", "Soap."],
  ["ティッシュ", "tisshu", "tissue", "Facial tissue."],
  ["マスク", "masuku", "mask", "Face mask."],
  ["アルコール", "arukooru", "alcohol", "Drink or sanitizer."],
  ["ビール", "biiru", "beer", "Beer."],
  ["ワイン", "wain", "wine", "Wine."],
  ["カクテル", "kakuteru", "cocktail", "Cocktail."],
  ["ソーダ", "sooda", "soda", "Soda water."],
  ["レモン", "remon", "lemon", "Lemon."],
  ["オレンジ", "orenji", "orange", "Orange fruit or color."],
  ["バナナ", "banana", "banana", "Banana."],
  ["メロン", "meron", "melon", "Melon."],
  ["パイナップル", "painappuru", "pineapple", "Pineapple."],
  ["イチゴ", "ichigo", "strawberry", "Strawberry (katakana form)."],
  ["トマト", "tomato", "tomato", "Tomato."],
  ["レタス", "retasu", "lettuce", "Lettuce."],
  ["キャベツ", "kyabetsu", "cabbage", "Cabbage."],
  ["ポテト", "poteto", "potato", "Potato (loan)."],
  ["フライドポテト", "furaido poteto", "french fries", "Fries."],
  ["ハンバーガー", "hanbaagaa", "hamburger", "Burger."],
  ["ホットドッグ", "hotto doggu", "hot dog", "Hot dog."],
  ["サンドイッチ", "sandoicchi", "sandwich", "Sandwich."],
  ["ピザ", "piza", "pizza", "Pizza."],
  ["カレー", "karee", "curry", "Curry rice dish."],
  ["ラーメン", "raamen", "ramen", "Ramen noodles."],
  ["ステーキ", "suteeki", "steak", "Steak."],
  ["スープ", "suupu", "soup", "Soup."],
  ["デザート", "dezaato", "dessert", "Dessert."],
  ["ケーキ", "keeki", "cake", "Cake."],
  ["チョコ", "choko", "chocolate", "Short for chocolate."],
  ["クッキー", "kukkii", "cookie", "Cookie."],
  ["アイスコーヒー", "aisu koohii", "iced coffee", "Cold coffee."],
  ["ミルク", "miruku", "milk", "Milk (loanword)."],
  ["クリーム", "kuriimu", "cream", "Cream."],
  ["バター", "bataa", "butter", "Butter."],
  ["ヨーグルト", "yooguruto", "yogurt", "Yogurt."],
  ["シリアル", "shiriaru", "cereal", "Breakfast cereal."],
  ["ナイフ", "naifu", "knife", "Knife."],
  ["フォーク", "fooku", "fork", "Fork."],
  ["スプーン", "supuun", "spoon", "Spoon."],
  ["コップ", "koppu", "cup / glass", "Drinking glass."],
  ["グラス", "gurasu", "glass", "Glass cup."],
  ["プレート", "pureeto", "plate", "Plate."],
  ["ランチ", "ranchi", "lunch", "Lunch set."],
  ["ディナー", "dinaa", "dinner", "Dinner."],
  ["パーティー", "paatii", "party", "Party."],
  ["イベント", "ibento", "event", "Event."],
  ["コンサート", "konsaato", "concert", "Concert."],
  ["ライブ", "raibu", "live show", "Live performance."],
  ["ドラマ", "dorama", "TV drama", "Drama series."],
  ["アニメ", "anime", "anime", "Japanese animation."],
  ["マンガ", "manga", "manga", "Comics."],
  ["ゲーム", "geemu", "game", "Video or board game."],
  ["パズル", "pazuru", "puzzle", "Puzzle."],
  ["ニュース", "nyuusu", "news", "News."],
  ["サイト", "saito", "website", "Site."],
  ["ブログ", "burogu", "blog", "Blog."],
  ["オンライン", "onrain", "online", "Online."],
  ["オフライン", "ofurain", "offline", "Offline."],
  ["ダウンロード", "daunroodo", "download", "Download."],
  ["アップロード", "appuroodo", "upload", "Upload."],
  ["アップデート", "appudeeto", "update", "Update."],
  ["ログイン", "roguin", "login", "Log in."],
  ["ログアウト", "roguauto", "logout", "Log out."],
  ["パスワード", "pasuwaado", "password", "Password."],
  ["アカウント", "akaunto", "account", "User account."],
  ["ユーザー", "yuuzaa", "user", "User."],
  ["メンバー", "menbaa", "member", "Member."],
  ["チーム", "chiimu", "team", "Team."],
  ["リーダー", "riidaa", "leader", "Leader."],
  ["スタッフ", "sutaffu", "staff", "Staff."],
  ["マネージャー", "manejaa", "manager", "Manager."],
  ["オフィス", "ofisu", "office", "Office."],
  ["デスク", "desuku", "desk", "Desk (loan)."],
  ["ミーティング", "miitingu", "meeting", "Meeting."],
  ["プレゼン", "purezen", "presentation", "Short for presentation."],
  ["プロジェクト", "purojekuto", "project", "Project."],
  ["タスク", "tasuku", "task", "Task."],
  ["スケジュール", "sukejuuru", "schedule", "Schedule."],
  ["カレンダー", "karendaa", "calendar", "Calendar."],
  ["プラン", "puran", "plan", "Plan."],
  ["アイデア", "aidea", "idea", "Idea."],
  ["ヒント", "hinto", "hint", "Hint."],
  ["ポイント", "pointo", "point", "Point / tip."],
  ["レベル", "reberu", "level", "Level."],
  ["スキル", "sukiru", "skill", "Skill."],
  ["キャリア", "kyaria", "career", "Career."],
  ["インタビュー", "intabyuu", "interview", "Interview."],
  ["パート", "paato", "part-time job", "Part-time work."],
  ["アルバイト", "arubaito", "part-time job", "From German Arbeit."],
  ["インターン", "intaan", "intern", "Internship short form."],
  ["ボーナス", "boonasu", "bonus", "Bonus pay."],
  ["コスト", "kosuto", "cost", "Cost."],
  ["セールス", "seerusu", "sales", "Sales work."],
  ["マーケティング", "maaketingu", "marketing", "Marketing."],
  ["ブランド", "burando", "brand", "Brand."],
  ["イメージ", "imeeji", "image / impression", "Image."],
  ["ポスター", "posutaa", "poster", "Poster."],
  ["パンフレット", "panfuretto", "pamphlet", "Brochure pamphlet."],
  ["カタログ", "katarogu", "catalog", "Catalog."],
  ["サンプル", "sanpuru", "sample", "Sample."],
  ["テスト", "tesuto", "test", "Test."],
  ["チェック", "chekku", "check", "Check / verify."],
  ["スタート", "sutaato", "start", "Start."],
  ["ゴール", "gooru", "goal", "Goal."],
  ["フィニッシュ", "finisshu", "finish", "Finish."],
  ["ストップ", "sutoppu", "stop", "Stop."],
  ["オープン", "oopun", "open", "Open."],
  ["クローズ", "kuroozu", "close", "Close."],
  ["フリー", "furii", "free", "Free (no cost or free time)."],
  ["プラス", "purasu", "plus", "Plus."],
  ["マイナス", "mainasu", "minus", "Minus."],
  ["ゼロ", "zero", "zero", "Zero."],
  ["ナンバー", "nanbaa", "number", "Number."],
  ["ページ", "peeji", "page", "Page."],
  ["ファイル", "fairu", "file", "File."],
  ["フォルダ", "foruda", "folder", "Folder."],
  ["データ", "deeta", "data", "Data."],
  ["グラフ", "gurafu", "graph", "Graph."],
  ["チャート", "chaato", "chart", "Chart."],
  ["レポート", "repooto", "report", "Report."],
  ["リスト", "risuto", "list", "List."],
  ["フォーム", "foomu", "form", "Form to fill."],
  ["サイン", "sain", "signature / sign", "Sign or signature."],
  ["ルール", "ruuru", "rule", "Rule."],
  ["マナー", "manaa", "manners", "Etiquette."],
  ["トラブル", "toraburu", "trouble", "Problem / trouble."],
  ["エラー", "eraa", "error", "Error."],
  ["ミス", "misu", "mistake", "Mistake."],
  ["アドバイス", "adobaisu", "advice", "Advice."],
  ["サポート", "sapooto", "support", "Support."],
  ["ヘルプ", "herupu", "help", "Help."],
  ["ガイド", "gaido", "guide", "Guide."],
  ["ツアー", "tsuaa", "tour", "Tour."],
  ["トラベル", "toraberu", "travel", "Travel."],
  ["フライト", "furaito", "flight", "Flight."],
  ["ゲート", "geeto", "gate", "Airport gate."],
  ["シート", "shiito", "seat", "Seat."],
  ["ウィンドウ", "uindou", "window", "Window seat / window."],
  ["ラゲッジ", "ragejji", "luggage", "Luggage."],
  ["スーツケース", "suutsukeesu", "suitcase", "Suitcase."],
  ["バックパック", "bakkupakku", "backpack", "Backpack."],
  ["マップ", "mappu", "map", "Map."],
  ["ガイドブック", "gaidobukku", "guidebook", "Guidebook."],
  ["スポット", "supotto", "spot", "Place / spot."],
  ["フォト", "foto", "photo", "Photo."],
  ["ビデオ", "bideo", "video", "Video."],
  ["ムービー", "muubii", "movie", "Movie (loan)."],
  ["サウンド", "saundo", "sound", "Sound."],
  ["ミュージック", "myuujikku", "music", "Music (loan)."],
  ["ソング", "songu", "song", "Song."],
  ["アルバム", "arubamu", "album", "Album."],
  ["アーティスト", "aatisuto", "artist", "Artist."],
  ["アイドル", "aidoru", "idol", "Pop idol."],
  ["ファン", "fan", "fan", "Fan of someone."],
  ["スター", "sutaa", "star", "Star / celebrity."],
  ["ヒーロー", "hiiroo", "hero", "Hero."],
  ["キャラクター", "kyarakutaa", "character", "Character."],
  ["ストーリー", "sutoorii", "story", "Story."],
  ["エンディング", "endingu", "ending", "Ending."],
  ["オープニング", "oopuningu", "opening", "Opening."],
  ["デジタル", "dejitaru", "digital", "Digital."],
  ["アナログ", "anarogu", "analog", "Analog."],
  ["エンジン", "enjin", "engine", "Engine."],
  ["ブレーキ", "bureeki", "brake", "Brake."],
  ["アクセル", "akuseru", "accelerator", "Gas pedal."],
  ["タイヤ", "taiya", "tire", "Tire."],
  ["ハンドル", "handoru", "steering wheel", "Steering wheel."],
  ["バッテリー", "batterii", "battery", "Battery."],
  ["ガソリン", "gasorin", "gasoline", "Fuel."],
  ["オイル", "oiru", "oil", "Oil."],
  ["コンセント", "konsento", "electrical outlet", "Power outlet."],
  ["プラグ", "puragu", "plug", "Plug."],
  ["ケーブル", "keeburu", "cable", "Cable."],
  ["リモコン", "rimokon", "remote control", "Remote."],
  ["スイッチ", "suicchi", "switch", "Switch."],
  ["モニター", "monitaa", "monitor", "Display monitor."],
  ["プリンター", "purintaa", "printer", "Printer."],
  ["スキャナー", "sukyanag", "scanner", "fix spelling."],
  ["エアコン", "eakon", "air conditioner", "AC."],
  ["ヒーター", "hiitaa", "heater", "Heater."],
  ["電子レンジ", "denshi renji", "microwave", "Has kanji+kana - skip if mixed."],
];

const EXTRA = [
  ["スマートフォン", "sumaatofon", "smartphone", "Full form of スマホ."],
  ["タブレット", "taburetto", "tablet", "Tablet device."],
  ["キーボード", "kiiboodo", "keyboard", "Keyboard."],
  ["マウス", "mausu", "mouse", "Computer mouse."],
  ["スピーカー", "supiikaa", "speaker", "Audio speaker."],
  ["ヘッドホン", "heddohon", "headphones", "Headphones."],
  ["イヤホン", "iyahon", "earphones", "Earphones."],
  ["マイク", "maiku", "microphone", "Mic."],
  ["プリンター", "purintaa", "printer", "Printer (dup ok filtered)."],
  ["スキャナー", "sukyanagaa", "scanner", "Scanner."],
  ["コピー", "kopii", "copy", "Photocopy / copy."],
  ["ファックス", "fakkusu", "fax", "Fax."],
  ["ボールペン", "boorupen", "ballpoint pen", "Pen."],
  ["シャープペン", "shaapupen", "mechanical pencil", "Mechanical pencil."],
  ["消しゴム", "keshigomu", "eraser", "Mixed - skip."],
  ["ホッチキス", "hocchikisu", "stapler", "Stapler."],
  ["クリップ", "kurippu", "clip", "Paper clip."],
  ["ホワイトボード", "howaitoboodo", "whiteboard", "Whiteboard."],
  ["マーカー", "maakaa", "marker", "Marker pen."],
  ["クリアファイル", "kuria fairu", "clear folder", "Plastic folder."],
  ["バインダー", "baindaa", "binder", "Binder."],
  ["冷蔵庫", "reizouko", "refrigerator", "Mixed - skip."],
  ["レンジ", "renji", "range / microwave", "Cooking appliance."],
  ["トースター", "toosutaa", "toaster", "Toaster."],
  ["フライパン", "furaipan", "frying pan", "Frying pan."],
  ["ミキサー", "mikisaa", "blender", "Mixer / blender."],
  ["コーヒーメーカー", "koohii meekaa", "coffee maker", "Coffee machine."],
  ["ラップ", "rappu", "plastic wrap", "Food wrap."],
  ["ホイル", "hoiru", "foil", "Aluminum foil."],
  ["洗剤", "senzai", "detergent", "Mixed - skip."],
  ["リンス", "rinsu", "conditioner", "Hair rinse."],
  ["トリートメント", "toriitomento", "hair treatment", "Hair treatment."],
  ["ドライヤー", "doraiyaa", "hair dryer", "Dryer."],
  ["コーム", "koomu", "comb", "Comb."],
  ["ブラシ", "burashi", "brush", "Brush."],
  ["リップ", "rippu", "lipstick", "Lip product."],
  ["ファンデーション", "fandeeshon", "foundation", "Makeup."],
  ["マスカラ", "masukara", "mascara", "Makeup."],
  ["サプリ", "sapuri", "supplement", "Dietary supplement."],
  ["プロテイン", "purotein", "protein", "Protein powder/drink."],
  ["ミネラルウォーター", "mineraru wootaa", "mineral water", "Bottled water."],
  ["エナジードリンク", "enajii dorinku", "energy drink", "Energy drink."],
  ["スムージー", "sumuujii", "smoothie", "Smoothie."],
  ["グラノーラ", "guranora", "granola", "Granola."],
  ["ナッツ", "nattsu", "nuts", "Nuts."],
  ["デリバリー", "deribarii", "delivery", "Food delivery."],
  ["テイクアウト", "teikuauto", "takeout", "Takeaway food."],
  ["ビュッフェ", "byuffe", "buffet", "Buffet."],
  ["セットメニュー", "setto menyuu", "set menu", "Combo meal."],
  ["カフェラテ", "kafe rate", "cafe latte", "Latte."],
  ["カプチーノ", "kapuchiino", "cappuccino", "Cappuccino."],
  ["エスプレッソ", "esupuresso", "espresso", "Espresso."],
  ["ミルクティー", "miruku tii", "milk tea", "Milk tea."],
  ["パンケーキ", "pankeeki", "pancake", "Pancake."],
  ["ワッフル", "waffuru", "waffle", "Waffle."],
  ["ベーグル", "beeguru", "bagel", "Bagel."],
  ["クロワッサン", "kurowassan", "croissant", "Croissant."],
  ["ドーナツ", "doonatsu", "donut", "Donut."],
  ["マフィン", "mafin", "muffin", "Muffin."],
  ["プリン", "purin", "pudding", "Custard pudding."],
  ["ゼリー", "zerii", "jelly", "Jelly."],
  ["パフェ", "pafe", "parfait", "Parfait."],
  ["ソフトクリーム", "sofuto kuriimu", "soft serve", "Soft ice cream."],
  ["ポップコーン", "poppukoon", "popcorn", "Popcorn."],
  ["ガム", "gamu", "gum", "Chewing gum."],
  ["キャンディ", "kyandi", "candy", "Candy."],
  ["グミ", "gumi", "gummy candy", "Gummies."],
  ["スタジアム", "sutajiamu", "stadium", "Stadium."],
  ["プール", "puuru", "pool", "Swimming pool."],
  ["ダンベル", "danberu", "dumbbell", "Weights."],
  ["マット", "matto", "mat", "Exercise mat."],
  ["サウナ", "sauna", "sauna", "Sauna."],
  ["ロッカー", "rokkaa", "locker", "Locker."],
  ["キャンプ", "kyanpu", "camp", "Camping."],
  ["テント", "tento", "tent", "Tent."],
  ["ランタン", "rantan", "lantern", "Lantern."],
  ["バーベキュー", "baabekyuu", "barbecue", "BBQ."],
  ["ハイキング", "haikingu", "hiking", "Hiking."],
  ["サーフィン", "saafin", "surfing", "Surfing."],
  ["ダイビング", "daibingu", "diving", "Diving."],
  ["ヨット", "yotto", "yacht", "Yacht."],
  ["クルーズ", "kuruuzu", "cruise", "Cruise."],
  ["フェリー", "ferii", "ferry", "Ferry."],
  ["テーマパーク", "teema paaku", "theme park", "Theme park."],
  ["ジェットコースター", "jetto koosutaa", "roller coaster", "Roller coaster."],
  ["ミュージアム", "myuujiamu", "museum", "Museum."],
  ["ギャラリー", "gyararii", "gallery", "Gallery."],
  ["スタジオ", "sutajio", "studio", "Studio."],
  ["カラオケ", "karaoke", "karaoke", "Karaoke."],
  ["ギター", "gitaa", "guitar", "Guitar."],
  ["ピアノ", "piano", "piano", "Piano."],
  ["バイオリン", "baiorin", "violin", "Violin."],
  ["ドラム", "doramu", "drums", "Drums."],
  ["トランペット", "toranpetto", "trumpet", "Trumpet."],
  ["サックス", "sakkusu", "sax", "Saxophone."],
  ["ウクレレ", "ukurele", "ukulele", "Ukulele."],
  ["ストリーミング", "sutoriimingu", "streaming", "Streaming."],
  ["プレイリスト", "pureirisuto", "playlist", "Playlist."],
  ["ポッドキャスト", "poddokyasuto", "podcast", "Podcast."],
  ["チャンネル", "channeru", "channel", "Channel."],
  ["サブスク", "sabusuku", "subscription", "Subscription service."],
  ["クラウド", "kuraudo", "cloud", "Cloud storage."],
  ["バックアップ", "bakkuappu", "backup", "Backup."],
  ["ハッシュタグ", "hasshutagu", "hashtag", "Hashtag."],
  ["タイムライン", "taimurain", "timeline", "Social timeline."],
  ["コメント", "komento", "comment", "Comment."],
  ["フォロワー", "forowaa", "follower", "Follower."],
  ["インフルエンサー", "infuruensaa", "influencer", "Influencer."],
  ["キャンペーン", "kyanpeen", "campaign", "Campaign."],
  ["クーポン", "kuupon", "coupon", "Coupon."],
  ["ギフトカード", "gifuto kaado", "gift card", "Gift card."],
  ["バーゲン", "baagen", "bargain sale", "Sale event."],
  ["タイムセール", "taimu seeru", "timed sale", "Limited-time sale."],
  ["オンラインストア", "onrain sutoa", "online store", "Web shop."],
  ["ショールーム", "shooruumu", "showroom", "Showroom."],
  ["フィッティング", "fittingu", "fitting", "Trying on clothes."],
  ["カスタマーセンター", "kasutamaa sentaa", "customer center", "Support center."],
  ["コールセンター", "kooru sentaa", "call center", "Call center."],
  ["チャット", "chatto", "chat", "Chat."],
  ["セキュリティ", "sekyuriti", "security", "Security."],
  ["ウイルス", "uirusu", "virus", "Computer virus."],
  ["スマートウォッチ", "sumaato wotchi", "smartwatch", "Smartwatch."],
  ["ドローン", "doroon", "drone", "Drone."],
  ["ロボット", "robotto", "robot", "Robot."],
  ["ゲーム機", "geemuki", "game console", "Mixed - skip."],
  ["コントローラー", "kontorooraa", "controller", "Game controller."],
  ["ヘッドセット", "heddosetto", "headset", "Headset."],
  ["メモリ", "memori", "memory", "Computer memory."],
  ["ストレージ", "sutorreeji", "storage", "Data storage."],
  ["プロセッサ", "purosessa", "processor", "CPU."],
  ["バージョン", "baajon", "version", "Software version."],
  ["パッチ", "pacchi", "patch", "Software patch."],
  ["チュートリアル", "chuutoriaru", "tutorial", "Tutorial."],
  ["ミッション", "misshon", "mission", "Mission."],
  ["クエスト", "kuesuto", "quest", "Quest."],
  ["アイテム", "aitemu", "item", "Item."],
  ["コイン", "koin", "coin", "Coin / in-game coin."],
  ["ランク", "ranku", "rank", "Rank."],
  ["マッチング", "matchingu", "matching", "Matchmaking."],
  ["セーブ", "seebu", "save", "Save data."],
  ["ロード", "roodo", "load", "Load data."],
  ["タイトル", "taitoru", "title", "Title."],
  ["エンジニア", "enjinia", "engineer", "Engineer."],
  ["デザイナー", "dezainaa", "designer", "Designer."],
  ["プログラマー", "puroguramaa", "programmer", "Programmer."],
  ["ライター", "raitaa", "writer", "Writer."],
  ["カメラマン", "kameraman", "photographer", "Camera person."],
  ["ドライバー", "doraibaa", "driver", "Driver (person or screwdriver)."],
  ["パイロット", "pairotto", "pilot", "Pilot."],
  ["キャビンアテンダント", "kyabin atendanto", "flight attendant", "Cabin attendant."],
  ["ホテルマン", "hoteruman", "hotel clerk", "Hotel staff (older term)."],
  ["フロント", "furonto", "front desk", "Hotel front desk."],
  ["ロビー", "robii", "lobby", "Lobby."],
  ["エレベーター", "erebeetaa", "elevator", "Elevator (dup filtered)."],
  ["エスカレーター", "esukareetaa", "escalator", "Escalator."],
  ["プラットフォーム", "purattofoomu", "platform", "Train platform."],
  ["ホーム", "hoomu", "platform (short)", "Station platform short form."],
  ["タイムテーブル", "taimu teeburu", "timetable", "Schedule table."],
  ["デッドライン", "deddorain", "deadline", "Deadline (loan)."],
  ["アジェンダ", "ajenda", "agenda", "Meeting agenda."],
  ["メモ", "memo", "memo", "Short note."],
  ["スライド", "suraido", "slide", "Presentation slide."],
  ["プロジェクター", "purojekutaa", "projector", "Projector."],
  ["スクリーン", "sukuriin", "screen", "Screen."],
  ["ホワイトボード", "howaitoboodo", "whiteboard", "Whiteboard (dup)."],
  ["ポストイット", "posutoitto", "sticky note", "Sticky notes."],
  ["ステープラー", "suteepuraa", "stapler", "Stapler (alt)."],
  ["マジック", "majikku", "marker / magic", "Magic marker."],
  ["ボールペン", "boorupen", "ballpoint pen", "Pen (dup)."],
  ["カラー", "karaa", "color", "Color (loan)."],
  ["デザイン", "dezain", "design", "Design."],
  ["スタイル", "sutairu", "style", "Style."],
  ["ファッション", "fasshon", "fashion", "Fashion."],
  ["トレンド", "torendo", "trend", "Trend."],
  ["シーズン", "shiizun", "season", "Season (fashion/sports)."],
  ["コレクション", "korekushon", "collection", "Collection."],
  ["セールスポイント", "seerusu pointo", "selling point", "Key benefit."],
  ["キャッチコピー", "kyacchi kopii", "tagline", "Ad catchphrase."],
  ["ロゴ", "rogo", "logo", "Logo."],
  ["アイコン", "aikon", "icon", "Icon."],
  ["バナー", "banaa", "banner", "Web banner."],
  ["リンク", "rinku", "link", "Hyperlink."],
  ["ボタン", "botan", "button", "Button (dup)."],
  ["クリック", "kurikku", "click", "Mouse click."],
  ["タップ", "tappu", "tap", "Screen tap."],
  ["スワイプ", "suwaipu", "swipe", "Swipe gesture."],
  ["スクロール", "sukurooru", "scroll", "Scroll."],
  ["ズーム", "zuumu", "zoom", "Zoom."],
  ["フィルター", "firutaa", "filter", "Filter."],
  ["エフェクト", "efekuto", "effect", "Effect."],
  ["テンプレート", "tenpureeto", "template", "Template."],
  ["フォーマット", "foomatto", "format", "Format."],
  ["レイアウト", "reiauto", "layout", "Layout."],
  ["フォント", "fonto", "font", "Font."],
  ["サイズ", "saizu", "size", "Size (dup)."],
  ["パーセント", "paasento", "percent", "Percent."],
  ["ドル", "doru", "dollar", "US dollar."],
  ["ユーロ", "yuuuro", "euro", "Euro."],
  ["ポンド", "pondo", "pound", "British pound."],
  ["センチ", "senchi", "centimeter", "cm."],
  ["メートル", "meetoru", "meter", "Meter."],
  ["キロ", "kiro", "kilo", "Kilogram or kilometer."],
  ["グラム", "guramu", "gram", "Gram."],
  ["リットル", "rittoru", "liter", "Liter."],
  ["パーセント", "paasento", "percent", "dup."],
];

function toEntry([word, reading, meaningEn, explanationEn], i) {
  if (!/^[\u30A0-\u30FFー\s]+$/.test(word)) return null;
  if (!isLatinRomaji(reading.replace(/\s/g, ""))) return null;
  if (looksLikeFillerMeaning(meaningEn)) return null;
  if (/skip|dup|mixed/i.test(meaningEn + explanationEn)) return null;
  return {
    id: `k-${i}`,
    word: word.replace(/\s/g, ""),
    reading: reading.toLowerCase().trim(),
    meaningEn,
    explanationEn,
    ttsText: word.replace(/\s/g, ""),
    ttsLang: "ja-JP",
  };
}

export function buildKatakana(need) {
  const raw = [...CURATED, ...EXTRA, ...MORE_KATAKANA];
  const out = [];
  const seen = new Set();
  for (let i = 0; i < raw.length; i += 1) {
    const entry = toEntry(raw[i], i);
    if (!entry) continue;
    if (seen.has(entry.word)) continue;
    seen.add(entry.word);
    out.push(entry);
    if (out.length >= need) break;
  }
  if (out.length < 100) {
    throw new Error(`Katakana real vocab too small: ${out.length}`);
  }
  return out;
}
