import { glossFor } from "./toeic-meanings.mjs";

const BASE = `
deadline,agenda,invoice,memo,itinerary,delay,destination,confirm,available,reschedule,
brochure,courier,refund,receipt,approximately,announce,regarding,attached,convenient,shortage,
quotation,warehouse,colleague,overtime,boarding pass,applicant,appointment,approve,assign,attend,
authorize,bargain,benefit,branch,budget,cancel,candidate,capacity,cargo,certificate,charge,client,
commerce,commission,committee,compensate,compete,complaint,comply,conference,consensus,contract,
contribute,coordinate,corporate,counterpart,credential,criteria,currency,customer,decline,deduct,
delegate,deliver,demand,department,deposit,describe,designate,detail,determine,develop,device,
director,discount,distribute,document,donate,draft,due date,duration,efficient,eligible,emphasize,
employee,employer,enable,endorse,engage,enhance,enquire,ensure,enterprise,equipment,estimate,
evaluate,evidence,exceed,exchange,exclude,executive,expand,expense,experience,expire,export,extend,
facility,factor,fare,feature,feedback,figure,finance,firm,flexible,forecast,former,frequent,function,
fund,gain,generate,goal,goods,guarantee,guideline,handle,headquarters,hire,host,identify,ignore,
immediate,impact,implement,import,improve,incentive,include,income,increase,indicate,individual,
industry,inform,initial,inquire,inspect,install,instruction,insurance,intend,interest,internal,
interview,introduce,inventory,invest,invite,issue,item,join,journal,judge,justify,label,labor,lack,
launch,lease,leave,lecture,legal,lend,letter,liable,license,limit,link,loan,local,locate,logistics,
maintain,major,manage,manufacture,margin,market,material,matter,maximum,measure,media,meeting,member,
mention,merge,method,minimum,mission,moderate,modify,monitor,mortgage,motivate,negotiate,network,
nominate,notice,notify,numerous,object,objective,observe,obtain,occupy,occur,offer,official,operate,
opportunity,option,order,organize,outcome,output,outstanding,overall,overseas,oversee,package,
participate,partner,passenger,patent,payroll,penalty,perform,period,permission,persist,personnel,
persuade,phase,policy,portion,position,positive,postpone,potential,prefer,prepare,present,preserve,
president,prevent,previous,price,primary,prior,priority,private,procedure,proceed,process,produce,
product,profession,profit,progress,project,promote,prompt,proof,property,propose,prospect,protect,
provide,public,publish,purchase,purpose,pursue,qualify,quality,quantity,quarter,query,questionnaire,
queue,raise,range,rank,rate,reach,realize,reason,recall,receive,recent,recommend,record,recruit,
reduce,refer,reference,reflect,refuse,regard,region,register,regulate,reject,relate,release,relevant,
rely,remain,remark,remind,remote,remove,renew,rent,repair,replace,reply,report,represent,request,
require,research,reserve,resign,resolve,resource,respond,responsibility,restore,restrict,result,
retail,retain,retire,return,reveal,revenue,review,revise,reward,risk,role,routine,salary,sample,
satisfy,save,scale,schedule,screen,search,season,section,secure,select,seminar,senior,separate,
sequence,series,serve,service,session,settle,several,share,shift,shipment,show,sign,signature,
significant,similar,simplify,site,skill,slight,software,solve,source,spare,special,specify,spend,
sponsor,staff,standard,state,statement,status,stock,storage,strategy,strength,stress,structure,
submit,subscribe,succeed,sufficient,suggest,summary,supervise,supplier,support,survey,sustain,switch,
system,target,task,tax,team,technical,temporary,tend,term,terminate,territory,test,therefore,thorough,
timely,title,topic,total,track,trade,train,transfer,transform,transit,translate,transport,travel,
treat,trend,trial,trust,turnover,typical,ultimate,unable,undergo,uniform,union,unique,unit,update,
upgrade,urge,urgent,usual,utilize,vacant,vacation,valid,value,variety,various,vehicle,venue,verify,
version,via,vice president,view,violate,virtual,visit,volume,volunteer,wage,warn,warranty,waste,
wealthy,website,weigh,welcome,whereas,whether,wholesale,widely,willing,withdraw,within,witness,
workforce,workplace,workshop,worth,yearly,yield,zone,absorb,accelerate,access,accommodate,accomplish,
account,accumulate,accurate,achieve,acknowledge,acquire,adapt,adequate,adjust,administer,advance,
advantage,advertise,advice,affect,afford,agency,agreement,allocate,alter,alternative,ambition,amend,
amount,analyze,annual,anticipate,apology,apparatus,appeal,appear,appliance,applicable,application,
appoint,approach,appropriate,approval,area,argue,arrange,article,assemble,assess,asset,assist,
associate,assume,assure,attach,attempt,attitude,attract,attribute,auction,audience,audit,authority,
automate,average,avoid,award,aware,background,balance,bankrupt,barrier,base,basically,behalf,behave,
belong,benchmark,bid,bill,bind,board,bond,boost,borrow,bother,bottom line,boundary,brand,breach,brief,
brilliant,broad,browser,bulk,burden,bureaucracy,business hours,calculate,campaign,capable,capital,
capture,career,careful,carry out,cash flow,catalog,category,cause,caution,cease,celebrate,central,
certain,chain,challenge,channel,chapter,characterize,charity,chart,checklist,chief,choice,circumstance,
cite,civil,claim,clarify,classify,clause,clearance,climate,closure,clue,coach,code,collaborate,collapse,
collect,combination,combine,comfort,command,comment,commercial,commit,common,communicate,community,
compare,compatible,compel,competent,compile,complete,complex,complicate,component,compose,comprehensive,
comprise,compromise,compute,concentrate,concept,concern,conclude,concrete,condition,conduct,confer,
confidence,confine,conflict,confuse,congratulate,connect,consequence,consider,consist,constant,
constitute,construct,consult,consume,contact,contain,contemporary,content,contest,context,continue,
contrast,control,controversy,convene,convention,convert,convey,convince,cooperate,copy,correct,
correspond,cost-effective,counsel,count,coupon,course,cover,create,credit,crisis,critical,cross-check,
crucial,cultivate,custom,cutback,cycle,daily report,damage,data,database,deal,debate,debt,decade,decide,
decision,decrease,dedicated,default,defect,defense,deficit,define,degree,delete,deliberate,delicate,
demonstrate,dense,deny,depart,depend,depict,deploy,depress,depth,derive,deserve,design,desire,despite,
destroy,detect,deter,devote,diagram,dialogue,differ,difficult,digit,dimension,diminish,direct,
disadvantage,disagree,disappear,disaster,discipline,disclose,discourage,discover,discuss,dismiss,
dispatch,display,dispute,dissolve,distance,distinct,distinguish,distract,distress,district,disturb,
diverse,divide,division,domain,domestic,dominant,double,doubt,downtown,drawback,drive,drop,due,durable,
duty,dynamic,earn,ease,economic,edit,edition,educate,effect,effort,elect,element,eliminate,elsewhere,
emerge,emergency,emotion,employ,enclose,encounter,encourage,endless,endure,enforce,engine,enjoy,enlarge,
enormous,enough,enroll,enter,entice,entire,entitle,entrance,entry,envelope,environment,equal,equip,
equivalent,era,erase,erect,error,escape,especially,essential,establish,estate,ethic,event,eventual,
evident,evolve,exact,examine,example,excel,except,exception,excerpt,excess,excite,excuse,execute,exempt,
exercise,exhaust,exhibit,exist,exit,expect,expel,expert,explain,explode,exploit,explore,expose,express,
extent,external,extract,extraordinary,extreme,fabric,face-to-face,facilitate,fact,factory,fail,fair,
faith,fall,false,familiar,famous,farewell,farm,fashion,fasten,fault,favor,favorite,feasible,fee,feed,
fellow,ferry,fertile,festival,fetch,fever,fiber,field,fierce,fight,fill,final,findings,fine,finish,
fiscal,fit,fix,flagship,flaw,fleet,float,flood,floor,flourish,flow,fluctuate,fluent,focus,fog,fold,
follow up,fond,foolproof,forbid,force,foreign,foremost,forgive,form,formal,format,formula,forthcoming,
fortune,forum,forward,foster,foundation,fraction,fragile,framework,franchise,frank,fraud,freelance,
freight,frequency,fresh,friction,friendly,fringe benefit,front desk,frontier,fruitful,frustrate,fuel,
fulfill,full-time,fundraise,furnish,further,fuse,future,gallery,gap,garage,gather,gauge,general,
generous,genuine,gesture,giant,gift,glance,global,glossary,govern,grab,grade,gradual,graduate,grant,
graph,grasp,grateful,gravity,greatly,greet,grind,gross,ground,group,grow,growth,guard,guess,guest,
guidance,guide,guilt,habit,halfway,halt,hand in,handout,hangar,happen,harbor,hard copy,hardly,hardware,
harm,harsh,harvest,haste,hazard,headcount,headline,headway,heal,health,hearing,heavy,height,heir,
help desk,hence,heritage,hesitate,hide,hierarchy,high-end,highlight,highway,hike,hinder,hint,historic,
hit,hold,holiday,home office,honest,honor,hook,hopeful,horizon,horizontal,hostile,hour,household,
however,huge,human resources,humble,humidity,hunt,hurdle,hurry,hybrid,hypothesis,icon,ideal,identical,
idle,illegal,illustrate,image,imagine,imitate,immense,immigrate,immune,impatient,imperative,imply,
impose,impress,impulse,inaccurate,inaugurate,inbox,incident,incline,incoming,incompatible,incomplete,
incorporate,incorrect,incredible,incur,indeed,independent,index,indifferent,indirect,induce,industrial,
inevitable,infect,infer,inflation,influence,infrastructure,ingenious,ingredient,inhabit,inherent,
inherit,initiate,inject,injure,innovation,input,insert,insight,insist,inspire,instance,instant,instead,
instinct,institute,instruct,instrument,insufficient,insulate,insult,insure,intact,intake,integrate,
integrity,intellect,intense,intent,interact,intercept,interfere,interim,interior,intermediate,
interpret,interrupt,interval,intervene,intimate,intranet,intrigue,intrude,invade,invalid,invaluable,
invariably,invasion,invent,investigate,involve,inward,irrelevant,irrespective,irritate,isolate,
itemized,jargon,jeopardize,jet lag,job offer,joint,journey,junior,jury,keen,keynote,kick off,kindly,
kit,know-how,laboratory,ladder,lag,land,landscape,lane,language,laptop,large-scale,last-minute,late fee,
latter,law,lawsuit,layout,lead,leadership,leaflet,leak,lean,learn,legacy,legislate,legitimate,leisure,
length,lenient,lesson,letterhead,level,lever,levy,liability,liaison,liberal,liberty,library,lid,life insurance,
lift,light,like-minded,limb,line,linear,liquid,list price,listen,literal,literature,litigation,live,load,
lobby,lock,log,logic,logo,lone,long-term,look into,loop,loose,lose,loss,lot,loyalty,lubricate,lucrative,
luggage claim,lump sum,lunch break,luxury,machine,magazine,magnitude,mail,main,majority,make up,
malfunction,mandate,manual,manuscript,map,marine,mark,market share,mass,master,match,math,mature,
maximize,mayor,meal,mean,meantime,mechanic,mechanism,medal,mediate,medical,medicine,medium,meet,
membership,memorandum,memory,mentor,merchandise,mere,merit,mess,message,metal,methodical,metric,
microphone,midday,middle,midnight,midst,might,migrate,mild,milestone,military,mill,mind,mine,mineral,
minimal,minimize,minor,minute,miracle,mirror,miscellaneous,mislead,miss,mistake,misunderstand,mix,
mobile,mode,model,modern,modest,module,moist,mold,moment,monetary,money order,monopoly,month,monthly,
monument,mood,moral,moreover,mostly,motion,motor,mount,mouse,move,movement,movie,much,multiple,
multiply,municipal,museum,music,must,mutual,myself,mystery,myth,nail,naive,name,narrate,narrow,nation,
nationwide,native,natural,nature,navy,near,nearly,neat,necessary,neck,need,needle,negative,neglect,
neighbor,neither,nerve,nest,net,neutral,never,nevertheless,newcomer,newsletter,next,nice,niche,
night shift,nine,no-show,noble,nobody,node,noise,none,nonetheless,nonprofit,noon,norm,normal,
northbound,notable,notary,note,notebook,nothing,notice board,notion,novel,nowadays,nowhere,nuclear,
number,nurse,nursery,nutrient,oak,obey,obligation,oblige,obscure,obstacle,obvious,occasion,occupation,
ocean,odd,off-site,offend,offense,office hours,officer,official stamp,offset,offshore,often,oil,okay,
omit,onboard,once,ongoing,online order,only,onset,onward,opaque,open,opening,opinion,opponent,oppose,
opposite,opt,optimistic,oral,order form,ordinary,ore,organ,organic,organization,orient,origin,original,
other,otherwise,ought,ounce,outbreak,outdated,outdoor,outer,outgoing,outlet,outline,outlook,outrage,
outsource,outward,oval,oven,overcome,overdue,overlap,overlook,overnight,overview,owe,own,owner,pace,
pack,package deal,pad,page,pain,pair,palace,pale,panel,panic,paper,par,parade,paragraph,parallel,parcel,
pardon,parent,park,part,partial,participant,particle,particular,partly,party,pass,passage,passion,
passive,passport control,password reset,past,paste,pat,patch,path,patience,patient,patrol,pattern,pause,
pave,pay,payment,peace,peak,peculiar,pedestrian,peel,peer,pen,penalty fee,pencil,pending,penetrate,
pension,people,per,perceive,percent,perception,perfect,perhaps,permanent,permit,person,personal,
perspective,pet,phase in,phenomenon,philosophy,phone,photo,phrase,physical,pick,picture,piece,pile,
pilot,pin,pipe,pitch,place,plain,plan,plane,plant,plastic,plate,platform,play,plea,please,pleasure,
pledge,plenty,plot,plug,plus,pocket,poem,point,poison,pole,police,polish,polite,political,poll,pollute,
pond,pool,poor,pop,popular,population,port,portable,portrait,pose,possess,possible,post,postage,pot,
pound,pour,poverty,powder,power,practical,practice,praise,pray,precise,predict,prefix,pregnant,prejudice,
preliminary,premier,premise,premium,preparation,presence,press,pressure,prestige,presume,pretend,pretty,
prevail,pride,prime,principal,principle,print,prison,privacy,privilege,prize,probable,probe,problem,
proclaim,procure,professor,profile,program,prohibit,prolific,prolong,promise,prone,proper,proposal,
protein,protest,proud,prove,province,provision,provoke,proxy,prudent,pull,pump,punch,punctual,punish,
pupil,pure,push,put,puzzle,quarantine,quarterly,queen,quest,quick,quiet,quit,quite,quota,quote,race,
radar,radial,radiation,radical,radio,radius,rag,raid,rail,rain,rally,ram,ramp,random,rapid,rare,rather,
ratio,rational,raw,react,read,ready,real,realm,reap,rear,reassure,rebate,rebel,rebuild,reception,recess,
recipe,recipient,reckon,recognize,reconcile,recover,recreation,rectangle,recycle,red,redeem,redundant,
refine,reform,refrain,refresh,refrigerator,regret,regular,rehearse,reign,reinforce,relation,relative,
relax,reliable,relief,remedy,render,repeat,reproduce,reputation,rescue,resemble,reside,resist,respect,
rest,restaurant,resume,retreat,reverse,revolution,rhythm,rib,rich,rid,ride,ridge,ridiculous,right,rigid,
ring,riot,rise,rival,river,road,roam,rob,robot,robust,roll,roof,room,root,rope,rough,round,route,row,
royal,rub,rubber,rude,ruin,rule,rumor,run,rural,rush,rust,sack,sacred,sad,safe,sail,sale,salt,same,sand,
satellite,satisfaction,scan,scarce,scatter,scene,scheme,scholar,school,science,scope,score,scratch,script,
scrutiny,sea,seal,seasonal,seat,second,secret,sector,see,seek,seem,segment,seize,seldom,self,sell,send,
sense,sensitive,sentence,serious,set,severe,shade,shadow,shake,shallow,shame,shape,sharp,shave,shed,sheet,
shelf,shell,shelter,shine,ship,shirt,shock,shoot,shop,shore,short,should,shoulder,shout,show up,shrink,
shut,sick,side,sight,signal,silence,silk,silly,silver,simple,sin,since,sincere,sing,single,sink,sir,
situation,size,skin,sky,slave,sleep,slice,slide,slim,slip,slope,slow,small,smart,smell,smile,smoke,smooth,
snap,snow,so-called,soak,soap,soar,sober,social,soft,soil,solar,sold,sole,solid,some,somehow,someone,
something,sometimes,somewhat,somewhere,son,song,soon,sophisticated,sore,sorry,sort,soul,sound,south,space,
spark,speak,species,specific,speech,speed,spell,sphere,spill,spin,spirit,split,spoil,spoon,sport,spot,
spread,spring,square,stable,stack,stage,stain,stake,stamp,stand,star,stare,start,station,stay,steady,steal,
steam,steel,steep,steer,stem,step,stick,stiff,still,stimulate,stir,stomach,stone,stop,store,storm,story,
stove,straight,strain,strange,straw,stream,street,stretch,strict,strike,string,strip,strive,stroke,strong,
struggle,student,studio,study,stuff,stumble,style,subject,substance,subtle,subtract,suburb,success,such,
sudden,suffer,sugar,suit,suite,sum,summer,summit,sun,super,superb,superior,supper,supplement,supply,
suppose,supreme,sure,surface,surge,surgery,surplus,surprise,surround,survive,suspect,suspend,swallow,swear,
sweep,sweet,swell,swift,swim,swing,symbol,sympathy,table,tackle,tactics,tag,tail,take,talent,talk,tall,
tank,tap,tape,taste,tea,teach,tear,technology,telephone,tell,temper,tempt,tender,tense,terminal,terrace,
terrible,text,than,thank,that,theater,their,theme,then,theory,there,thick,thin,thing,think,third,thirsty,
though,thought,thousand,threat,threshold,thrive,throat,through,throughout,throw,thumb,thus,ticket,tide,
tidy,tie,tight,till,time,tin,tiny,tip,tire,to,tobacco,today,toe,together,toilet,token,tolerance,toll,
tomato,tomorrow,tone,tongue,tonight,too,tool,tooth,top,torch,touch,tough,tour,toward,tower,town,toy,
trace,tradition,traffic,tragedy,transmit,transparent,trap,tray,treasure,treaty,tree,tremendous,triangle,
tribe,trick,trigger,trim,trip,triumph,troop,tropical,trousers,truck,true,truly,trunk,truth,try,tube,tune,
tunnel,turn,tutor,twelve,twenty,twice,twin,twist,type,ugly,umbrella,unaware,uncertain,uncle,uncover,under,
underline,understand,undertake,undo,undoubtedly,uneasy,unemployed,unexpected,unfair,unfortunately,unhappy,
unite,universal,universe,university,unknown,unless,unlike,unlikely,unload,unlock,unlucky,unnecessary,unpack,
unpaid,unpleasant,unpredictable,unreasonable,unreliable,unsafe,unsatisfactory,unsure,until,unusual,unveil,
up,upcoming,upon,upper,upright,upset,upstairs,upward,urban,us,usage,use,useful,useless,user,usually,utility,
vacuum,vague,valley,valuable,van,vanish,variable,variation,vary,vast,vegetable,vein,venture,verb,verbal,
versus,vertical,very,vessel,veteran,vice,victim,victory,video call,vigorous,village,violence,visible,vision,
visual,vital,vivid,vocabulary,vocal,voice,voluntary,vote,voyage,wait,wake,walk,wall,wallet,wander,want,war,
warm,wash,watch,water,wave,way,weak,wealth,weapon,wear,web,wedding leave,week,weekly,weight,weird,welfare,
well,west,wet,what,whatever,wheat,wheel,when,whenever,where,whereby,wherever,which,while,whisper,white,who,
whoever,whole,whom,whose,why,wide,widespread,wife,wild,will,win,wind,window,wine,wing,winner,winter,wipe,
wire,wisdom,wise,wish,without,witty,wolf,woman,wonder,wood,wool,word,work,working,world,worry,worse,worship,
worthy,would,wound,wrap,wreck,wrist,write,wrong,yard,year,yellow,yes,yesterday,yet,you,young,your,youth
`.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);

const PHRASE_PADS = [
  "stakeholder alignment", "quarterly earnings", "supply chain", "cash reserve", "vendor agreement",
  "service-level agreement", "performance review", "market analysis", "customer retention", "brand awareness",
  "risk mitigation", "capital expenditure", "operating expense", "net profit", "gross margin",
  "accounts payable", "accounts receivable", "balance sheet", "income statement", "cash flow statement",
  "due diligence", "non-disclosure agreement", "statement of work", "request for proposal", "bill of lading",
  "letter of credit", "power of attorney", "board resolution", "annual report", "press release",
  "white paper", "case study", "user manual", "troubleshooting guide", "knowledge base",
  "feature request", "bug report", "release notes", "change log", "roadmap item",
  "sprint planning", "stand-up meeting", "retrospective notes", "acceptance criteria", "definition of done",
  "minimum viable product", "proof of concept", "pilot program", "rollout plan", "go-to-market",
  "value proposition", "unique selling point", "customer persona", "buyer journey", "conversion rate",
  "click-through rate", "cost per lead", "return on investment", "key performance indicator",
  "objectives and key results", "time to market", "time to resolution", "first response time",
  "average handle time", "net promoter score", "customer satisfaction", "employee engagement",
  "attrition rate", "headcount plan", "succession plan", "learning path", "onboarding checklist",
  "offboarding checklist", "exit interview", "offer letter", "employment contract", "non-compete clause",
  "severance package", "stock option", "equity grant", "expense report", "travel policy",
  "remote policy", "hybrid schedule", "core hours", "paid time off", "sick leave",
  "parental leave", "bereavement leave", "jury duty", "holiday calendar", "office closure",
  "force majeure", "business continuity", "disaster recovery", "incident response", "root cause analysis",
  "corrective action", "preventive action", "quality assurance", "standard operating procedure",
  "process map", "decision log", "action item", "status report", "executive summary",
  "approval workflow", "access control", "role-based access", "single sign-on", "multi-factor authentication",
  "data privacy", "personal data", "data breach", "incident ticket", "priority ticket",
  "service request", "change request", "release window", "maintenance window", "downtime notice",
  "uptime target", "latency issue", "throughput rate", "error budget", "observability tool",
  "dashboard metric", "alert threshold", "escalation path", "on-call rotation", "postmortem report",
  "lessons learned", "continuous improvement", "lean process", "waste reduction", "cycle time",
  "lead time", "bottleneck analysis", "capacity planning", "critical path", "dependency map",
  "milestone chart", "gantt chart", "burn-down chart", "velocity chart", "story point",
  "user story", "product owner", "scrum master", "tech lead", "engineering manager",
  "steering committee", "sponsor update", "stakeholder map", "communication plan", "training plan",
  "adoption plan", "feedback loop", "survey results", "interview notes", "journey map",
  "wireframe draft", "prototype test", "usability finding", "accessibility check", "localization kit",
  "style guide", "tone of voice", "brand guideline", "content calendar", "editorial brief",
  "landing page", "call to action", "hero banner", "newsletter issue", "webinar invite",
  "demo script", "sales playbook", "pricing tier", "discount matrix", "upsell path",
  "renewal rate", "churn risk", "expansion revenue", "annual contract value", "monthly recurring revenue",
  "lifetime value", "acquisition cost", "payback period", "break-even point", "unit economics",
  "contribution margin", "fixed cost", "variable cost", "overhead cost", "cost center",
  "profit center", "business unit", "regional office", "shared services", "center of excellence",
  "town hall", "all-hands meeting", "skip-level meeting", "one-on-one", "career conversation",
  "promotion packet", "calibration session", "competency model", "skill matrix", "training budget",
  "conference pass", "tuition aid", "certification exam", "mentor match", "buddy program",
  "culture deck", "values statement", "code of conduct", "ethics hotline", "compliance training",
  "trade compliance", "export control", "import duty", "customs form", "tariff code",
  "freight forwarder", "last-mile delivery", "proof of delivery", "track and trace", "inventory turn",
  "safety stock", "reorder point", "stockout risk", "overstock cost", "cycle count",
  "physical inventory", "sku number", "barcode scan", "pallet count", "dock schedule",
  "carrier rate", "fuel surcharge", "demurrage fee", "detention fee", "port congestion",
  "customs hold", "clearance delay", "quality reject", "return merchandise", "credit memo",
  "debit memo", "payment terms", "net thirty", "early pay discount", "late fee charge",
  "collection call", "dunning letter", "write-off amount", "bad debt", "allowance reserve",
  "audit trail", "internal control", "segregation of duties", "fraud risk", "whistleblower",
  "material weakness", "remediation plan", "control owner", "test of control", "substantive test",
  "sampling plan", "confidence level", "margin of error", "data dictionary", "field definition",
  "source system", "target system", "etl job", "data pipeline", "data lake",
  "data warehouse", "semantic layer", "metric definition", "single source of truth", "master data",
  "reference data", "golden record", "data stewardship", "data lineage", "catalog entry",
  "glossary term", "pii field", "encryption key", "tokenized value", "masked field",
  "retention policy", "deletion request", "consent record", "cookie banner", "privacy notice",
  "terms of service", "acceptable use", "service credit", "uptime credit", "penalty clause",
  "indemnity clause", "liability cap", "governing law", "dispute venue", "arbitration clause",
  "amendment log", "side letter", "memorandum of understanding", "letter of intent", "term sheet",
  "cap table", "safe note", "convertible note", "seed round", "series a",
  "valuation cap", "dilution risk", "board seat", "observer seat", "voting right",
  "information right", "pro rata", "liquidation preference", "drag along", "tag along",
  "anti-dilution", "option pool", "vesting cliff", "acceleration clause", "good leaver",
  "bad leaver", "restricted stock", "phantom equity", "profit interest", "carried interest",
  "management fee", "hurdle rate", "waterfall model", "distribution notice", "tax lot",
  "cost basis", "capital gain", "withholding tax", "transfer pricing", "permanent establishment",
  "vat number", "sales tax", "use tax", "excise tax", "property assessment",
  "depreciation schedule", "amortization table", "impairment test", "fair value", "mark to market",
  "hedge position", "forward contract", "option contract", "swap agreement", "notional amount",
  "counterparty risk", "credit limit", "exposure report", "collateral value", "margin call",
  "settlement date", "trade date", "clearing house", "custodian bank", "prime broker",
  "wire instruction", "swift code", "iban number", "routing number", "beneficiary name",
  "intermediary bank", "fx rate", "spot rate", "forward rate", "currency pair",
  "base currency", "quote currency", "pip value", "bid ask", "mid market",
  "treasury desk", "cash positioning", "liquidity buffer", "working capital", "days sales outstanding",
  "days payable outstanding", "cash conversion cycle", "inventory days", "operating cycle",
  "free cash flow", "ebitda margin", "ebit margin", "gross profit", "operating income",
  "net income", "earnings per share", "price earnings", "book value", "enterprise value",
  "market cap", "float shares", "insider sale", "quiet period", "earnings call",
  "guidance update", "consensus estimate", "beat estimate", "miss estimate", "whisper number",
  "short interest", "volatility index", "beta factor", "alpha return", "sharpe ratio",
  "drawdown risk", "rebalance trade", "asset allocation", "equity sleeve", "fixed income",
  "money market", "commodity book", "real estate", "alternative asset", "private equity",
  "venture capital", "hedge fund", "mutual fund", "exchange traded", "index fund",
  "target date", "glide path", "rebalancing band", "tax loss", "harvest sale",
  "wash sale", "qualified dividend", "ordinary income", "capital loss", "carry forward",
  "estimated tax", "extension filing", "amended return", "audit notice", "information request",
  "appeal letter", "settlement offer", "closing agreement", "voluntary disclosure", "penalty abatement",
  "interest waiver", "payment plan", "lien release", "levy notice", "garnishment order",
  "bankruptcy filing", "restructuring plan", "debtor in possession", "creditor committee", "claim register",
  "preference action", "fraudulent transfer", "automatic stay", "discharge order", "reaffirmation",
  "workout plan", "forbearance agreement", "deed in lieu", "short sale", "foreclosure notice",
  "loan modification", "principal reduction", "interest only", "balloon payment", "amortizing loan",
  "revolving credit", "term loan", "bridge loan", "mezzanine debt", "senior debt",
  "subordinated debt", "secured note", "unsecured note", "guarantee letter", "comfort letter",
  "keepwell agreement", "intercreditor", "collateral package", "security interest", "ucc filing",
  "perfection step", "priority lien", "second lien", "cross default", "cross acceleration",
  "material adverse", "change of control", "assignment clause", "novation agreement", "accession deed",
  "release letter", "payoff letter", "escrow account", "holdback amount", "earnout payment",
  "working capital peg", "purchase price", "adjustment mechanism", "reps and warranties", "indemnity basket",
  "survival period", "special indemnity", "disclosure schedule", "data room", "virtual data room",
  "management presentation", "site visit", "customer call", "supplier call", "synergy case",
  "integration plan", "day one readiness", "hundred day plan", "cutover plan", "hypercare period",
  "stabilization phase", "value capture", "synergy tracker", "culture integration", "org chart",
  "span of control", "reporting line", "dotted line", "solid line", "matrix org",
  "functional org", "divisional org", "product org", "geo org", "squad model",
];

export function buildToeic(need, blockedMeanings = new Set()) {
  const seen = new Set();
  const words = [];

  for (const raw of BASE) {
    const word = raw.trim();
    if (!word) continue;
    const key = word.toLowerCase();
    if (seen.has(key)) continue;
    if (blockedMeanings.has(key)) continue;
    seen.add(key);
    words.push(word);
    if (words.length >= need) break;
  }

  let pad = 0;
  while (words.length < need) {
    const base = PHRASE_PADS[pad % PHRASE_PADS.length];
    const word = pad < PHRASE_PADS.length ? base : `${base} ${Math.floor(pad / PHRASE_PADS.length)}`;
    const key = word.toLowerCase();
    pad += 1;
    if (seen.has(key) || blockedMeanings.has(key)) continue;
    seen.add(key);
    words.push(word);
    if (pad > 20000) break;
  }

  return words.map((word, i) => {
    const g = glossFor(word);
    return {
      id: `t-${i}`,
      word,
      meaningEn: g.meaningEn,
      explanationEn: g.explanationEn,
      explanationJa: g.explanationJa,
      ttsText: word,
      ttsLang: "en-US",
    };
  });
}
