import type { LearningUnit } from "@/lib/types";

/** Parallel to Japanese first phrases: useful English you can say today. */
export const toeicWelcomeUnit: LearningUnit = {
  id: "toeic-welcome",
  pathId: "toeic",
  title: "First English phrases",
  titleJa: "はじめての英語フレーズ",
  subtitle: "Learn useful workplace lines before exam drills",
  xpReward: 90,
  tutorial: {
    title: "English the same way as Japanese Quest",
    titleJa: "日本語クエストと同じ学び方",
    bodyEn:
      "We teach first, then quiz. Start with short workplace phrases you can say out loud. Listen, repeat, then a tiny check. Later units add vocabulary, reading, and official TOEIC part skills.",
    bodyJa:
      "先に教えて、あとで確認します。まずは声に出せる短い仕事英語から。聞いて繰り返して、短いチェックへ。そのあと語彙・読解・本番パートへ進みます。",
    tips: [
      "Tap Listen on every phrase",
      "Say it aloud before the check",
      "Japanese support is always there",
    ],
  },
  teach: [
    {
      glyph: "Hello",
      reading: "heh-LOH",
      tipEn: "Friendly greeting. Soft h, stress on LO.",
      tipJa: "あいさつ。h を軽く、LO に強勢。",
      ttsText: "Hello",
      ttsLang: "en-US",
    },
    {
      glyph: "Thank you",
      reading: "THANGK yoo",
      tipEn: "Polite thanks. th as in think (tongue on teeth).",
      tipJa: "ありがとう。th は舌を歯につけて。",
      ttsText: "Thank you",
      ttsLang: "en-US",
    },
    {
      glyph: "Yes / No",
      reading: "yes / noh",
      tipEn: "Clear answers. Keep them short and crisp.",
      tipJa: "はい／いいえ。短くはっきり。",
      ttsText: "Yes. No.",
      ttsLang: "en-US",
    },
    {
      glyph: "Please",
      reading: "pleez",
      tipEn: "Softens a request: Coffee, please.",
      tipJa: "依頼をやわらげる語。Coffee, please.",
      ttsText: "Please",
      ttsLang: "en-US",
    },
    {
      glyph: "Excuse me",
      reading: "ek-SKYOOZ mee",
      tipEn: "Get attention or apologize lightly.",
      tipJa: "呼び止めや軽い謝罪。",
      ttsText: "Excuse me",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "tw-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which phrase means thanks?",
      promptJa: "「ありがとう」に近いのは？",
      choices: [
        { id: "a", label: "A) Excuse me" },
        { id: "b", label: "B) Thank you" },
        { id: "c", label: "C) Hello" },
        { id: "d", label: "D) No" },
      ],
      correctChoiceId: "b",
      explanationEn: "Thank you = thanks.",
      explanationJa: "Thank you が「ありがとう」です。",
    },
    {
      id: "tw-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which phrase do you hear?",
      promptJa: "聞いて、聞こえたフレーズは？",
      ttsText: "Excuse me",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Hello" },
        { id: "b", label: "B) Please" },
        { id: "c", label: "C) Excuse me" },
        { id: "d", label: "D) Yes" },
      ],
      correctChoiceId: "c",
      explanationEn: "You heard Excuse me.",
      explanationJa: "Excuse me でした。",
    },
    {
      id: "tw-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say: Thank you.",
      promptJa: "Thank you と言ってください。",
      ttsText: "Thank you",
      ttsLang: "en-US",
      explanationEn: "Keep the th clear: tongue lightly on teeth.",
      explanationJa: "th を意識して。",
    },
    {
      id: "tw-4",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick the polite request helper.",
      promptJa: "依頼をやわらげる語は？",
      choices: [
        { id: "a", label: "A) No" },
        { id: "b", label: "B) Please" },
        { id: "c", label: "C) Hello" },
        { id: "d", label: "D) Yes" },
      ],
      correctChoiceId: "b",
      explanationEn: "Please softens requests.",
      explanationJa: "Please が依頼を丁寧にします。",
    },
    {
      id: "tw-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "How does Lumi teach English on this path?",
      promptJa: "このコースの英語の学び方は？",
      choices: [
        { id: "a", label: "A) Quiz only, no teaching" },
        { id: "b", label: "B) Learn with audio first, then a short check" },
        { id: "c", label: "C) Memorize a dictionary" },
        { id: "d", label: "D) Skip listening forever" },
      ],
      correctChoiceId: "b",
      explanationEn: "Same model as Japanese Quest: Learn, then practice.",
      explanationJa: "日本語クエストと同じ：先に Learn、あとで練習。",
    },
  ],
};
