import type { LearningUnit } from "@/lib/types";

/** Parallel to Japanese sounds: English phonics that trip up Japanese learners. */
export const toeicSoundsUnit: LearningUnit = {
  id: "toeic-sounds",
  pathId: "toeic",
  title: "English sounds",
  titleJa: "英語の音",
  subtitle: "Key sounds for Japanese ears: R/L, TH, short vowels",
  xpReward: 100,
  tutorial: {
    title: "Train your ear before the exam",
    titleJa: "本番の前に耳を作る",
    bodyEn:
      "Japanese mora timing is even. English stretches and reduces vowels, and has sounds Japanese does not (R vs L, TH). Learn each target sound with Listen, then a short check. This helps Listening Parts 1 to 4.",
    bodyJa:
      "日本語は拍が均等で、英語は母音の長さや弱形があり、R/L・TH など日本語にない音があります。Listen で1つずつ覚えてから短い確認へ。Listening Part 1〜4の土台になります。",
    tips: [
      "Exaggerate the mouth shape once, then relax",
      "Compare minimal pairs: light / right",
      "Use Listen twice if needed",
    ],
  },
  teach: [
    {
      glyph: "R",
      reading: "right",
      tipEn: "English R: tongue tip up, not flapped like Japanese ら行.",
      tipJa: "英語の R。舌先を上げる。日本語のら行の弾きとは違う。",
      ttsText: "right",
      ttsLang: "en-US",
    },
    {
      glyph: "L",
      reading: "light",
      tipEn: "English L: tongue tip touches behind upper teeth.",
      tipJa: "英語の L。舌先を上の歯の裏に当てる。",
      ttsText: "light",
      ttsLang: "en-US",
    },
    {
      glyph: "TH",
      reading: "think",
      tipEn: "TH (think): tongue lightly between teeth + air.",
      tipJa: "think の th。舌を歯の間に軽く出して息を通す。",
      ttsText: "think",
      ttsLang: "en-US",
    },
    {
      glyph: "short A",
      reading: "cat",
      tipEn: "Short a (cat): wider mouth than Japanese ア.",
      tipJa: "cat の短い a。日本語のアより口を横に。",
      ttsText: "cat",
      ttsLang: "en-US",
    },
    {
      glyph: "schwa ə",
      reading: "a bout",
      tipEn: "Schwa: weak 'uh' in about, agenda. Very common in TOEIC speech.",
      tipJa: "about の弱い母音（ə）。TOEIC音声で頻出。",
      ttsText: "about",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "ts-1",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Do you hear light or right?",
      promptJa: "聞こえるのは light と right のどちらの L/R？",
      ttsText: "light",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) light (L)" },
        { id: "b", label: "B) right (R)" },
        { id: "c", label: "C) night" },
        { id: "d", label: "D) write" },
      ],
      correctChoiceId: "a",
      explanationEn: "light starts with L (tongue on teeth ridge).",
      explanationJa: "light は L で始まります。",
    },
    {
      id: "ts-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word has TH as in think?",
      promptJa: "think と同じ th の語は？",
      ttsText: "think",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) sink" },
        { id: "b", label: "B) think" },
        { id: "c", label: "C) pink" },
        { id: "d", label: "D) link" },
      ],
      correctChoiceId: "b",
      explanationEn: "think uses the TH sound.",
      explanationJa: "think の th です。",
    },
    {
      id: "ts-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say: right and light.",
      promptJa: "right と light を言ってください。",
      ttsText: "right. light.",
      ttsLang: "en-US",
      explanationEn: "Feel the tongue difference between R and L.",
      explanationJa: "R と L で舌の位置を変えて。",
    },
    {
      id: "ts-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The weak vowel in aBOUT / aGENDA is called:",
      promptJa: "about / agenda の弱い母音は？",
      choices: [
        { id: "a", label: "A) Schwa (ə)" },
        { id: "b", label: "B) Long O only" },
        { id: "c", label: "C) Silent letter" },
        { id: "d", label: "D) Katakana" },
      ],
      correctChoiceId: "a",
      explanationEn: "Schwa is the weak 'uh' in unstressed syllables.",
      explanationJa: "schwa（ə）は弱く短い母音です。",
    },
    {
      id: "ts-5",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick the word that starts with English R.",
      promptJa: "英語の R で始まる語は？",
      choices: [
        { id: "a", label: "A) light" },
        { id: "b", label: "B) right" },
        { id: "c", label: "C) night" },
        { id: "d", label: "D) might" },
      ],
      correctChoiceId: "b",
      explanationEn: "right begins with R.",
      explanationJa: "right は R です。",
    },
  ],
};
