import type { LearningUnit } from "@/lib/types";

/** Parallel to Japanese bridge into hiragana: ready for vocab rows. */
export const toeicBridgeUnit: LearningUnit = {
  id: "toeic-before-vocab",
  pathId: "toeic",
  title: "Ready for vocabulary",
  titleJa: "語彙レッスン準備",
  subtitle: "Connect sounds + word building to workplace vocab",
  xpReward: 90,
  tutorial: {
    title: "Same path shape as Japanese Quest",
    titleJa: "日本語クエストと同じ道のり",
    bodyEn:
      "You already practiced phrases, English sounds, and word building. Next rows teach workplace words the same way: Learn each word with spelling help and Listen, then a short quiz (read → write → speak → listen). Exam Parts 1 to 7 come after that foundation.",
    bodyJa:
      "フレーズ・英語の音・語の仕組みを練習しました。次の語彙行も同じ：スペルと Listen で1語ずつ覚えてから短いクイズ（読む→書く→話す→聞く）。そのあと本番 Part 1〜7へ。",
    tips: [
      "Never skip the Learn step on vocab units",
      "Say the English word, then check the Japanese meaning",
      "Reuse Words of the Day every morning",
    ],
  },
  teach: [
    {
      glyph: "agenda",
      reading: "uh-JEN-duh",
      tipEn: "Meeting topic list. Stress on JEN.",
      tipJa: "会議の議題リスト。強勢は JEN。",
      ttsText: "agenda",
      ttsLang: "en-US",
    },
    {
      glyph: "invoice",
      reading: "IN-vois",
      tipEn: "Bill for payment. Stress on IN.",
      tipJa: "請求書。強勢は IN。",
      ttsText: "invoice",
      ttsLang: "en-US",
    },
    {
      glyph: "schedule",
      reading: "SKED-jool",
      tipEn: "Timetable / plan. Common TOEIC noun and verb.",
      tipJa: "予定表。名詞にも動詞にもなる頻出語。",
      ttsText: "schedule",
      ttsLang: "en-US",
    },
    {
      glyph: "available",
      reading: "uh-VAY-luh-bul",
      tipEn: "Free to meet or use. Stress on VAY.",
      tipJa: "空いている／利用できる。強勢は VAY。",
      ttsText: "available",
      ttsLang: "en-US",
    },
    {
      glyph: "reschedule",
      reading: "ree-SKED-jool",
      tipEn: "Change to a new time. re- + schedule.",
      tipJa: "予定を変更する。re + schedule。",
      ttsText: "reschedule",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "tb-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "agenda means:",
      promptJa: "agenda の意味は？",
      choices: [
        { id: "a", label: "A) A payment bill" },
        { id: "b", label: "B) A meeting topic list" },
        { id: "c", label: "C) A holiday" },
        { id: "d", label: "D) A password" },
      ],
      correctChoiceId: "b",
      explanationEn: "agenda = topics for a meeting.",
      explanationJa: "agenda は議題リストです。",
    },
    {
      id: "tb-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which workplace word?",
      promptJa: "聞こえた仕事英語は？",
      ttsText: "invoice",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) invoice" },
        { id: "b", label: "B) advice" },
        { id: "c", label: "C) device" },
        { id: "d", label: "D) invite" },
      ],
      correctChoiceId: "a",
      explanationEn: "invoice = bill for payment.",
      explanationJa: "invoice（請求書）です。",
    },
    {
      id: "tb-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say: Are you available?",
      promptJa: "Are you available? と言ってください。",
      ttsText: "Are you available?",
      ttsLang: "en-US",
      explanationEn: "Stress VAY in available.",
      explanationJa: "available の VAY に強勢。",
    },
    {
      id: "tb-4",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick the word meaning 'change the time'.",
      promptJa: "「予定を変更する」は？",
      choices: [
        { id: "a", label: "A) schedule" },
        { id: "b", label: "B) reschedule" },
        { id: "c", label: "C) agenda" },
        { id: "d", label: "D) invoice" },
      ],
      correctChoiceId: "b",
      explanationEn: "reschedule = schedule again / change the time.",
      explanationJa: "reschedule が予定変更です。",
    },
    {
      id: "tb-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What comes next on this path after START HERE?",
      promptJa: "START HERE の次は？",
      choices: [
        { id: "a", label: "A) Learn + practice workplace VOCAB" },
        { id: "b", label: "B) Only the full 200-question exam" },
        { id: "c", label: "C) Skip to Part 7" },
        { id: "d", label: "D) Stop listening practice" },
      ],
      correctChoiceId: "a",
      explanationEn: "Vocab rows use the same Learn-then-quiz model.",
      explanationJa: "語彙も同じ：Learn → クイズです。",
    },
  ],
};
