import type { LearningUnit } from "@/lib/types";

/** Parallel to Japanese “scripts”: how English words work on TOEIC. */
export const toeicWordSystemsUnit: LearningUnit = {
  id: "toeic-word-systems",
  pathId: "toeic",
  title: "How English words work",
  titleJa: "英単語の仕組み",
  subtitle: "Stress, word families, and workplace word types",
  xpReward: 100,
  tutorial: {
    title: "Build words like building blocks",
    titleJa: "積み木のように語を作る",
    bodyEn:
      "Japanese Quest teaches characters first. Here we teach English word building: stress (de-MAND), families (manage / manager / management), and workplace types (noun vs verb). Learn the ideas with examples, then check.",
    bodyJa:
      "日本語クエストが文字から入るように、ここでは英語の語の仕組みを教えます。強勢（de-MAND）、語族（manage / manager / management）、品詞（名詞と動詞）。例で覚えてから確認します。",
    tips: [
      "Clap the stressed syllable",
      "Guess the part of speech from the ending (-tion, -ment)",
      "Listen for reduced vowels in long words",
    ],
  },
  teach: [
    {
      glyph: "deadline",
      reading: "DED-line",
      tipEn: "Stress on DED. Noun: the due time.",
      tipJa: "強勢は DED。名詞＝締切。",
      ttsText: "deadline",
      ttsLang: "en-US",
    },
    {
      glyph: "manager",
      reading: "MAN-uh-jer",
      tipEn: "manage → manager (person). Stress on MAN.",
      tipJa: "manage → manager（人）。強勢は MAN。",
      ttsText: "manager",
      ttsLang: "en-US",
    },
    {
      glyph: "management",
      reading: "MAN-ij-ment",
      tipEn: "Same family: the system / leadership (noun).",
      tipJa: "同じ語族。経営・管理（名詞）。",
      ttsText: "management",
      ttsLang: "en-US",
    },
    {
      glyph: "confirm",
      reading: "kun-FURM",
      tipEn: "Verb: make sure. Stress on FURM.",
      tipJa: "動詞＝確認する。強勢は FURM。",
      ttsText: "confirm",
      ttsLang: "en-US",
    },
    {
      glyph: "confirmation",
      reading: "kon-fer-MAY-shun",
      tipEn: "Noun form with -tion. Stress moves to MAY.",
      tipJa: "-tion の名詞。強勢は MAY に移動。",
      ttsText: "confirmation",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "tws-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Which is the person who manages?",
      promptJa: "管理する「人」は？",
      choices: [
        { id: "a", label: "A) management" },
        { id: "b", label: "B) manager" },
        { id: "c", label: "C) manage" },
        { id: "d", label: "D) managed" },
      ],
      correctChoiceId: "b",
      explanationEn: "manager = the person.",
      explanationJa: "manager が人です。",
    },
    {
      id: "tws-2",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word did you hear?",
      promptJa: "聞こえた語は？",
      ttsText: "confirmation",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) confirm" },
        { id: "b", label: "B) confirmation" },
        { id: "c", label: "C) conference" },
        { id: "d", label: "D) comfort" },
      ],
      correctChoiceId: "b",
      explanationEn: "confirmation is the noun with -tion.",
      explanationJa: "confirmation（-tion の名詞）です。",
    },
    {
      id: "tws-3",
      kind: "write-choice",
      skill: "write",
      prompt: "Pick the verb meaning 'make sure'.",
      promptJa: "「確認する」の動詞は？",
      choices: [
        { id: "a", label: "A) confirmation" },
        { id: "b", label: "B) deadline" },
        { id: "c", label: "C) confirm" },
        { id: "d", label: "D) manager" },
      ],
      correctChoiceId: "c",
      explanationEn: "confirm is the verb.",
      explanationJa: "confirm が動詞です。",
    },
    {
      id: "tws-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say: deadline (stress DED).",
      promptJa: "deadline（DED に強勢）と言ってください。",
      ttsText: "deadline",
      ttsLang: "en-US",
      explanationEn: "DED-line, not dead-LINE.",
      explanationJa: "DED-line。後ろを強くしすぎない。",
    },
    {
      id: "tws-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "In English word families, -tion usually makes a:",
      promptJa: "-tion が付くとだいたい何になる？",
      choices: [
        { id: "a", label: "A) Noun" },
        { id: "b", label: "B) Past tense only" },
        { id: "c", label: "C) Adjective color" },
        { id: "d", label: "D) Question word" },
      ],
      correctChoiceId: "a",
      explanationEn: "-tion words are usually nouns (confirmation, reservation).",
      explanationJa: "-tion はだいたい名詞です。",
    },
  ],
};
