import type { LearningUnit } from "@/lib/types";

/** Phase B2: Prepositions & collocations */
export const toeicGrammarPrepositionsUnit: LearningUnit = {
  id: "toeic-grammar-prepositions",
  pathId: "toeic",
  title: "GRAMMAR: Prepositions",
  titleJa: "文法：前置詞・コロケーション",
  subtitle: "responsible for, by Friday, interested in",
  examPart: "GRAMMAR",
  xpReward: 110,
  tutorial: {
    title: "Memorize pairs, not single words",
    titleJa: "単語ではなくペアで覚える",
    bodyEn:
      "Part 5 loves fixed pairs: responsible for, apply for, interested in, by Friday, on time. Learn the collocation, then choose the preposition.",
    bodyJa:
      "Part 5は固定ペアが好きです（responsible for, apply for, interested in, by Friday, on time）。コロケーションを覚えてから前置詞を選びます。",
    tips: [
      "responsible for + noun / -ing",
      "by = deadline; until = continuing up to a time",
      "interested in / good at / look forward to",
    ],
  },
  teach: [
    {
      glyph: "responsible for",
      reading: "rih-SPON-suh-bul for",
      tipEn: "Always for after responsible when naming a duty.",
      tipJa: "責任の対象は responsible for。",
      ttsText: "responsible for",
      ttsLang: "en-US",
    },
    {
      glyph: "by Friday",
      reading: "deadline by",
      tipEn: "by Friday = no later than Friday.",
      tipJa: "by Friday＝金曜までに。",
      ttsText: "by Friday",
      ttsLang: "en-US",
    },
    {
      glyph: "interested in",
      reading: "IN-tres-tid in",
      tipEn: "interested in + noun / -ing.",
      tipJa: "interested in + 名詞／動名詞。",
      ttsText: "interested in",
      ttsLang: "en-US",
    },
    {
      glyph: "apply for",
      reading: "uh-PLY for",
      tipEn: "apply for a job / position / visa.",
      tipJa: "apply for a job（職に応募する）。",
      ttsText: "apply for",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "g-prep-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Ms. Park is responsible _______ training new staff.",
      promptJa: "パクさんは新人研修を担当しています。",
      choices: [
        { id: "a", label: "A) to" },
        { id: "b", label: "B) for" },
        { id: "c", label: "C) of" },
        { id: "d", label: "D) with" },
      ],
      correctChoiceId: "b",
      explanationEn: "responsible for + -ing / noun.",
      explanationJa: "responsible for + 動名詞／名詞。",
    },
    {
      id: "g-prep-2",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Please submit the form _______ Monday at noon.",
      promptJa: "月曜正午までにフォームを提出してください。",
      choices: [
        { id: "a", label: "A) by" },
        { id: "b", label: "B) since" },
        { id: "c", label: "C) during" },
        { id: "d", label: "D) between" },
      ],
      correctChoiceId: "a",
      explanationEn: "by marks the latest allowed time.",
      explanationJa: "by は期限（それまでに）を表します。",
    },
    {
      id: "g-prep-3",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Many applicants are interested _______ remote positions.",
      promptJa: "多くの応募者がリモート職に関心を持っています。",
      choices: [
        { id: "a", label: "A) on" },
        { id: "b", label: "B) in" },
        { id: "c", label: "C) at" },
        { id: "d", label: "D) for" },
      ],
      correctChoiceId: "b",
      explanationEn: "interested in + noun.",
      explanationJa: "interested in + 名詞。",
    },
    {
      id: "g-prep-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "He decided to apply _______ the marketing manager role.",
      promptJa: "彼はマーケ責任者の職に応募することにしました。",
      choices: [
        { id: "a", label: "A) to" },
        { id: "b", label: "B) for" },
        { id: "c", label: "C) at" },
        { id: "d", label: "D) with" },
      ],
      correctChoiceId: "b",
      explanationEn: "apply for a job / role.",
      explanationJa: "apply for a job。",
    },
    {
      id: "g-prep-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The package arrived _______ time for the client meeting.",
      promptJa: "荷物は顧客ミーティングに間に合うよう届きました。",
      choices: [
        { id: "a", label: "A) on" },
        { id: "b", label: "B) in" },
        { id: "c", label: "C) at" },
        { id: "d", label: "D) by" },
      ],
      correctChoiceId: "a",
      explanationEn: "on time = not late.",
      explanationJa: "on time＝時間どおり。",
    },
    {
      id: "g-prep-6",
      kind: "multiple-choice",
      skill: "read",
      prompt: "We look forward _______ your reply next week.",
      promptJa: "来週のご返信を楽しみにしています。",
      choices: [
        { id: "a", label: "A) to" },
        { id: "b", label: "B) for" },
        { id: "c", label: "C) of" },
        { id: "d", label: "D) at" },
      ],
      correctChoiceId: "a",
      explanationEn: "look forward to + noun / -ing.",
      explanationJa: "look forward to + 名詞／動名詞。",
    },
    {
      id: "g-prep-7",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The cafe is located _______ the corner of 5th and Oak.",
      promptJa: "そのカフェは5丁目とオーク通りの角にあります。",
      choices: [
        { id: "a", label: "A) in" },
        { id: "b", label: "B) on" },
        { id: "c", label: "C) at" },
        { id: "d", label: "D) by" },
      ],
      correctChoiceId: "b",
      explanationEn: "on the corner is the usual collocation.",
      explanationJa: "on the corner が一般的です。",
    },
    {
      id: "g-prep-8",
      kind: "multiple-choice",
      skill: "read",
      prompt: "She is good _______ explaining complex policies simply.",
      promptJa: "彼女は複雑な方針を分かりやすく説明するのが得意です。",
      choices: [
        { id: "a", label: "A) in" },
        { id: "b", label: "B) at" },
        { id: "c", label: "C) on" },
        { id: "d", label: "D) for" },
      ],
      correctChoiceId: "b",
      explanationEn: "good at + -ing.",
      explanationJa: "good at + 動名詞。",
    },
  ],
};
