import type { LearningUnit } from "@/lib/types";

/** Phase B1: Word forms (noun / verb / adj / adv) */
export const toeicGrammarWordFormsUnit: LearningUnit = {
  id: "toeic-grammar-word-forms",
  pathId: "toeic",
  title: "GRAMMAR: Word forms",
  titleJa: "文法：品詞（語形）",
  subtitle: "Noun / verb / adjective / adverb for Part 5",
  examPart: "GRAMMAR",
  xpReward: 110,
  tutorial: {
    title: "Pick the right part of speech",
    titleJa: "正しい品詞を選ぶ",
    bodyEn:
      "Part 5 often tests word families: decide / decision / decisive / decisively. Learn the pattern with examples, then practice incomplete sentences.",
    bodyJa:
      "Part 5では語族がよく出ます（decide / decision / decisive / decisively）。例で型を覚えてから空所補充へ。",
    tips: [
      "Check what the blank needs: noun, verb, adj, or adv",
      "Endings help: -tion/-ment (noun), -ive/-al (adj), -ly (adv)",
      "After will/can/should use the base verb",
    ],
  },
  teach: [
    {
      glyph: "decide → decision",
      reading: "verb → noun",
      tipEn: "After the / a / this you often need a noun: a decision.",
      tipJa: "the / a / this のあとは名詞が多い：a decision。",
      ttsText: "decision",
      ttsLang: "en-US",
    },
    {
      glyph: "success → successful",
      reading: "noun → adjective",
      tipEn: "Before a noun use adjective: a successful meeting.",
      tipJa: "名詞の前は形容詞：a successful meeting。",
      ttsText: "successful",
      ttsLang: "en-US",
    },
    {
      glyph: "quick → quickly",
      reading: "adjective → adverb",
      tipEn: "Modify a verb with -ly: please respond quickly.",
      tipJa: "動詞を修飾するなら -ly：respond quickly。",
      ttsText: "quickly",
      ttsLang: "en-US",
    },
    {
      glyph: "will + base verb",
      reading: "modal pattern",
      tipEn: "After will / can / should use present base: will present.",
      tipJa: "will / can / should のあとは原形：will present。",
      ttsText: "will present",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "g-wf-1",
      kind: "multiple-choice",
      skill: "read",
      prompt:
        "The board will _______ a final decision after reviewing the proposal.",
      promptJa: "取締役会は提案を検討したあと最終決定を___します。",
      choices: [
        { id: "a", label: "A) announce" },
        { id: "b", label: "B) announcement" },
        { id: "c", label: "C) announced" },
        { id: "d", label: "D) announcing" },
      ],
      correctChoiceId: "a",
      explanationEn: "After will you need the base verb announce.",
      explanationJa: "will のあとは動詞の原形 announce。",
    },
    {
      id: "g-wf-2",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Her _______ of the data helped the team choose a vendor.",
      promptJa: "彼女のデータの___が、業者選定に役立ちました。",
      choices: [
        { id: "a", label: "A) analyze" },
        { id: "b", label: "B) analysis" },
        { id: "c", label: "C) analytical" },
        { id: "d", label: "D) analytically" },
      ],
      correctChoiceId: "b",
      explanationEn: "After her you need a noun: analysis.",
      explanationJa: "her のあとは名詞 analysis。",
    },
    {
      id: "g-wf-3",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Please speak _______ so everyone in the hall can hear.",
      promptJa: "会場の全員に聞こえるよう、___話してください。",
      choices: [
        { id: "a", label: "A) clear" },
        { id: "b", label: "B) clarity" },
        { id: "c", label: "C) clearly" },
        { id: "d", label: "D) cleared" },
      ],
      correctChoiceId: "c",
      explanationEn: "Modify the verb speak with the adverb clearly.",
      explanationJa: "動詞 speak を修飾する副詞 clearly。",
    },
    {
      id: "g-wf-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Nova Soft had a _______ year despite higher shipping costs.",
      promptJa: "配送費が上がったにもかかわらず、Nova Softは___年でした。",
      choices: [
        { id: "a", label: "A) profit" },
        { id: "b", label: "B) profitable" },
        { id: "c", label: "C) profitably" },
        { id: "d", label: "D) profited" },
      ],
      correctChoiceId: "b",
      explanationEn: "Before year you need an adjective: profitable.",
      explanationJa: "year の前は形容詞 profitable。",
    },
    {
      id: "g-wf-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "We need your _______ before Friday morning.",
      promptJa: "金曜の朝までにあなたの___が必要です。",
      choices: [
        { id: "a", label: "A) approve" },
        { id: "b", label: "B) approval" },
        { id: "c", label: "C) approvingly" },
        { id: "d", label: "D) approved" },
      ],
      correctChoiceId: "b",
      explanationEn: "After your you need a noun: approval.",
      explanationJa: "your のあとは名詞 approval。",
    },
    {
      id: "g-wf-6",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The new software runs more _______ than the old system.",
      promptJa: "新ソフトは旧システムより___動作します。",
      choices: [
        { id: "a", label: "A) efficient" },
        { id: "b", label: "B) efficiency" },
        { id: "c", label: "C) efficiently" },
        { id: "d", label: "D) efficiencies" },
      ],
      correctChoiceId: "c",
      explanationEn: "Compare how it runs: adverb efficiently.",
      explanationJa: "動作の様子を表す副詞 efficiently。",
    },
    {
      id: "g-wf-7",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Ms. Chen gave a short _______ on safety rules.",
      promptJa: "チェンさんは安全規則について短い___をしました。",
      choices: [
        { id: "a", label: "A) present" },
        { id: "b", label: "B) presentation" },
        { id: "c", label: "C) presently" },
        { id: "d", label: "D) presented" },
      ],
      correctChoiceId: "b",
      explanationEn: "After a short you need a noun: presentation.",
      explanationJa: "a short のあとは名詞 presentation。",
    },
    {
      id: "g-wf-8",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Applicants should _______ the form carefully before submitting.",
      promptJa: "応募者は提出前にフォームを注意深く___すべきです。",
      choices: [
        { id: "a", label: "A) complete" },
        { id: "b", label: "B) completion" },
        { id: "c", label: "C) completely" },
        { id: "d", label: "D) completed" },
      ],
      correctChoiceId: "a",
      explanationEn: "After should you need the base verb complete.",
      explanationJa: "should のあとは原形 complete。",
    },
  ],
};
