import type { LearningUnit } from "@/lib/types";

/** Phase B3: Conjunctions & transitions */
export const toeicGrammarConjunctionsUnit: LearningUnit = {
  id: "toeic-grammar-conjunctions",
  pathId: "toeic",
  title: "GRAMMAR: Conjunctions",
  titleJa: "文法：接続詞・つなぎ語",
  subtitle: "however, therefore, due to, although",
  examPart: "GRAMMAR",
  xpReward: 110,
  tutorial: {
    title: "Link ideas the Part 5 / 6 way",
    titleJa: "Part 5・6のつなぎ方",
    bodyEn:
      "Choose connectors by meaning and grammar: due to + noun, because + clause, although = contrast, therefore = result. Learn the patterns, then practice.",
    bodyJa:
      "意味と文法でつなぎ語を選びます。due to + 名詞、because + 節、although＝対比、therefore＝結果。型を覚えてから練習へ。",
    tips: [
      "due to / because of + noun phrase",
      "because / although + full clause",
      "however / therefore often need a comma or new clause",
    ],
  },
  teach: [
    {
      glyph: "due to",
      reading: "doo too + noun",
      tipEn: "due to the delay (noun). Not due to we were late.",
      tipJa: "due to + 名詞。節は続けない。",
      ttsText: "due to the delay",
      ttsLang: "en-US",
    },
    {
      glyph: "although",
      reading: "awl-THOH",
      tipEn: "although + clause: Although it rained, we opened.",
      tipJa: "although + 節。",
      ttsText: "although",
      ttsLang: "en-US",
    },
    {
      glyph: "therefore",
      reading: "THER-for",
      tipEn: "therefore shows result: Sales fell; therefore we cut costs.",
      tipJa: "therefore＝だから（結果）。",
      ttsText: "therefore",
      ttsLang: "en-US",
    },
    {
      glyph: "however",
      reading: "how-EV-er",
      tipEn: "however shows contrast, often after a period or semicolon.",
      tipJa: "however＝しかし（対比）。",
      ttsText: "however",
      ttsLang: "en-US",
    },
  ],
  exercises: [
    {
      id: "g-conj-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "_______ the storm, several flights were delayed.",
      promptJa: "嵐のため、いくつかの便が遅れました。",
      choices: [
        { id: "a", label: "A) Because" },
        { id: "b", label: "B) Due to" },
        { id: "c", label: "C) Although" },
        { id: "d", label: "D) Unless" },
      ],
      correctChoiceId: "b",
      explanationEn: "due to + noun phrase (the storm).",
      explanationJa: "due to + 名詞句。",
    },
    {
      id: "g-conj-2",
      kind: "multiple-choice",
      skill: "read",
      prompt: "_______ the price rose, demand stayed strong.",
      promptJa: "価格が上がったにもかかわらず、需要は堅調でした。",
      choices: [
        { id: "a", label: "A) Because" },
        { id: "b", label: "B) Therefore" },
        { id: "c", label: "C) Although" },
        { id: "d", label: "D) Due to" },
      ],
      correctChoiceId: "c",
      explanationEn: "although + clause shows contrast.",
      explanationJa: "although + 節で対比。",
    },
    {
      id: "g-conj-3",
      kind: "multiple-choice",
      skill: "read",
      prompt:
        "Costs increased sharply; _______, the firm postponed hiring.",
      promptJa: "コストが急増した。___、採用を延期した。",
      choices: [
        { id: "a", label: "A) however" },
        { id: "b", label: "B) therefore" },
        { id: "c", label: "C) although" },
        { id: "d", label: "D) despite" },
      ],
      correctChoiceId: "b",
      explanationEn: "therefore shows a result.",
      explanationJa: "therefore は結果。",
    },
    {
      id: "g-conj-4",
      kind: "multiple-choice",
      skill: "read",
      prompt: "The lobby is open late. _______, the cafe closes at 6 p.m.",
      promptJa: "ロビーは遅くまで開いている。___、カフェは午後6時閉店。",
      choices: [
        { id: "a", label: "A) Therefore" },
        { id: "b", label: "B) However" },
        { id: "c", label: "C) Because" },
        { id: "d", label: "D) Due to" },
      ],
      correctChoiceId: "b",
      explanationEn: "however marks contrast between two facts.",
      explanationJa: "however は対比。",
    },
    {
      id: "g-conj-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "_______ you finish the report, please email the file to me.",
      promptJa: "レポートが終わったら、ファイルをメールしてください。",
      choices: [
        { id: "a", label: "A) When" },
        { id: "b", label: "B) During" },
        { id: "c", label: "C) Despite" },
        { id: "d", label: "D) Due to" },
      ],
      correctChoiceId: "a",
      explanationEn: "when + clause for time.",
      explanationJa: "when + 節で時を表す。",
    },
    {
      id: "g-conj-6",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Sales grew _______ higher ad spending this quarter.",
      promptJa: "今四半期は広告費増の___売上が伸びた。",
      choices: [
        { id: "a", label: "A) because" },
        { id: "b", label: "B) because of" },
        { id: "c", label: "C) although" },
        { id: "d", label: "D) however" },
      ],
      correctChoiceId: "b",
      explanationEn: "because of + noun phrase.",
      explanationJa: "because of + 名詞句。",
    },
    {
      id: "g-conj-7",
      kind: "multiple-choice",
      skill: "read",
      prompt: "_______ the rain, the outdoor event continued as planned.",
      promptJa: "雨___、屋外イベントは予定どおり続いた。",
      choices: [
        { id: "a", label: "A) Because" },
        { id: "b", label: "B) Despite" },
        { id: "c", label: "C) Therefore" },
        { id: "d", label: "D) Unless" },
      ],
      correctChoiceId: "b",
      explanationEn: "despite + noun shows contrast without a clause.",
      explanationJa: "despite + 名詞で対比。",
    },
    {
      id: "g-conj-8",
      kind: "multiple-choice",
      skill: "read",
      prompt: "Call the help desk _______ the printer still fails after reboot.",
      promptJa: "再起動後もプリンタが動かない___ヘルプデスクに連絡して。",
      choices: [
        { id: "a", label: "A) if" },
        { id: "b", label: "B) during" },
        { id: "c", label: "C) despite" },
        { id: "d", label: "D) due to" },
      ],
      correctChoiceId: "a",
      explanationEn: "if + clause for a condition.",
      explanationJa: "if + 節で条件。",
    },
  ],
};
