import type { LearningUnit } from "@/lib/types";

export const toeicPart3Unit: LearningUnit = {
  id: "toeic-l3-conversations",
  pathId: "toeic",
  title: "Listening Part 3",
  titleJa: "リスニング Part 3",
  subtitle: "Official skill: Conversations (Listening Part 3)",
  examPart: "L3",
  xpReward: 130,
  tutorial: {
    title: "Real TOEIC Part 3",
    titleJa: "本番の Part 3",
    bodyEn:
      "Official Part 3 has 39 questions: 13 conversations with 3 questions each. Questions appear in the test book. Skills tested: gist, detail, inference, and speaker intent in workplace dialogues. Lumi drills one conversation focus at a time with original scripts.",
    bodyJa:
      "公式Part 3は39問（会話13×各3問）。設問は問題用紙に印刷されます。職場会話の主旨・詳細・推論・意図が問われます。Lumiはオリジナル台本で一点集中ドリルします。",
    tips: [
      "Preview the three questions before the audio when you can",
      "Track names, times, places, and next steps",
      "Use the final lines for follow-up actions",
    ],
  },
  exercises: [
    {
      id: "l3-1",
      kind: "listen-choice",
      prompt: "Why is the woman calling?",
      promptJa: "女性が電話した理由は？",
      ttsText:
        "Man: Accounting, Ken speaking. Woman: Hi Ken, this is Mai from sales. I'm calling to confirm whether the Q3 invoices were sent to Horizon Corp.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) To apply for a job" },
        { id: "b", label: "B) To confirm invoices were sent" },
        { id: "c", label: "C) To cancel a meeting" },
        { id: "d", label: "D) To order office supplies" },
      ],
      correctChoiceId: "b",
      explanationEn: "She says she is calling to confirm the invoices were sent.",
      explanationJa: "請求書送付の確認のために電話した、と言っています。",
    },
    {
      id: "l3-2",
      kind: "listen-choice",
      prompt: "Where will they meet?",
      promptJa: "どこで会いますか？",
      ttsText:
        "Woman: Can we discuss the venue options today? Man: Sure. Let's meet in the second-floor lounge at three.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) In the parking garage" },
        { id: "b", label: "B) In the second-floor lounge" },
        { id: "c", label: "C) At the client's factory" },
        { id: "d", label: "D) In the cafeteria kitchen" },
      ],
      correctChoiceId: "b",
      explanationEn: "He proposes the second-floor lounge at three.",
      explanationJa: "2階ラウンジで3時、と提案しています。",
    },
    {
      id: "l3-3",
      kind: "listen-choice",
      prompt: "What will the man do next?",
      promptJa: "男性が次にすることは？",
      ttsText:
        "Woman: The printer on floor four is jammed again. Man: I'll go reset it and replace the paper tray.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Call a taxi" },
        { id: "b", label: "B) Fix the printer" },
        { id: "c", label: "C) Book a hotel" },
        { id: "d", label: "D) Update the website" },
      ],
      correctChoiceId: "b",
      explanationEn: "He will reset the printer and replace the paper tray.",
      explanationJa: "プリンターをリセットして用紙トレイを替える、と言っています。",
    },
    {
      id: "l3-4",
      kind: "listen-choice",
      prompt: "What is the problem?",
      promptJa: "問題は何ですか？",
      ttsText:
        "Man: Did the samples arrive? Woman: Not yet. The courier said the package is delayed until Thursday.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) The samples are delayed" },
        { id: "b", label: "B) The office is closed" },
        { id: "c", label: "C) The price is too high" },
        { id: "d", label: "D) The meeting room is booked" },
      ],
      correctChoiceId: "a",
      explanationEn: "The package with samples is delayed until Thursday.",
      explanationJa: "サンプルの荷物が木曜まで遅れる、とあります。",
    },
    {
      id: "l3-5",
      kind: "listen-choice",
      prompt: "What does the woman suggest?",
      promptJa: "女性の提案は？",
      ttsText:
        "Man: Traffic looks heavy. We might miss the 9 a.m. kickoff. Woman: Let's take the subway. It should be faster this morning.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Cancel the kickoff" },
        { id: "b", label: "B) Take the subway" },
        { id: "c", label: "C) Work from home" },
        { id: "d", label: "D) Rent a larger car" },
      ],
      correctChoiceId: "b",
      explanationEn: "She suggests taking the subway because it should be faster.",
      explanationJa: "地下鉄の方が早いので地下鉄で行こう、と提案しています。",
    },
    {
      id: "l3-6",
      kind: "listen-choice",
      prompt: "What does the man want the woman to do?",
      promptJa: "男性が女性にしてほしいことは？",
      ttsText:
        "Man: Could you forward the client brief to the design team? Woman: Sure. I'll send it as soon as the meeting ends.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Cancel the design meeting" },
        { id: "b", label: "B) Forward the client brief" },
        { id: "c", label: "C) Print new business cards" },
        { id: "d", label: "D) Book a flight for the client" },
      ],
      correctChoiceId: "b",
      explanationEn: "He asks her to forward the client brief to the design team.",
      explanationJa: "クライアント概要をデザインチームに転送してほしい、と頼んでいます。",
    },
    {
      id: "l3-7",
      kind: "listen-choice",
      prompt: "When is the deadline?",
      promptJa: "締切はいつですか？",
      ttsText:
        "Woman: When do we need the revised slides? Man: The director wants them on her desk by Wednesday noon.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Monday evening" },
        { id: "b", label: "B) Wednesday noon" },
        { id: "c", label: "C) Friday morning" },
        { id: "d", label: "D) Next month" },
      ],
      correctChoiceId: "b",
      explanationEn: "He says the director wants the slides by Wednesday noon.",
      explanationJa: "水曜正午までにスライドが必要、と言っています。",
    },
    {
      id: "l3-8",
      kind: "listen-choice",
      prompt: "Why is the man concerned?",
      promptJa: "男性が心配している理由は？",
      ttsText:
        "Woman: The guest speaker confirmed for Friday. Man: That's good, but I'm worried the projector in Hall C still isn't working.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) The guest canceled the talk" },
        { id: "b", label: "B) The projector may not work" },
        { id: "c", label: "C) The hall is too small" },
        { id: "d", label: "D) The tickets are sold out" },
      ],
      correctChoiceId: "b",
      explanationEn: "He is worried that the projector in Hall C still is not working.",
      explanationJa: "Cホールのプロジェクターがまだ動かないと心配しています。",
    },
    {
      id: "l3-9",
      kind: "listen-choice",
      prompt: "What will they do about the order?",
      promptJa: "注文についてどうしますか？",
      ttsText:
        "Man: We ordered too many folders. Woman: Let's return the extras and keep only two boxes for the workshop.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Order more folders" },
        { id: "b", label: "B) Return the extras" },
        { id: "c", label: "C) Cancel the workshop" },
        { id: "d", label: "D) Donate all supplies today" },
      ],
      correctChoiceId: "b",
      explanationEn: "She suggests returning the extras and keeping two boxes.",
      explanationJa: "余分な分を返品し、2箱だけ残そう、と提案しています。",
    },
    {
      id: "l3-10",
      kind: "listen-choice",
      prompt: "Where is the temporary office?",
      promptJa: "仮オフィスはどこですか？",
      ttsText:
        "Woman: Our floor is closed for painting. Man: HR said we can work from the temporary office next to the mailroom until Thursday.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Next to the mailroom" },
        { id: "b", label: "B) Across from the cafeteria" },
        { id: "c", label: "C) On the roof terrace" },
        { id: "d", label: "D) At the client's factory" },
      ],
      correctChoiceId: "a",
      explanationEn: "HR said the temporary office is next to the mailroom.",
      explanationJa: "仮オフィスはメールルームの隣、とあります。",
    },
  ],
};
