import type { LearningUnit } from "@/lib/types";

export const toeicPart4Unit: LearningUnit = {
  id: "toeic-l4-talks",
  pathId: "toeic",
  title: "Listening Part 4",
  titleJa: "リスニング Part 4",
  subtitle: "Official skill: Talks (Listening Part 4)",
  examPart: "L4",
  xpReward: 130,
  tutorial: {
    title: "Real TOEIC Part 4",
    titleJa: "本番の Part 4",
    bodyEn:
      "Official Part 4 has 30 questions: 10 short talks with 3 questions each. Formats include announcements, excerpts, ads, and voicemail. Questions are printed. Train purpose, detail, and implied next action. Note: standard TOEIC L&R does not score speaking or writing; those are a separate TOEIC Speaking and Writing test.",
    bodyJa:
      "公式Part 4は30問（トーク10×各3問）。アナウンス・抜粋・広告・留守電など。設問は印刷あり。目的・詳細・次の行動を鍛えます。なお標準のTOEIC L&Rにスピーキング／ライティング採点はなく、それらは別試験（S&W）です。",
    tips: [
      "The first sentence often states the purpose",
      "Capture numbers, dates, and locations",
      "Listen for what the audience should do next",
    ],
  },
  exercises: [
    {
      id: "l4-1",
      kind: "listen-choice",
      prompt: "What is the purpose of the announcement?",
      promptJa: "アナウンスの目的は？",
      ttsText:
        "Attention passengers. The 10:15 express to Kyoto will depart from track 5 instead of track 2. Please move to track 5.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) To sell train tickets" },
        { id: "b", label: "B) To change the departure track" },
        { id: "c", label: "C) To cancel all express trains" },
        { id: "d", label: "D) To introduce a new station cafe" },
      ],
      correctChoiceId: "b",
      explanationEn: "Listeners must move because the train now leaves from track 5.",
      explanationJa: "発車番線が5番に変わったので移動するよう案内しています。",
    },
    {
      id: "l4-2",
      kind: "listen-choice",
      prompt: "Who is this message for?",
      promptJa: "この案内の対象は？",
      ttsText:
        "Good morning staff. Please submit your vacation requests for August by Friday so managers can finalize schedules.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Hotel guests" },
        { id: "b", label: "B) Company staff" },
        { id: "c", label: "C) Delivery drivers only" },
        { id: "d", label: "D) New customers" },
      ],
      correctChoiceId: "b",
      explanationEn: "It addresses staff about vacation requests.",
      explanationJa: "社員向けに休暇申請の案内をしています。",
    },
    {
      id: "l4-3",
      kind: "listen-choice",
      prompt: "What discount is offered?",
      promptJa: "割引はいくら？",
      ttsText:
        "This week only, Green Leaf Market is offering 20 percent off all fresh produce for members. Join at the service desk.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) 10 percent off electronics" },
        { id: "b", label: "B) 20 percent off fresh produce for members" },
        { id: "c", label: "C) Buy one get one free on all items" },
        { id: "d", label: "D) Free shipping on furniture" },
      ],
      correctChoiceId: "b",
      explanationEn: "Members get 20 percent off fresh produce this week.",
      explanationJa: "会員は生鮮食品が20%オフです。",
    },
    {
      id: "l4-4",
      kind: "listen-choice",
      prompt: "When does the workshop begin?",
      promptJa: "ワークショップはいつ始まる？",
      ttsText:
        "Welcome to the safety workshop. We will begin at 1:30 in Room B after a short equipment check.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) At noon in Room A" },
        { id: "b", label: "B) At 1:30 in Room B" },
        { id: "c", label: "C) At 3:00 online" },
        { id: "d", label: "D) Tomorrow morning" },
      ],
      correctChoiceId: "b",
      explanationEn: "It starts at 1:30 in Room B.",
      explanationJa: "B室で1時半開始です。",
    },
    {
      id: "l4-5",
      kind: "listen-choice",
      prompt: "What should listeners do?",
      promptJa: "聞き手は何をすべき？",
      ttsText:
        "Due to maintenance, the east elevator is closed until Monday. Please use the west elevator or the stairs.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Avoid the building entirely" },
        { id: "b", label: "B) Use the west elevator or stairs" },
        { id: "c", label: "C) Call security immediately" },
        { id: "d", label: "D) Wait for a shuttle bus" },
      ],
      correctChoiceId: "b",
      explanationEn: "They should use the west elevator or the stairs.",
      explanationJa: "西エレベーターか階段を使うよう案内されています。",
    },
    {
      id: "l4-6",
      kind: "listen-choice",
      prompt: "What is the main purpose of this message?",
      promptJa: "この伝言の主な目的は？",
      ttsText:
        "Hello, this is Priya from Apex Logistics. I'm calling to let you know your delivery is scheduled for tomorrow between 9 and 11 a.m. Please keep the loading dock clear.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) To confirm a delivery time" },
        { id: "b", label: "B) To cancel a warehouse lease" },
        { id: "c", label: "C) To hire a new driver" },
        { id: "d", label: "D) To advertise a sale" },
      ],
      correctChoiceId: "a",
      explanationEn: "The caller confirms a delivery window for tomorrow morning.",
      explanationJa: "翌朝の配達時間帯を伝える留守電です。",
    },
    {
      id: "l4-7",
      kind: "listen-choice",
      prompt: "Where should listeners go?",
      promptJa: "聞き手はどこへ行くべき？",
      ttsText:
        "Attention visitors. The registration desk has moved to the second-floor atrium. Please proceed there to collect your badges before entering the exhibit hall.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) To the parking garage" },
        { id: "b", label: "B) To the second-floor atrium" },
        { id: "c", label: "C) To the hotel restaurant" },
        { id: "d", label: "D) To the train station" },
      ],
      correctChoiceId: "b",
      explanationEn: "Registration is now in the second-floor atrium.",
      explanationJa: "受付は2階アトリウムに移った、と案内しています。",
    },
    {
      id: "l4-8",
      kind: "listen-choice",
      prompt: "What special offer is mentioned?",
      promptJa: "どんな特別オファー？",
      ttsText:
        "At Harbor Bookstore this weekend, buy any two business titles and receive a free tote bag. Offer valid while supplies last.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Free shipping on all books" },
        { id: "b", label: "B) A free tote bag with two business titles" },
        { id: "c", label: "C) Half price on all magazines" },
        { id: "d", label: "D) Free coffee with every purchase" },
      ],
      correctChoiceId: "b",
      explanationEn: "Buying two business titles gets you a free tote bag.",
      explanationJa: "ビジネス書を2冊買うとトートバッグが無料です。",
    },
    {
      id: "l4-9",
      kind: "listen-choice",
      prompt: "Why is the cafeteria closed?",
      promptJa: "カフェテリアが閉まっている理由は？",
      ttsText:
        "Good afternoon. The staff cafeteria will be closed on Tuesday for a health inspection. Please use the food trucks in the courtyard or bring lunch from home.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) For a company party" },
        { id: "b", label: "B) For a health inspection" },
        { id: "c", label: "C) Because of a power outage" },
        { id: "d", label: "D) Because of a holiday" },
      ],
      correctChoiceId: "b",
      explanationEn: "It will be closed on Tuesday for a health inspection.",
      explanationJa: "火曜は衛生検査のため閉鎖です。",
    },
    {
      id: "l4-10",
      kind: "listen-choice",
      prompt: "What should employees do before Friday?",
      promptJa: "金曜までに社員は何をすべき？",
      ttsText:
        "Reminder to all employees: please update your emergency contact information in the HR portal before Friday. Incomplete profiles may delay badge renewals.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Renew their parking permits" },
        { id: "b", label: "B) Update emergency contacts in the HR portal" },
        { id: "c", label: "C) Attend a fire drill downtown" },
        { id: "d", label: "D) Return all borrowed laptops" },
      ],
      correctChoiceId: "b",
      explanationEn: "They must update emergency contact information before Friday.",
      explanationJa: "金曜までに緊急連絡先をHRポータルで更新するよう求めています。",
    },
  ],
};
