import type { LearningUnit } from "@/lib/types";

export const toeicPart2Unit: LearningUnit = {
  id: "toeic-l2-question-response",
  pathId: "toeic",
  title: "Listening Part 2",
  titleJa: "リスニング Part 2",
  subtitle: "Official skill: Question-Response (Listening Part 2)",
  examPart: "L2",
  xpReward: 110,
  tutorial: {
    title: "Real TOEIC Part 2",
    titleJa: "本番の Part 2",
    bodyEn:
      "Official Part 2 has 25 questions. You hear a question or statement, then three responses (A, B, C). Nothing is printed. Pick the natural reply. Common traps reuse a word from the question but answer the wrong question type (where vs when, who vs what).",
    bodyJa:
      "公式Part 2は25問。質問／発言のあと応答が3つ（A〜C）。印刷なし。自然な返事を選びます。同じ語を繰り返すが疑問の種類がずれるひっかけに注意。",
    tips: [
      "Classify: wh-, yes/no, choice, or statement",
      "Reject same-word traps that miss the question",
      "Short answers are often correct",
    ],
  },
  exercises: [
    {
      id: "l2-1",
      kind: "listen-choice",
      prompt: "Listen to the question. Choose the best response.",
      promptJa: "質問を聞いて、最も良い応答を選ぶ。",
      ttsText: "Where is the meeting room?",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) At 2 o'clock." },
        { id: "b", label: "B) On the third floor." },
        { id: "c", label: "C) With Mr. Tanaka." },
        { id: "d", label: "D) Because it was canceled." },
      ],
      correctChoiceId: "b",
      explanationEn: "'Where' asks for a place. 'On the third floor' answers it.",
      explanationJa: "Where は場所を尋ねます。3階、が答えです。",
    },
    {
      id: "l2-2",
      kind: "listen-choice",
      prompt: "Choose the natural reply.",
      promptJa: "自然な応答を選んでください。",
      ttsText: "Have you finished the report?",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Yes, I emailed it this morning." },
        { id: "b", label: "B) It's about twenty pages." },
        { id: "c", label: "C) The printer is near the window." },
        { id: "d", label: "D) Next Tuesday works for me." },
      ],
      correctChoiceId: "a",
      explanationEn: "A yes/no question about finishing needs a completion answer.",
      explanationJa: "終えたかどうかの Yes/No に対する応答が A です。",
    },
    {
      id: "l2-3",
      kind: "listen-choice",
      prompt: "Best response?",
      promptJa: "最も良い返事は？",
      ttsText: "Who will present the budget update?",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) In the main conference hall." },
        { id: "b", label: "B) Sara from finance." },
        { id: "c", label: "C) Around 15 percent higher." },
        { id: "d", label: "D) Please print five copies." },
      ],
      correctChoiceId: "b",
      explanationEn: "'Who' needs a person. Sara from finance fits.",
      explanationJa: "Who には人が答え。経理のSaraが適切です。",
    },
    {
      id: "l2-4",
      kind: "listen-choice",
      prompt: "Listen and reply.",
      promptJa: "聞いて応答を選ぶ。",
      ttsText: "Could you send me the client list?",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Sure, I'll share it after lunch." },
        { id: "b", label: "B) The list is alphabetical." },
        { id: "c", label: "C) Clients prefer morning calls." },
        { id: "d", label: "D) We met them last April." },
      ],
      correctChoiceId: "a",
      explanationEn: "A request with 'could you' expects agreement or a plan.",
      explanationJa: "Could you の依頼には承諾や予定の返答が自然です。",
    },
    {
      id: "l2-5",
      kind: "listen-choice",
      prompt: "Pick the best answer.",
      promptJa: "最善の答えを選ぶ。",
      ttsText: "When does the flight arrive?",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Gate 12." },
        { id: "b", label: "B) Around 6:40 p.m." },
        { id: "c", label: "C) Economy class." },
        { id: "d", label: "D) Yes, I have a ticket." },
      ],
      correctChoiceId: "b",
      explanationEn: "'When' asks for a time. 6:40 p.m. answers it.",
      explanationJa: "When は時を尋ねます。午後6時40分頃が答えです。",
    },
  ],
};
