import type { LearningUnit } from "@/lib/types";

export const toeicPart1Unit: LearningUnit = {
  id: "toeic-l1-photographs",
  pathId: "toeic",
  title: "Listening Part 1",
  titleJa: "リスニング Part 1",
  subtitle: "Official skill: Photographs (Listening Part 1)",
  examPart: "L1",
  xpReward: 100,
  tutorial: {
    title: "Real TOEIC Part 1",
    titleJa: "本番の Part 1",
    bodyEn:
      "On the official TOEIC Listening and Reading test, Listening has 100 questions in about 45 minutes. Part 1 (Photographs) has 6 questions. You look at a photo and hear four statements (A to D). Only one matches the picture. Statements are not printed. In Lumi, we train the same skill with spoken scene descriptions and written choices (original content, not ETS materials).",
    bodyJa:
      "公式TOEIC L&Rのリスニングは約45分・100問です。Part 1（写真）は6問。写真を見ながらA〜Dの短い英文を聞き、写真と一致するものを選びます（選択肢は印刷されません）。Lumiでは同じ力を、オリジナルの場面描写音声で練習します。",
    tips: [
      "Focus on who is doing what, and where",
      "Ignore options that change one key detail",
      "Do not read ahead for meaning you did not hear",
    ],
  },
  exercises: [
    {
      id: "l1-1",
      kind: "listen-choice",
      prompt: "Listen, then choose the matching statement.",
      promptJa: "聞いて、合う文を選んでください。",
      ttsText:
        "A woman is typing on a laptop at a desk. There is a coffee cup beside the keyboard.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) She is writing on a whiteboard." },
        { id: "b", label: "B) She is using a laptop at a desk." },
        { id: "c", label: "C) She is standing in a hallway." },
        { id: "d", label: "D) She is talking on a phone outdoors." },
      ],
      correctChoiceId: "b",
      explanationEn: "The audio says she is typing on a laptop at a desk.",
      explanationJa: "音声はデスクでノートPCを使っている、と述べています。",
    },
    {
      id: "l1-2",
      kind: "listen-choice",
      prompt: "Which statement matches the scene?",
      promptJa: "場面に合う文はどれ？",
      ttsText:
        "Two men are shaking hands in front of an office building entrance.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) They are sitting at a conference table." },
        { id: "b", label: "B) They are boarding a train." },
        { id: "c", label: "C) They are shaking hands outside a building." },
        { id: "d", label: "D) They are packing boxes in a warehouse." },
      ],
      correctChoiceId: "c",
      explanationEn: "Handshake plus building entrance matches option C.",
      explanationJa: "握手とビル入口の描写に合うのは C です。",
    },
    {
      id: "l1-3",
      kind: "listen-choice",
      prompt: "Listen carefully for the main action.",
      promptJa: "主な動作に注意して聞いてください。",
      ttsText:
        "A delivery worker is unloading boxes from the back of a van.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Someone is loading luggage onto a plane." },
        { id: "b", label: "B) Someone is unloading boxes from a van." },
        { id: "c", label: "C) Someone is driving through a tunnel." },
        { id: "d", label: "D) Someone is sealing envelopes at a desk." },
      ],
      correctChoiceId: "b",
      explanationEn: "Unloading boxes from a van is stated directly.",
      explanationJa: "バンから箱を下ろしている、と明確に述べられています。",
    },
    {
      id: "l1-4",
      kind: "listen-choice",
      prompt: "Pick the best match.",
      promptJa: "最も合うものを選ぶ。",
      ttsText:
        "People are seated in rows facing a speaker at a podium.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) An audience is listening to a presentation." },
        { id: "b", label: "B) Shoppers are waiting in a checkout line." },
        { id: "c", label: "C) Runners are lining up at a starting line." },
        { id: "d", label: "D) Diners are ordering at a counter." },
      ],
      correctChoiceId: "a",
      explanationEn: "Rows facing a podium describes an audience at a talk.",
      explanationJa: "演台に向かって並ぶ座席はプレゼンの聴衆の場面です。",
    },
    {
      id: "l1-5",
      kind: "listen-choice",
      prompt: "What matches the audio?",
      promptJa: "音声に合うのは？",
      ttsText:
        "A clerk is handing a form across the counter to a customer.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) A customer is filling a shopping cart." },
        { id: "b", label: "B) A clerk is giving a form to a customer." },
        { id: "c", label: "C) A chef is tasting soup in a kitchen." },
        { id: "d", label: "D) A guard is locking a gate." },
      ],
      correctChoiceId: "b",
      explanationEn: "Handing a form across the counter matches B.",
      explanationJa: "カウンター越しに書類を渡す描写は B です。",
    },
    {
      id: "l1-6",
      kind: "listen-choice",
      prompt: "Listen, then choose the matching statement.",
      promptJa: "聞いて、合う文を選んでください。",
      ttsText:
        "A man is watering plants on a balcony outside an office.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) He is mowing a lawn in a park." },
        { id: "b", label: "B) He is watering plants on a balcony." },
        { id: "c", label: "C) He is painting a wall indoors." },
        { id: "d", label: "D) He is stacking chairs in a hall." },
      ],
      correctChoiceId: "b",
      explanationEn: "The audio describes watering plants on a balcony.",
      explanationJa: "音声はバルコニーで植物に水をやっている、と述べています。",
    },
    {
      id: "l1-7",
      kind: "listen-choice",
      prompt: "Which statement matches the scene?",
      promptJa: "場面に合う文はどれ？",
      ttsText:
        "A woman is pointing at a chart on a screen during a meeting.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) She is filing papers in a cabinet." },
        { id: "b", label: "B) She is scanning tickets at a gate." },
        { id: "c", label: "C) She is pointing at a chart on a screen." },
        { id: "d", label: "D) She is wrapping gifts at a counter." },
      ],
      correctChoiceId: "c",
      explanationEn: "Pointing at a chart on a screen matches option C.",
      explanationJa: "画面のグラフを指している描写に合うのは C です。",
    },
    {
      id: "l1-8",
      kind: "listen-choice",
      prompt: "Listen carefully for the main action.",
      promptJa: "主な動作に注意して聞いてください。",
      ttsText:
        "Workers are arranging chairs around a long conference table.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Workers are arranging chairs around a table." },
        { id: "b", label: "B) Workers are washing windows outside." },
        { id: "c", label: "C) Workers are loading carts into an elevator." },
        { id: "d", label: "D) Workers are tasting samples in a kitchen." },
      ],
      correctChoiceId: "a",
      explanationEn: "Arranging chairs around a conference table is stated directly.",
      explanationJa: "会議テーブルの周りに椅子を並べている、と明確です。",
    },
    {
      id: "l1-9",
      kind: "listen-choice",
      prompt: "Pick the best match.",
      promptJa: "最も合うものを選ぶ。",
      ttsText:
        "A security guard is checking badges at the building entrance.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) A guard is watering flowers in a lobby." },
        { id: "b", label: "B) A guard is checking badges at an entrance." },
        { id: "c", label: "C) A guard is serving coffee in a cafe." },
        { id: "d", label: "D) A guard is packing boxes in a warehouse." },
      ],
      correctChoiceId: "b",
      explanationEn: "Checking badges at the entrance matches B.",
      explanationJa: "入口でバッジを確認する描写は B です。",
    },
    {
      id: "l1-10",
      kind: "listen-choice",
      prompt: "What matches the audio?",
      promptJa: "音声に合うのは？",
      ttsText:
        "A technician is repairing a photocopier next to a supply shelf.",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) Someone is buying stamps at a post office." },
        { id: "b", label: "B) Someone is cooking lunch in a cafeteria." },
        { id: "c", label: "C) Someone is repairing a photocopier." },
        { id: "d", label: "D) Someone is hanging posters in a hallway." },
      ],
      correctChoiceId: "c",
      explanationEn: "Repairing a photocopier is the main action in the audio.",
      explanationJa: "コピー機を修理している、というのが主な動作です。",
    },
  ],
};
