import type { LearningUnit } from "@/lib/types";
import { withVocabTeach } from "@/content/toeic/vocab-factory";

const toeicVocabTravelUnitBase: LearningUnit = {
  id: "toeic-vocab-travel",
  pathId: "toeic",
  title: "VOCAB: Travel & logistics",
  titleJa: "語彙：旅行・物流",
  subtitle: "Airports, hotels, shipping, and schedules",
  examPart: "VOCAB",
  xpReward: 100,
  tutorial: {
    title: "Travel vocabulary on TOEIC",
    titleJa: "TOEICの旅行語彙",
    bodyEn:
      "Many Listening Parts 1 to 4 and Reading Part 7 texts use travel and logistics words: boarding pass, itinerary, delay, destination, courier. Build these before exam sections.",
    bodyJa:
      "Listening Part 1〜4やReading Part 7では、boarding pass, itinerary, delay, destination, courier などの旅行・物流語が頻出します。本番パートの前に固めましょう。",
    tips: [
      "Link each word to a travel scene",
      "Watch delay vs cancel",
      "Practice both listening and reading forms",
    ],
  },
  exercises: [
    {
      id: "v-tr-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "An 'itinerary' is:",
      promptJa: "itinerary とは？",
      choices: [
        { id: "a", label: "A) A travel schedule / plan" },
        { id: "b", label: "B) A hotel pillow" },
        { id: "c", label: "C) A passport photo" },
        { id: "d", label: "D) A taxi fare only" },
      ],
      correctChoiceId: "a",
      explanationEn: "Itinerary means a planned route or schedule.",
      explanationJa: "itinerary は旅程・予定表です。",
    },
    {
      id: "v-tr-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which word means '遅延'?",
      promptJa: "「遅延」の語は？",
      choices: [
        { id: "a", label: "A) delay" },
        { id: "b", label: "B) depart" },
        { id: "c", label: "C) deliver" },
        { id: "d", label: "D) deposit" },
      ],
      correctChoiceId: "a",
      explanationEn: "Delay = late / 遅延.",
      explanationJa: "delay は遅延です。",
    },
    {
      id: "v-tr-3",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word?",
      promptJa: "聞こえた語は？",
      ttsText: "boarding pass",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) boarding pass" },
        { id: "b", label: "B) business pass" },
        { id: "c", label: "C) border path" },
        { id: "d", label: "D) boring class" },
      ],
      correctChoiceId: "a",
      explanationEn: "Boarding pass is your ticket document to board a plane.",
      explanationJa: "boarding pass は搭乗券です。",
    },
    {
      id: "v-tr-4",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say 'destination'.",
      promptJa: "destination と言ってみましょう。",
      ttsText: "destination",
      ttsLang: "en-US",
      explanationEn: "Destination is the place you are going to.",
      explanationJa: "destination は目的地です。",
    },
    {
      id: "v-tr-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "A 'courier' most nearly means:",
      promptJa: "courier に最も近い意味は？",
      choices: [
        { id: "a", label: "A) A delivery service / messenger" },
        { id: "b", label: "B) A restaurant chef" },
        { id: "c", label: "C) A museum guide" },
        { id: "d", label: "D) A bank teller" },
      ],
      correctChoiceId: "a",
      explanationEn: "Courier is a person or service that delivers packages.",
      explanationJa: "courier は宅配便・配達人です。",
    },
    {
      id: "v-tr-6",
      kind: "multiple-choice",
      skill: "read",
      prompt: "A 'boarding gate' is:",
      promptJa: "boarding gate とは？",
      choices: [
        { id: "a", label: "A) The place at an airport where you enter the plane" },
        { id: "b", label: "B) A hotel breakfast menu" },
        { id: "c", label: "C) A type of suitcase lock" },
        { id: "d", label: "D) A taxi meter only" },
      ],
      correctChoiceId: "a",
      explanationEn: "A boarding gate is where passengers enter the aircraft.",
      explanationJa: "boarding gate は搭乗ゲートです。",
    },
    {
      id: "v-tr-7",
      kind: "write-choice",
      skill: "write",
      prompt: "Which word means '予約'?",
      promptJa: "「予約」の語は？",
      choices: [
        { id: "a", label: "A) reservation" },
        { id: "b", label: "B) renovation" },
        { id: "c", label: "C) resolution" },
        { id: "d", label: "D) recreation" },
      ],
      correctChoiceId: "a",
      explanationEn: "Reservation = booking / 予約.",
      explanationJa: "reservation は予約です。",
    },
    {
      id: "v-tr-8",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word?",
      promptJa: "聞こえた語は？",
      ttsText: "departure",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) department" },
        { id: "b", label: "B) departure" },
        { id: "c", label: "C) deposit" },
        { id: "d", label: "D) description" },
      ],
      correctChoiceId: "b",
      explanationEn: "Departure is the act of leaving, often a flight or train time.",
      explanationJa: "departure は出発です。",
    },
    {
      id: "v-tr-9",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say 'luggage'.",
      promptJa: "luggage と言ってみましょう。",
      ttsText: "luggage",
      ttsLang: "en-US",
      explanationEn: "Luggage means bags and suitcases for travel.",
      explanationJa: "luggage は荷物・手荷物です。",
    },
    {
      id: "v-tr-10",
      kind: "multiple-choice",
      skill: "read",
      prompt: "'The flight was canceled' most nearly means:",
      promptJa: "The flight was canceled に最も近い意味は？",
      choices: [
        { id: "a", label: "A) The flight will not operate" },
        { id: "b", label: "B) The flight left early" },
        { id: "c", label: "C) The flight had free meals" },
        { id: "d", label: "D) The flight changed seats only" },
      ],
      correctChoiceId: "a",
      explanationEn: "Canceled means the flight will not take place.",
      explanationJa: "canceled は運航中止・キャンセルです。",
    },
  ],
};

export const toeicVocabTravelUnit = withVocabTeach(toeicVocabTravelUnitBase, [
  {
    word: "itinerary",
    reading: "eye-TIN-uh-rer-ee",
    meaningEn: "travel plan / schedule",
    meaningJa: "旅程",
  },
  {
    word: "destination",
    reading: "des-ti-NAY-shun",
    meaningEn: "place you are going",
    meaningJa: "目的地",
  },
  {
    word: "delay",
    reading: "dih-LAY",
    meaningEn: "later than planned",
    meaningJa: "遅延",
  },
  {
    word: "courier",
    reading: "KUR-ee-er",
    meaningEn: "delivery messenger",
    meaningJa: "宅配・急送業者",
  },
  {
    word: "boarding pass",
    reading: "BOR-ding pass",
    meaningEn: "ticket to board a plane",
    meaningJa: "搭乗券",
  },
  {
    word: "luggage",
    reading: "LUG-ij",
    meaningEn: "bags for travel",
    meaningJa: "荷物",
  },
]);

