import type { LearningUnit } from "@/lib/types";

export const toeicVocabOfficeUnit: LearningUnit = {
  id: "toeic-vocab-office",
  pathId: "toeic",
  title: "VOCAB: Office basics",
  titleJa: "語彙：オフィス基礎",
  subtitle: "High-frequency workplace words for beginners",
  examPart: "VOCAB",
  xpReward: 100,
  tutorial: {
    title: "Why vocab first?",
    titleJa: "なぜ語彙から？",
    bodyEn:
      "TOEIC Listening and Reading both depend on workplace vocabulary. We start from scratch with office words you will see in Parts 1 to 7: agenda, deadline, invoice, memo, and more. Learn with English prompts and Japanese support.",
    bodyJa:
      "TOEICのListeningもReadingも、ビジネス語彙が土台です。まずはオフィスで頻出の語（agenda, deadline, invoice, memoなど）をゼロから学びます。英語の問題に日本語サポート付きです。",
    tips: [
      "Say each English word aloud",
      "Connect the word to a workplace scene",
      "Review wrong items the same day",
    ],
  },
  exercises: [
    {
      id: "v-off-1",
      kind: "multiple-choice",
      skill: "read",
      prompt: "What does 'deadline' mean?",
      promptJa: "deadline の意味は？",
      choices: [
        { id: "a", label: "A) A meeting room" },
        { id: "b", label: "B) The time something must be finished" },
        { id: "c", label: "C) A company logo" },
        { id: "d", label: "D) A holiday bonus" },
      ],
      correctChoiceId: "b",
      explanationEn: "A deadline is the latest time work must be completed.",
      explanationJa: "deadline は締切（完了しなければならない期限）です。",
    },
    {
      id: "v-off-2",
      kind: "write-choice",
      skill: "write",
      prompt: "Which word means '請求書'?",
      promptJa: "「請求書」に当たる語は？",
      choices: [
        { id: "a", label: "A) agenda" },
        { id: "b", label: "B) invoice" },
        { id: "c", label: "C) brochure" },
        { id: "d", label: "D) itinerary" },
      ],
      correctChoiceId: "b",
      explanationEn: "Invoice = bill / 請求書.",
      explanationJa: "invoice は請求書です。",
    },
    {
      id: "v-off-3",
      kind: "speak-prompt",
      skill: "speak",
      prompt: "Say 'agenda' clearly after LUMI.",
      promptJa: "agenda をはっきり言ってみましょう。",
      ttsText: "agenda",
      ttsLang: "en-US",
      explanationEn: "Agenda is the list of topics for a meeting.",
      explanationJa: "agenda は会議の議題リストです。",
    },
    {
      id: "v-off-4",
      kind: "listen-choice",
      skill: "listen",
      prompt: "Listen. Which word do you hear?",
      promptJa: "聞いて、聞こえた語を選ぶ。",
      ttsText: "memo",
      ttsLang: "en-US",
      choices: [
        { id: "a", label: "A) menu" },
        { id: "b", label: "B) memo" },
        { id: "c", label: "C) metro" },
        { id: "d", label: "D) medal" },
      ],
      correctChoiceId: "b",
      explanationEn: "Memo is a short workplace note.",
      explanationJa: "memo は社内の短い連絡文です。",
    },
    {
      id: "v-off-5",
      kind: "multiple-choice",
      skill: "read",
      prompt: "'Please RSVP by Friday' is closest to:",
      promptJa: "Please RSVP by Friday に最も近い意味は？",
      choices: [
        { id: "a", label: "A) Reply whether you will attend by Friday" },
        { id: "b", label: "B) Pay the invoice by Friday" },
        { id: "c", label: "C) Ship the package by Friday" },
        { id: "d", label: "D) Clean the office by Friday" },
      ],
      correctChoiceId: "a",
      explanationEn: "RSVP means reply to an invitation.",
      explanationJa: "RSVP は招待への出欠返信を意味します。",
    },
  ],
};
